// Source of truth for the WordPress must-use plugin that exposes a unified
// cache-purge + Elementor maintenance REST API. Deployed to
// /wp-content/mu-plugins/agent-cache-control.php by the cp_deploy_cache_helper
// tool. Authentication piggybacks on WordPress Application Passwords — every
// route requires the `manage_options` capability.
//
// Keep this string as the single source. The .php file on the server is a
// generated artifact; edit here and re-deploy.

export const CACHE_HELPER_FILENAME = 'agent-cache-control.php';
export const CACHE_HELPER_VERSION = '1.1.0';

export const CACHE_HELPER_PHP = `<?php
/**
 * Plugin Name: Agent Cache Control
 * Description: Unified cache-purge and Elementor maintenance REST API for MCP automation agents.
 * Version: ${CACHE_HELPER_VERSION}
 * Author: automation
 *
 * Auto-generated by cpanel-mcp (cp_deploy_cache_helper). Do not edit on the server;
 * edit src/assets/cacheHelperPlugin.ts and re-deploy.
 */

if (!defined('ABSPATH')) {
    exit;
}

/*
 * LiteSpeed / CGI / FastCGI SAPIs expose HTTP Basic credentials only as
 * HTTP_AUTHORIZATION (via the standard .htaccess rewrite), never as
 * PHP_AUTH_USER/PHP_AUTH_PW. WordPress Application Password authentication
 * reads ONLY PHP_AUTH_USER/PW, so REST auth silently fails (rest_not_logged_in)
 * on these hosts. mu-plugins load before authentication runs, so reconstruct
 * the PHP_AUTH_* pair here. This fixes REST auth for every plugin, not just this one.
 */
if (empty($_SERVER['PHP_AUTH_USER'])) {
    $agent_cache_auth = '';
    if (!empty($_SERVER['HTTP_AUTHORIZATION'])) {
        $agent_cache_auth = $_SERVER['HTTP_AUTHORIZATION'];
    } elseif (!empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        $agent_cache_auth = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
    }
    if (stripos($agent_cache_auth, 'basic ') === 0) {
        $agent_cache_decoded = base64_decode(substr($agent_cache_auth, 6), true);
        if ($agent_cache_decoded !== false && strpos($agent_cache_decoded, ':') !== false) {
            list($agent_cache_u, $agent_cache_p) = explode(':', $agent_cache_decoded, 2);
            $_SERVER['PHP_AUTH_USER'] = $agent_cache_u;
            $_SERVER['PHP_AUTH_PW']   = $agent_cache_p;
        }
    }
}

const AGENT_CACHE_NS = 'agent-cache/v1';

add_action('rest_api_init', function () {
    $auth = function () {
        return current_user_can('manage_options');
    };

    register_rest_route(AGENT_CACHE_NS, '/ping', [
        'methods'             => 'GET',
        'permission_callback' => $auth,
        'callback'            => function () {
            return new WP_REST_Response([
                'ok'      => true,
                'version' => '${CACHE_HELPER_VERSION}',
                'caches'  => agent_cache_detect_layers(),
            ], 200);
        },
    ]);

    register_rest_route(AGENT_CACHE_NS, '/purge', [
        'methods'             => 'POST',
        'permission_callback' => $auth,
        'callback'            => 'agent_cache_purge',
        'args'                => [
            'urls' => ['required' => false],
            'all'  => ['required' => false],
        ],
    ]);

    register_rest_route(AGENT_CACHE_NS, '/elementor/regenerate-css', [
        'methods'             => 'POST',
        'permission_callback' => $auth,
        'callback'            => 'agent_cache_elementor_regenerate',
        'args'                => [
            'post_id' => ['required' => false],
        ],
    ]);

    register_rest_route(AGENT_CACHE_NS, '/elementor/bust-image-urls', [
        'methods'             => 'POST',
        'permission_callback' => $auth,
        'callback'            => 'agent_cache_elementor_bust',
        'args'                => [
            'post_id'      => ['required' => true],
            'version'      => ['required' => false],
            'replacements' => ['required' => false],
        ],
    ]);

    register_rest_route(AGENT_CACHE_NS, '/post-meta', [
        [
            'methods'             => 'GET',
            'permission_callback' => $auth,
            'callback'            => 'agent_cache_get_meta',
            'args'                => [
                'post_id' => ['required' => true],
                'key'     => ['required' => true],
            ],
        ],
        [
            'methods'             => 'POST',
            'permission_callback' => $auth,
            'callback'            => 'agent_cache_set_meta',
            'args'                => [
                'post_id' => ['required' => true],
                'key'     => ['required' => true],
                'value'   => ['required' => true],
            ],
        ],
    ]);
});

/**
 * Report which known cache layers are active on this install.
 */
function agent_cache_detect_layers() {
    return [
        'litespeed'    => defined('LSCWP_V') || has_action('litespeed_purge_all'),
        'nginx_helper' => has_action('rt_nginx_helper_purge_all') || class_exists('Nginx_Helper'),
        'wp_rocket'    => function_exists('rocket_clean_domain'),
        'w3tc'         => function_exists('w3tc_flush_all'),
        'wp_super'     => function_exists('wp_cache_clear_cache'),
        'autoptimize'  => class_exists('autoptimizeCache'),
        'sg_optimizer' => function_exists('sg_cachepress_purge_cache'),
        'elementor'    => did_action('elementor/loaded') || class_exists('\\\\Elementor\\\\Plugin'),
        'object_cache' => wp_using_ext_object_cache(),
    ];
}

/**
 * Fire every available purge mechanism. If specific URLs are given, prefer
 * targeted purges where the active plugin supports them, otherwise purge all.
 */
function agent_cache_purge(WP_REST_Request $req) {
    $urls    = $req->get_param('urls');
    $all     = $req->get_param('all');
    $targets = is_array($urls) ? array_values(array_filter(array_map('esc_url_raw', $urls))) : [];
    $purgeAll = $all === true || $all === '1' || $all === 1 || empty($targets);
    $fired   = [];

    // Core object cache.
    wp_cache_flush();
    $fired[] = 'wp_cache_flush';

    // LiteSpeed Cache.
    if ($purgeAll) {
        do_action('litespeed_purge_all');
        $fired[] = 'litespeed_purge_all';
    } else {
        foreach ($targets as $u) {
            do_action('litespeed_purge_url', $u);
        }
        $fired[] = 'litespeed_purge_url';
    }

    // Nginx Helper (FastCGI/proxy cache).
    if ($purgeAll) {
        do_action('rt_nginx_helper_purge_all');
        $fired[] = 'rt_nginx_helper_purge_all';
    } else {
        foreach ($targets as $u) {
            do_action('rt_nginx_helper_purge_url', $u);
        }
        $fired[] = 'rt_nginx_helper_purge_url';
    }

    // WP Rocket.
    if (function_exists('rocket_clean_domain')) {
        if ($purgeAll || empty($targets)) {
            rocket_clean_domain();
        } elseif (function_exists('rocket_clean_files')) {
            rocket_clean_files($targets);
        }
        $fired[] = 'wp_rocket';
    }

    // W3 Total Cache.
    if ($purgeAll && function_exists('w3tc_flush_all')) {
        w3tc_flush_all();
        $fired[] = 'w3tc_flush_all';
    } elseif (!$purgeAll && function_exists('w3tc_flush_url')) {
        foreach ($targets as $u) {
            w3tc_flush_url($u);
        }
        $fired[] = 'w3tc_flush_url';
    }

    // WP Super Cache.
    if (function_exists('wp_cache_clear_cache')) {
        wp_cache_clear_cache();
        $fired[] = 'wp_super_cache';
    }

    // Autoptimize.
    if (class_exists('autoptimizeCache')) {
        autoptimizeCache::clearall();
        $fired[] = 'autoptimize';
    }

    // SiteGround Optimizer.
    if (function_exists('sg_cachepress_purge_cache')) {
        sg_cachepress_purge_cache();
        $fired[] = 'sg_optimizer';
    }

    return new WP_REST_Response([
        'ok'        => true,
        'mode'      => $purgeAll ? 'all' : 'targeted',
        'targets'   => $targets,
        'mechanisms'=> $fired,
    ], 200);
}

/**
 * Clear (regenerate) Elementor's generated CSS so the front-end re-renders.
 */
function agent_cache_elementor_regenerate(WP_REST_Request $req) {
    if (!class_exists('\\\\Elementor\\\\Plugin')) {
        return new WP_Error('no_elementor', 'Elementor is not active', ['status' => 400]);
    }
    $postId = (int) $req->get_param('post_id');
    $files  = \\Elementor\\Plugin::$instance->files_manager;

    if ($postId > 0) {
        $css = \\Elementor\\Core\\Files\\CSS\\Post::create($postId);
        $css->delete();
        $css->update();
        $scope = 'post:' . $postId;
    } else {
        $files->clear_cache();
        $scope = 'all';
    }

    return new WP_REST_Response(['ok' => true, 'regenerated' => $scope], 200);
}

/**
 * Safely rewrite image URLs inside _elementor_data. Operates on decoded JSON
 * so length-prefixed serialization can never be corrupted. Two modes:
 *  - version: append/replace a ?ver=<v> query string on every image URL.
 *  - replacements: [{from, to}] exact substring swaps on URLs.
 */
function agent_cache_elementor_bust(WP_REST_Request $req) {
    $postId       = (int) $req->get_param('post_id');
    $version      = $req->get_param('version');
    $replacements = $req->get_param('replacements');

    if ($postId <= 0) {
        return new WP_Error('bad_post', 'post_id required', ['status' => 400]);
    }

    $raw = get_post_meta($postId, '_elementor_data', true);
    if (empty($raw)) {
        return new WP_Error('no_data', 'No _elementor_data for this post', ['status' => 404]);
    }

    // Elementor stores a JSON string (sometimes already an array via filters).
    $data = is_array($raw) ? $raw : json_decode($raw, true);
    if (json_last_error() !== JSON_ERROR_NONE && !is_array($data)) {
        return new WP_Error('bad_json', 'Could not decode _elementor_data: ' . json_last_error_msg(), ['status' => 500]);
    }

    $count = 0;
    $repMap = [];
    if (is_array($replacements)) {
        foreach ($replacements as $r) {
            if (isset($r['from'], $r['to'])) {
                $repMap[(string) $r['from']] = (string) $r['to'];
            }
        }
    }

    $walker = function (&$node) use (&$walker, &$count, $repMap, $version) {
        if (!is_array($node)) {
            return;
        }
        foreach ($node as $key => &$value) {
            if (is_array($value)) {
                // Image control shape: ['url' => ..., 'id' => ...]
                if (isset($value['url']) && is_string($value['url'])) {
                    $original = $value['url'];
                    $url = $original;
                    foreach ($repMap as $from => $to) {
                        if (strpos($url, $from) !== false) {
                            $url = str_replace($from, $to, $url);
                        }
                    }
                    if (!empty($version) && agent_cache_is_image_url($url)) {
                        $url = agent_cache_set_query_arg($url, 'ver', (string) $version);
                    }
                    if ($url !== $original) {
                        $value['url'] = $url;
                        $count++;
                    }
                }
                $walker($value);
            } elseif (is_string($value)) {
                // Inline URLs inside text/html widgets.
                $original = $value;
                foreach ($repMap as $from => $to) {
                    if (strpos($value, $from) !== false) {
                        $value = str_replace($from, $to, $value);
                    }
                }
                if ($value !== $original) {
                    $count++;
                }
            }
        }
        unset($value);
    };
    $walker($data);

    if ($count > 0) {
        // Re-encode and store with slashes the way Elementor expects.
        $encoded = wp_json_encode($data);
        update_post_meta($postId, '_elementor_data', wp_slash($encoded));

        // Regenerate that post's CSS so changes show without manual save.
        if (class_exists('\\\\Elementor\\\\Core\\\\Files\\\\CSS\\\\Post')) {
            $css = \\Elementor\\Core\\Files\\CSS\\Post::create($postId);
            $css->delete();
            $css->update();
        }
    }

    return new WP_REST_Response(['ok' => true, 'post_id' => $postId, 'changed' => $count], 200);
}

function agent_cache_is_image_url($url) {
    return (bool) preg_match('/\\.(png|jpe?g|gif|webp|svg|avif)(\\?|$)/i', $url);
}

function agent_cache_set_query_arg($url, $key, $val) {
    $parts = explode('#', $url, 2);
    $frag  = isset($parts[1]) ? '#' . $parts[1] : '';
    $base  = $parts[0];
    $split = explode('?', $base, 2);
    $path  = $split[0];
    $query = isset($split[1]) ? $split[1] : '';
    parse_str($query, $args);
    $args[$key] = $val;
    return $path . '?' . http_build_query($args) . $frag;
}

function agent_cache_get_meta(WP_REST_Request $req) {
    $postId = (int) $req->get_param('post_id');
    $key    = sanitize_text_field($req->get_param('key'));
    $value  = get_post_meta($postId, $key, true);
    return new WP_REST_Response(['post_id' => $postId, 'key' => $key, 'value' => $value], 200);
}

function agent_cache_set_meta(WP_REST_Request $req) {
    $postId = (int) $req->get_param('post_id');
    $key    = sanitize_text_field($req->get_param('key'));
    $value  = $req->get_param('value');
    // Meta keys that hold JSON must be stored slashed.
    if (is_string($value) && in_array($key, ['_elementor_data'], true)) {
        $value = wp_slash($value);
    }
    $ok = update_post_meta($postId, $key, $value);
    return new WP_REST_Response(['ok' => $ok !== false, 'post_id' => $postId, 'key' => $key], 200);
}
`;
