"""PRD content module for the Brevo MCP server."""

TOOLS = [
    ("brevo_preflight", "Read", "Pass/fail checklist: API key valid, credits remaining, enforced sender exists and is active, dry-run state."),
    ("brevo_get_account", "Read", "Account company, plan and remaining email credits."),
    ("brevo_list_senders", "Read", "Verified sender identities with active flag."),
    ("brevo_check_domain_auth", "Read", "DKIM, DMARC and Brevo-code status for one sending domain."),
    ("brevo_list_lists", "Read", "Contact lists with subscriber and blacklist counts."),
    ("brevo_list_folders", "Read", "Contact folders; a folderId is required to create a list."),
    ("brevo_get_contact", "Read", "One contact by email, including blacklist status and list membership."),
    ("brevo_list_contacts_in_list", "Read", "Contacts belonging to a given list id."),
    ("brevo_get_import_status", "Read", "Status of an async contact import by processId."),
    ("brevo_list_campaigns", "Read", "Campaigns filtered by status, with headline statistics."),
    ("brevo_get_campaign", "Read", "One campaign with full delivery and engagement statistics."),
    ("brevo_get_email_events", "Read", "Per-recipient events: bounces, spam, opens, clicks, unsubscribes."),
    ("brevo_campaign_report", "Read", "Cross-campaign deliverability report with MPP-corrected open rate and threshold warnings."),
    ("brevo_create_list", "Write", "Create a contact list in a folder; returns the new list id."),
    ("brevo_import_contacts", "Write", "Bulk import contacts into a list from inline CSV; returns a processId."),
    ("brevo_blacklist_contact", "Write", "Permanent opt-out; no future campaign can email the address."),
    ("brevo_create_campaign", "Write", "Create a campaign. Always a DRAFT; sender-lock enforced; no send option exists."),
    ("brevo_update_campaign", "Write", "Patch a draft campaign; only supplied fields change."),
    ("brevo_send_test_email", "Write", "Send a test copy to 1-10 named addresses only."),
    ("brevo_schedule_campaign", "Write", "Schedule a future send. Requires confirm=\"SCHEDULE\" and passes the sender lock."),
    ("brevo_send_campaign_now", "Write", "IRREVERSIBLE full-list send. Requires confirm=\"SEND\" and passes the sender lock."),
]

READ_COUNT = sum(1 for t in TOOLS if t[1] == "Read")
WRITE_COUNT = sum(1 for t in TOOLS if t[1] == "Write")

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "Brevo MCP Server",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        # 1
        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Status", "Summary of Change"],
         "rows": [["0.1", "2026-07-22", "Musfiqur Tuhin", "Draft", "Initial PRD written from the shipped v1.0.0 source at Tooling/MCP/brevo-mcp."]]},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Sign-off"],
         "rows": [
             ["Document Owner", "Musfiqur Tuhin", "Authors and maintains this PRD", "Owner"],
             ["Engineering Owner", "Musfiqur Tuhin", "Maintains brevo-mcp source, tests and releases", "Pending"],
             ["Operations Owner", "HaorGrix", "Holds the Brevo API key and the sending reputation", "Pending"],
             ["Campaign Approver", "TBD — named person who authorises a live send", "Approves any brevo_send_campaign_now invocation", "Pending"],
         ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Repository: HaorGrix/mcp-servers (private), branch main, folder Tooling/MCP/brevo-mcp.",
            "brevo-mcp/README.md — setup, environment table, safety design, known limits.",
            "Brevo API v3 reference (https://developers.brevo.com), the upstream contract this server wraps.",
            "Model Context Protocol specification, as implemented by @modelcontextprotocol/sdk ^1.12.0.",
            "brevo-mcp/.env.example — the canonical list of supported environment variables.",
        ]},

        # 2
        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "Email campaign work against Brevo is done by hand through a web console or by ad-hoc scripts holding a raw API key. Both are unsafe in the presence of an AI agent: a send is irreversible, outward-facing and reputation-bearing, and the Brevo API will happily accept a full-list blast as a single unguarded POST. The concrete failure this server was built after is on record — 26 of 27 Podium Tutoring campaigns were sent from a podiumtutor@gmail.com address that Brevo cannot DKIM-sign for gmail.com, which put the mail in spam and was not detected until after the fact."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": f"brevo-mcp is a Node/TypeScript MCP server, v1.0.0, that exposes {len(TOOLS)} tools ({READ_COUNT} read, {WRITE_COUNT} write) over stdio to an MCP client. Every call passes through a single HTTP client that enforces a token-bucket rate limit, retries only retryable statuses with jittered backoff, redacts the API key from every error string, and appends a JSON line to an audit log for every mutating request. Campaigns can only be created as drafts. Sending requires a literal confirm token, and every send path re-reads the campaign and checks its sender against BREVO_ENFORCE_SENDER before the request leaves the machine."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "The server was written for the Podium Tutoring email programme, but the only Podium-specific artefact is the default sender lock value in .env.example. It is the only server in the MCP monorepo that ships a test suite: 34 tests across src/tests/unit.test.ts and src/tests/client.test.ts, run by the Node test runner under tsx."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "It is part of the HaorGrix internal MCP tooling line, which gives agents first-class access to the operational SaaS the business already runs on. Brevo is the highest-blast-radius member of that set, so it also serves as the reference implementation for guard design — config validation at boot, confirm-string gates, audit trail, secret redaction — that the other servers are expected to adopt."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Make routine campaign work (list hygiene, drafting, test sends, reporting) delegable to an agent without a human in the loop for each step.",
            "Make the one irreversible action — a full-list send — require an explicit, unambiguous human-authored token.",
            "Prevent the DKIM-misalignment class of error structurally rather than by remembering to check.",
            "Produce an accountability trail that survives the agent session, so what went out and when is answerable from disk.",
            "Report honest engagement numbers by correcting for Apple Mail Privacy Protection prefetch opens where the data allows.",
        ]},

        # 3
        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "G1 — Zero campaigns sent from a non-enforced sender address in any environment where BREVO_ENFORCE_SENDER is set, measured continuously from the audit log.",
            "G2 — Zero unintended full-list sends: every /sendNow entry in the audit log traces to a deliberate confirm=\"SEND\" call.",
            "G3 — Keep npm run check (typecheck plus 34 tests) green on main at every commit.",
            "G4 — Zero occurrences of an xkeysib- key in any audit line, error message or stderr output.",
            "G5 — Zero 429-driven tool failures under normal operation; throttling is absorbed by the limiter and the retry curve.",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"],
         "rows": [
             ["Sends from a mismatched sender", "26 of 27 historical Podium campaigns", "0", "assertSenderAllowed throws; audit log shows no /sendNow for a mismatched address"],
             ["Unconfirmed send attempts reaching Brevo", "n/a (no gate before v1.0.0)", "0", "zod literal on confirm rejects at schema level; failures never reach the client"],
             ["Test pass rate on main", "34/34", "34/34", "npm run check in CI or pre-commit"],
             ["API key appearances in logs or errors", "unmeasured", "0", "redact() applied at BrevoApiError construction and audit write; two unit tests assert it"],
             ["Mutating calls without an audit line", "n/a", "0", "every non-GET path writes success, error or dry-run to audit.jsonl"],
             ["Tool failures caused by HTTP 429", "unmeasured", "0", "token bucket at BREVO_RPS plus Retry-After-aware retry; audit attempts field"],
         ]},
        {"kind": "h2", "text": "3.3 Non-Goals"},
        {"kind": "bullets", "items": [
            "No transactional/SMTP send endpoint. Only campaign email is exposed; /smtp is used for statistics only.",
            "No reply tracking. Replies go to the Reply-To mailbox and never touch Brevo, so no API can report them. They are counted by hand.",
            "No HTTP or SSE transport. stdio only.",
            "No contact deletion, list deletion or campaign deletion tools.",
            "No template management, no automation/workflow API, no SMS or WhatsApp channel.",
            "No multi-account or multi-tenant support; one API key per process.",
            "No end-user GUI. The consumer is an MCP client.",
        ]},

        # 4
        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"],
         "rows": [
             ["Persona", "AI coding/ops agent operating through an MCP client (Claude Code)"],
             ["Context", "Runs the server as a stdio child process with the operator's API key in its environment"],
             ["Goal", "Prepare, verify, send and report on an email campaign end to end without a console session"],
             ["Affordances", "Tool names, tool descriptions and zod argument schemas are the entire interface"],
             ["Failure mode guarded against", "Confidently invoking an irreversible send, or inventing a sender address"],
             ["Success criterion", "Preflight passes, a draft is created, a test lands, and the live send is gated behind a token the human supplied"],
         ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "Campaign operator (HaorGrix) — reads brevo_preflight and brevo_campaign_report output, authors the confirm token, owns the sending reputation.",
            "Maintainer engineer — extends the tool surface, keeps the test suite green, rotates the API key.",
            "Incident reviewer — reconstructs what was sent, when, and after how many attempts from audit.jsonl.",
        ]},

        # 5
        {"kind": "break"},
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an agent, I run brevo_preflight before any campaign work so a bad key, an unverified sender or exhausted credits fails early and legibly.",
            "As an agent, I create a campaign knowing the tool cannot send it, so drafting is a safe operation.",
            "As an operator, I set BREVO_ENFORCE_SENDER so no agent can send from an address my domain cannot DKIM-sign.",
            "As an operator, I set BREVO_DRY_RUN while an agent explores, so every write is refused and still recorded.",
            "As an agent, I import a contact CSV and poll brevo_get_import_status until the async process completes.",
            "As an operator, I read brevo_campaign_report and see an open rate with Apple MPP prefetches removed, or an explicit null when Brevo did not supply the MPP figure.",
            "As an incident reviewer, I open audit.jsonl and see every mutation with timestamp, method, path, status, duration and attempt count, with no credentials in it.",
            "As an agent, I hit a 429 and the call still succeeds because the client honoured Retry-After and retried.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"],
         "rows": [
             ["FR-1", "Boot-time configuration validation", "Must", "loadConfig throws on a missing key, a key without the xkeysib- prefix, a non-email BREVO_ENFORCE_SENDER, a non-boolean flag, or an out-of-range integer; index.ts logs the message and exits 1 rather than starting."],
             ["FR-2", "Health and preflight tooling", "Must", "brevo_preflight returns {ready, checks[]} covering api_key, credits, enforced_sender and dry_run; it returns ready=false immediately if the account call fails."],
             ["FR-3", "Account and sender inspection", "Must", "brevo_get_account, brevo_list_senders and brevo_check_domain_auth return the corresponding Brevo payloads; the domain argument is URL-encoded."],
             ["FR-4", "Contact list and folder management", "Must", "brevo_list_lists, brevo_list_folders and brevo_create_list (name plus required folderId) operate against /contacts/lists and /contacts/folders."],
             ["FR-5", "Contact lookup", "Must", "brevo_get_contact (email-validated, URL-encoded) and brevo_list_contacts_in_list (limit 1-500, default 50) return contact records."],
             ["FR-6", "Bulk contact import", "Should", "brevo_import_contacts posts inline CSV with listIds, updateExistingContacts (default true) and emptyContactsAttributes (default false), returning a processId that brevo_get_import_status resolves."],
             ["FR-7", "Permanent opt-out", "Must", "brevo_blacklist_contact PUTs emailBlacklisted=true and returns a plain-language confirmation naming the address."],
             ["FR-8", "Draft-only campaign creation", "Must", "brevo_create_campaign accepts name, subject, senderName, senderEmail, replyTo, htmlContent, listIds (min 1) and optional exclusionListIds; it sets inlineImageActivation=false, exposes no send option, and returns the draft id with an explicit 'nothing has been sent' message."],
             ["FR-9", "Campaign amendment", "Should", "brevo_update_campaign PUTs only the supplied fields; listIds is rewritten into recipients.listIds."],
             ["FR-10", "Test send", "Must", "brevo_send_test_email accepts 1-10 email-validated addresses and posts to /sendTest; no other recipient can receive it."],
             ["FR-11", "Gated live send", "Must", "brevo_send_campaign_now requires confirm to equal the literal string SEND, re-reads the campaign, runs the sender check against its actual sender.email, then posts /sendNow."],
             ["FR-12", "Gated scheduling", "Must", "brevo_schedule_campaign requires confirm to equal the literal string SCHEDULE, runs the same sender check, then PUTs scheduledAt as an ISO 8601 datetime with offset."],
             ["FR-13", "Sender lock", "Must", "When BREVO_ENFORCE_SENDER is set, assertSenderAllowed throws for any non-matching address on create, send-now and schedule, with a message naming both addresses and the DKIM reason. When unset it is a no-op and preflight raises a warn."],
             ["FR-14", "Dry-run mode", "Must", "With BREVO_DRY_RUN on, every non-GET request throws DryRunError before any network call and still writes an audit line with status 'dry-run'; GET requests are unaffected."],
             ["FR-15", "Rate limiting", "Must", "A token bucket sized at BREVO_RPS (default 8, range 1-100) allows a full burst to capacity, then makes callers wait; it refills over time and never exceeds capacity when idle."],
             ["FR-16", "Retry policy", "Must", "Only 408, 429 and 5xx are retried, up to BREVO_MAX_RETRIES (default 3, range 0-10), using Retry-After when present and otherwise exponential backoff with full jitter capped at 20s. 4xx client errors are not retried."],
             ["FR-17", "Audit trail", "Must", "Every non-GET request appends one JSON line (ts, method, path, status, durationMs, attempts, optional redacted detail) to BREVO_AUDIT_LOG; GET requests are not audited; a failed audit write logs to stderr and never crashes the server."],
             ["FR-18", "Credential redaction", "Must", "redact() replaces any xkeysib- token with a placeholder in every error message and audit detail; two unit tests assert both the replacing and the non-replacing case."],
             ["FR-19", "Error surfacing", "Must", "Non-2xx responses become BrevoApiError carrying status, Brevo error code, redacted message and attempt count; a non-JSON error body is preserved as raw text; an unparseable 2xx body raises code bad_json."],
             ["FR-20", "Exhaustive pagination", "Should", "getAll walks pages of up to 500 until a short or empty page, and throws after 200 pages rather than looping, telling the caller to narrow the query."],
             ["FR-21", "Event statistics", "Must", "brevo_get_email_events filters by one of twelve event types, recipient email and a date range, with limit 1-1000 (default 100)."],
             ["FR-22", "Deliverability reporting", "Must", "brevo_campaign_report reads up to 100 sent campaigns and returns per-campaign sent, delivered, bounce rate, open rate, appleMppOpens, MPP-corrected realOpenRate, click rate, complaints, unsubscribes and warnings; realOpenRate is null when Brevo supplied no globalStats to derive MPP from."],
             ["FR-23", "Deliverability warnings", "Must", "Reports flag a free-mailbox sender domain (gmail, yahoo, hotmail, outlook), a bounce rate above 3% and a complaint rate above 0.1%."],
             ["FR-24", "stdio transport and lifecycle", "Must", "The server connects StdioServerTransport, prints a one-line startup banner to stderr stating mode, base URL, sender lock, rps, retries and audit path, and exits 0 on SIGINT/SIGTERM."],
         ]},
        {"kind": "h2", "text": "5.2.1 Complete Tool Inventory"},
        {"kind": "table", "header": ["Tool", "Class", "Behaviour"],
         "rows": [[name, cls, desc] for name, cls, desc in TOOLS]},
        {"kind": "meta", "text": f"{len(TOOLS)} tools total: {READ_COUNT} read, {WRITE_COUNT} write. This list is exhaustive as of v1.0.0."},
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Campaign launch: brevo_preflight → brevo_list_lists → brevo_create_campaign (draft) → brevo_send_test_email → human supplies confirm → brevo_send_campaign_now or brevo_schedule_campaign → brevo_campaign_report.",
            "Audience build: brevo_list_folders → brevo_create_list → brevo_import_contacts → brevo_get_import_status (poll) → brevo_list_contacts_in_list.",
            "Deliverability triage: brevo_campaign_report → brevo_get_email_events filtered to hardBounces or spam → brevo_blacklist_contact per offending address.",
            "Sender diagnosis: brevo_list_senders → brevo_check_domain_auth → fix DKIM/DMARC in Brevo → brevo_preflight to confirm.",
            "Blocked write: any write while BREVO_DRY_RUN is on → DryRunError returned to the agent, audit line written with status dry-run, no network call made.",
        ]},

        # 6
        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"],
         "rows": [
             ["Performance", "Tool latency is dominated by the Brevo API. Local overhead is a token-bucket check and JSON serialisation. Per-request timeout is BREVO_TIMEOUT_MS (default 30s, range 1s-120s) enforced via AbortController."],
             ["Scalability", "Single process, single API key, one MCP client. Outbound throughput is capped at BREVO_RPS (default 8). getAll pages at 500 per request up to 200 pages, then refuses to continue."],
             ["Availability", "No uptime target; the process is spawned on demand by the MCP client. Resilience is per-request: retry on 408/429/5xx with jittered backoff honouring Retry-After. Brevo outages surface as BrevoApiError."],
             ["Security", "API key supplied only through the environment via dotenv, never an argument. Key format validated at boot. redact() strips any xkeysib- token from errors and audit details. Write paths gated by dry-run, sender lock and literal confirm tokens."],
             ["Privacy / Compliance", "The server handles contact email addresses and engagement events, which are personal data. It does not persist them — the audit log records method, path and status only, never request bodies. brevo_blacklist_contact provides an opt-out path. Brevo remains the system of record."],
             ["Accessibility", "N/A — no human-facing UI. Operator-facing output is plain text and JSON on stdout/stderr, readable by a screen reader through the host terminal."],
             ["Observability", "Startup banner on stderr states mode, base URL, sender lock, rps, retries and audit path. audit.jsonl is an append-only JSONL record of every mutation including attempt counts and failures. Audit write failures are reported on stderr and never fatal. No metrics endpoint and no structured read-path logging exist."],
             ["Localization", "N/A — single-locale English tool descriptions and error strings for an English-speaking operator and an English-language agent. Campaign content itself is caller-supplied and locale-agnostic."],
         ]},

        # 7
        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "bullets", "items": [
            "Node.js >= 18 (native fetch and AbortController required), TypeScript 5.7, ESM, compiled by tsc to dist/.",
            "Runtime dependencies: @modelcontextprotocol/sdk ^1.12.0, zod ^3.23.8, dotenv ^16.4.7. Dev: tsx ^4.19.2, typescript ^5.7.2, @types/node ^22.",
            "Layers: index.ts (config load, client construction, five tool-group registrations, stdio transport) → tools/*.ts (zod schemas plus handlers) → client.ts (BrevoClient: request loop, retries, dry-run gate, audit) → ratelimit.ts and audit.ts (policy primitives) → config.ts (validation and redaction).",
            "Tool groups: health.ts, account.ts, contacts.ts, campaigns.ts, stats.ts, with a shared ok() result formatter in helpers.ts.",
            "Roughly 1,400 lines of source including 313 lines of tests across two files.",
            "Scripts: build (tsc), start (node dist/index.js), dev (tsx src/index.ts), typecheck (tsc --noEmit), test (tsx --test src/tests/*.test.ts), check (typecheck then test).",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "para", "text": "The server holds no database and no persistent state beyond the append-only audit log. types.ts declares the response shapes consumed from Brevo — BrevoAccount, BrevoSender, BrevoContact, BrevoContactsResponse, BrevoListsResponse, BrevoImportResponse, BrevoCampaign, BrevoCampaignList, BrevoCampaignStats and BrevoError. Every tool result is returned as a single MCP text block containing either pretty-printed JSON or a plain-language sentence."},
        {"kind": "table", "header": ["Brevo endpoint", "Method", "Used by"],
         "rows": [
             ["/account", "GET", "brevo_get_account, brevo_preflight"],
             ["/senders", "GET", "brevo_list_senders, brevo_preflight"],
             ["/senders/domains/{domain}", "GET", "brevo_check_domain_auth"],
             ["/contacts/lists", "GET, POST", "brevo_list_lists, brevo_create_list"],
             ["/contacts/folders", "GET", "brevo_list_folders"],
             ["/contacts/{email}", "GET, PUT", "brevo_get_contact, brevo_blacklist_contact"],
             ["/contacts/lists/{id}/contacts", "GET", "brevo_list_contacts_in_list"],
             ["/contacts/import", "POST", "brevo_import_contacts"],
             ["/processes/{id}", "GET", "brevo_get_import_status"],
             ["/emailCampaigns", "GET, POST", "brevo_list_campaigns, brevo_create_campaign, brevo_campaign_report"],
             ["/emailCampaigns/{id}", "GET, PUT", "brevo_get_campaign, brevo_update_campaign, brevo_schedule_campaign"],
             ["/emailCampaigns/{id}/sendTest", "POST", "brevo_send_test_email"],
             ["/emailCampaigns/{id}/sendNow", "POST", "brevo_send_campaign_now"],
             ["/smtp/statistics/events", "GET", "brevo_get_email_events"],
         ]},
        {"kind": "h2", "text": "7.3 Integrations"},
        {"kind": "table", "header": ["Dependency", "Owner", "Type", "Status"],
         "rows": [
             ["Brevo API v3", "Brevo (external SaaS)", "REST over HTTPS, api-key header", "Live"],
             ["@modelcontextprotocol/sdk", "Anthropic (open source)", "MCP server framework, stdio transport", "Live, pinned ^1.12.0"],
             ["zod", "Open source", "Tool argument schemas and confirm-literal gates", "Live"],
             ["dotenv", "Open source", "Loads .env into process.env at startup", "Live"],
             ["MCP client (Claude Code)", "HaorGrix operator", "Spawns the server over stdio", "Live, registered via claude mcp add"],
             ["Local filesystem", "Host machine", "Append-only audit.jsonl", "Live"],
             ["DNS / DKIM / DMARC for the sending domain", "HaorGrix", "Deliverability prerequisite, read via brevo_check_domain_auth", "Operator-managed"],
         ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "Brevo cannot observe replies. For reply-driven campaigns, open and click rate are noise and replies must be counted in the Reply-To mailbox by hand.",
            "Apple Mail Privacy Protection prefetches images and inflates unique opens. appleMppOpens is only present on globalStats, which Brevo zeroes for list-based campaigns; in that case realOpenRate is reported as null rather than a falsely precise figure.",
            "The API key is assumed to be scoped to a single Brevo account and is not rotated by the server.",
            "The agent is assumed to be trusted-but-fallible: it may misread intent, so guards are structural rather than advisory.",
            "Audit integrity depends on a writable path; the log is neither rotated nor shipped anywhere.",
            "The default sender lock in .env.example is Podium-specific and must be changed for any other programme.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "table", "header": ["Event", "Trigger", "Properties", "Destination"],
         "rows": [
             ["mutation_success", "Any non-GET request returning 2xx", "ts, method, path, status, durationMs, attempts", "audit.jsonl (BREVO_AUDIT_LOG)"],
             ["mutation_error", "Any non-GET request exhausting retries or failing non-retryably", "ts, method, path, status='error', durationMs, attempts, redacted detail", "audit.jsonl"],
             ["dry_run_refusal", "Any non-GET request while BREVO_DRY_RUN is on", "ts, method, path, status='dry-run', durationMs=0, attempts=0", "audit.jsonl"],
             ["audit_write_failure", "appendFile to the audit path throws", "redacted error message", "stderr"],
             ["startup_banner", "Successful transport connect", "mode, baseUrl, sender lock state, rps, maxRetries, audit path", "stderr"],
             ["config_error", "loadConfig throws at boot", "validation message, exit code 1", "stderr"],
             ["preflight_result", "brevo_preflight invocation", "ready boolean, per-check pass/fail/warn with detail", "MCP tool result (not persisted)"],
         ]},

        # 8
        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "There is no graphical interface. The product is a headless stdio process whose only consumer is an AI agent, so the design surface is the tool contract: names, descriptions, argument schemas, and the wording of results and errors."},
        {"kind": "bullets", "items": [
            "Naming: every tool is prefixed brevo_ and named verb-first against the Brevo noun (brevo_send_test_email, brevo_get_import_status), so a client listing tools from several servers never collides and the read/write intent is legible from the name alone.",
            "Descriptions as the only affordance: the agent cannot read the source, so descriptions carry the policy. brevo_create_campaign states 'Always created as a DRAFT; it is never sent by this tool' and names the follow-up tools. brevo_send_campaign_now opens with 'IRREVERSIBLE' and states the preconditions. brevo_send_test_email is labelled 'Safe'.",
            "Argument schemas as guardrails: zod bounds every numeric range (test recipients 1-10, events limit 1-1000), validates every email, and expresses confirm as a literal type so a wrong or absent token fails at schema validation before any handler runs.",
            "Confirmation ergonomics: the tokens are distinct words (SEND, SCHEDULE) rather than a shared boolean, so a confirmation cannot be copied from one call into a more dangerous one.",
            "Error legibility: refusals explain the reason and the fix in one sentence — the sender-lock error names both addresses and states that mismatch breaks DKIM alignment; DryRunError names the variable to unset; BrevoApiError carries status, Brevo's own error code and the attempt count.",
            "Result shaping: writes return a plain-language sentence naming what changed ('Campaign 42 (\"...\") is sending from ...') rather than raw API JSON, so the agent's summary to the human is accurate by default. Reads return pretty-printed JSON.",
            "Preflight as an onboarding surface: brevo_preflight returns a pass/fail/warn checklist rather than raw payloads, giving the agent a single call that establishes whether work can proceed.",
        ]},

        # 9
        {"kind": "break"},
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"],
         "rows": [
             ["M1 — v1.0.0 shipped", f"All {len(TOOLS)} tools, client with retry/rate-limit/audit/redaction, 34 tests, README", "Musfiqur Tuhin", "Complete"],
             ["M2 — PRD baseline", "This document at version 0.1", "Musfiqur Tuhin", "2026-07-22"],
             ["M3 — CI gate", "npm run check enforced on every push to main in the monorepo", "Musfiqur Tuhin", "TBD — pending monorepo CI decision"],
             ["M4 — Audit log retention", "Rotation and off-host retention for audit.jsonl", "HaorGrix Operations", "TBD"],
             ["M5 — Coverage extension", "Tests for the tool handlers and sender-lock logic, not only the client and primitives", "Musfiqur Tuhin", "TBD"],
             ["M6 — Second programme onboarding", "Non-Podium sender lock and .env.example generalisation", "HaorGrix Operations", "TBD — awaiting a second email programme"],
         ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "para", "text": "Rollout is per-operator, not per-user: the server is installed locally and registered with claude mcp add pointing at dist/index.js. The safe adoption path is BREVO_DRY_RUN=true with BREVO_ENFORCE_SENDER set, exercising reads and confirming that writes are refused and audited, then disabling dry-run once brevo_preflight reports ready. There is no staged or percentage rollout and no feature flagging beyond the environment variables."},
        {"kind": "h2", "text": "9.3 Effort & Timeline"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"],
         "rows": [
             ["v1.0.0 implementation", "Musfiqur Tuhin", "Complete", "Brevo API key, Podium campaign requirements"],
             ["PRD authoring", "Musfiqur Tuhin", "Complete", "Shipped source"],
             ["CI gate wiring", "Musfiqur Tuhin", "0.5 day", "Monorepo CI runner"],
             ["Handler-level test coverage", "Musfiqur Tuhin", "1-2 days", "Mock MCP server harness"],
             ["Audit rotation and retention", "HaorGrix Operations", "0.5 day", "Decision on retention period and destination"],
             ["Key rotation runbook", "HaorGrix Operations", "0.5 day", "Brevo account admin access"],
         ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "npm run check green (typecheck plus 34 tests).",
            "npm run build produces dist/index.js and the client is registered against that path.",
            "BREVO_API_KEY present, xkeysib- prefixed, and not committed; .env ignored by git.",
            "BREVO_ENFORCE_SENDER set to the correct programme sender for this deployment, not the Podium default.",
            "brevo_preflight returns ready=true with the enforced sender active and credits non-zero.",
            "brevo_check_domain_auth confirms DKIM and DMARC for the sending domain.",
            "A dry-run pass completed and audit.jsonl shows the dry-run refusals.",
            "The audit log path is writable and its location is known to the operator.",
            "A named human is designated to author the confirm token for any live send.",
        ]},

        # 10
        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"],
         "rows": [
             ["Maintainer / sole engineer", "Musfiqur Tuhin", "Ad hoc; no dedicated allocation"],
             ["Campaign operator", "TBD — named operator per programme", "Per campaign"],
             ["Send approver", "TBD — named approver", "Per live send"],
             ["Brevo account admin", "HaorGrix", "As needed for key rotation and sender verification"],
         ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "No hosting cost. The server runs as a local child process on the operator's machine.",
            "No licensing cost. All dependencies are permissively licensed open source.",
            "Brevo plan cost is the real spend and is unchanged by this server; brevo_get_account and brevo_preflight surface remaining credits so a send is not attempted against an empty balance.",
            "The dominant cost risk is reputational rather than monetary: a mis-sent campaign damages domain reputation, which is why the guards exist.",
            "Ongoing engineering cost is maintenance only — SDK and Brevo API drift.",
        ]},

        # 11
        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "bullets", "items": [
            "Code ownership: Musfiqur Tuhin, HaorGrix/mcp-servers, Tooling/MCP/brevo-mcp.",
            "Credential ownership: HaorGrix Operations holds the Brevo API key; it lives only in a local .env.",
            "Runtime ownership: the operator whose machine spawns the process. There is no shared deployment to monitor.",
            "Incident evidence: audit.jsonl on the operator's machine is the authoritative record of mutations.",
        ]},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "bullets", "items": [
            "README.md covers setup, environment variables, client registration, the safety design and the known limits.",
            "First-line diagnosis is brevo_preflight; its checklist distinguishes a bad key, an unverified or inactive sender, exhausted credits and an active dry-run.",
            "Configuration errors are fatal at boot with a specific message naming the offending variable, so a misconfiguration cannot present as a mysterious runtime failure.",
            "There is no ticketing queue or on-call rotation; issues go to the maintainer directly.",
        ]},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "Track @modelcontextprotocol/sdk minor releases; the server pins ^1.12.0 and uses the high-level McpServer.tool API.",
            "Track Brevo API v3 changes, particularly the campaign statistics shape that brevo_campaign_report depends on.",
            "Any new write tool must be added with an audit path, a sender check where a send is implied, and a confirm gate where the action is irreversible.",
            "Deprecation path: unregister from the MCP client and revoke the API key in Brevo. No data migration is required because the server stores nothing but its own audit log.",
        ]},

        # 12
        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "table", "header": ["Area", "Consideration", "Owner or Status"],
         "rows": [
             ["Personal data", "Contact email addresses and engagement events flow through the tools. Nothing is persisted locally; the audit log records method, path and status only, never request bodies.", "HaorGrix — current design"],
             ["Consent and opt-out", "brevo_blacklist_contact provides a permanent suppression path. Consent capture happens upstream of this server and is not verified by it.", "HaorGrix Operations"],
             ["Anti-spam law (CAN-SPAM, GDPR, PECR)", "Unsubscribe handling, sender identification and lawful basis are properties of the campaign content and the list, not of this server. The server does not validate them.", "Open — campaign owner's responsibility"],
             ["Credential handling", "API key only via environment, format-validated at boot, redacted from all errors and audit details. Never logged.", "Implemented"],
             ["Data residency", "All contact data resides in Brevo. The only local artefact is audit.jsonl on the operator's machine.", "Implemented"],
             ["Third-party terms", "Use is subject to Brevo's terms and rate limits; the client paces itself at BREVO_RPS to stay within them.", "Accepted"],
             ["Audit retention", "No rotation, encryption or retention policy for audit.jsonl.", "Open — see M4"],
             ["Licensing", "No LICENSE file in the server folder; the monorepo is private and internal-use only.", "Open — TBD whether a licence is required"],
         ]},

        # 13
        {"kind": "break"},
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"],
         "rows": [
             ["Sender lock is optional; an operator who does not set BREVO_ENFORCE_SENDER gets no protection from the exact failure the server was built to prevent", "Medium", "High", "brevo_preflight raises an explicit warn when it is unset; the startup banner states 'no sender lock'. Consider making it mandatory in a future version."],
             ["Tests cover the client and primitives but not the tool handlers, so a regression in assertSenderAllowed or a confirm gate would not be caught", "Medium", "High", "M5 extends coverage to handlers; until then the guards are reviewed manually on change."],
             ["A live send is irreversible; a correct-looking confirm token from an agent that misread intent still sends", "Low", "High", "confirm is a literal token, the campaign is re-read and its sender re-checked before sending, and the action is audited. Ultimately mitigated by a human authoring the token."],
             ["Audit log is local, unrotated and unencrypted; it can be lost, deleted or grow unbounded", "Medium", "Medium", "M4 defines rotation and off-host retention. Content is deliberately minimal so loss exposes no personal data."],
             ["brevo_update_campaign has no sender check because it cannot change the sender; if a future edit adds sender fields the gap becomes real", "Low", "High", "Documented here; any schema change to that tool must add assertSenderAllowed."],
             ["realOpenRate is null whenever Brevo zeroes globalStats for list-based campaigns, which is the common case", "High", "Low", "Reported as null rather than an inflated figure; the limitation is stated in the README and in the tool description."],
             ["Brevo API v3 breaking change to campaign statistics or the senders payload", "Low", "Medium", "Types are narrow and optional-chained; failures surface as BrevoApiError or missing fields rather than silent wrong numbers."],
             ["No CI gate yet, so a broken build can reach main", "Medium", "Medium", "M3 wires npm run check into the monorepo pipeline."],
             ["No LICENSE file and no key-rotation runbook", "Low", "Low", "Tracked as open questions below."],
         ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"],
         "rows": [
             ["Should BREVO_ENFORCE_SENDER become mandatory rather than optional?", "Musfiqur Tuhin", "Open"],
             ["Who is the named approver authorised to supply confirm=\"SEND\"?", "HaorGrix Operations", "Open"],
             ["What is the retention period and destination for audit.jsonl?", "HaorGrix Operations", "Open"],
             ["Should the audit log also record read calls for completeness, or does the volume make it useless?", "Musfiqur Tuhin", "Open"],
             ["Is a transactional (SMTP send) tool group wanted, or does that widen the blast radius too far?", "Musfiqur Tuhin", "Open"],
             ["How is the Brevo API key rotated, and on what cadence?", "HaorGrix Operations", "Open"],
             ["Does the monorepo need a LICENSE file for internal-only servers?", "Musfiqur Tuhin", "Open"],
             ["Should the 200-page getAll ceiling be configurable, or is refusing to continue the right behaviour?", "Musfiqur Tuhin", "Open — current behaviour is deliberate"],
         ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"],
         "rows": [
             ["TBD — v1.0.0 development", "Campaigns are created as drafts only; brevo_create_campaign has no send option", "Separates authoring from the irreversible act, so a drafting mistake is recoverable", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Sending requires a literal confirm token (SEND / SCHEDULE) typed as a zod literal", "Fails closed at schema validation; distinct words prevent a confirmation being reused across actions", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Sender lock enforced in the tool layer, and re-checked against the campaign's actual sender at send time", "26 of 27 Podium campaigns went out from a gmail.com address that could not be DKIM-aligned", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Only mutations are audited; reads are not", "Reads are high volume and uninteresting; an audit log that is mostly GETs stops being read", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Dry-run refusals are still audited", "Blocked intent is evidence worth keeping", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Configuration is validated at boot and the process exits 1 on failure", "A misconfiguration should not surface as a mid-campaign tool error", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "realOpenRate is null when no MPP figure is available, instead of falling back to the raw open rate", "A real-looking number that silently equals the inflated one is worse than an absent one", "Musfiqur Tuhin"],
             ["TBD — v1.0.0 development", "Retry only 408, 429 and 5xx, with full jitter", "4xx will not improve on retry; jitter stops concurrent tools resynchronising into a burst", "Musfiqur Tuhin"],
             ["2026-07-22", "PRD baselined at version 0.1 from the shipped source", "Documentation must describe the actual state, not an intended one", "Musfiqur Tuhin"],
         ]},

        # 14
        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "bullets", "items": [
            "Brevo web console — full featured and the system of record, but requires a human session and offers no agent-callable surface. It also makes the DKIM-misalignment mistake easy, which is the gap this server closes.",
            "Direct Brevo API calls from an ad-hoc script or a generic HTTP tool — maximum capability, zero guards: no confirm gate, no sender lock, no audit, and the raw key in the agent's context.",
            "Community/third-party Brevo MCP servers — availability is unverified and none are known to implement a sender lock, a dry-run mode or an audit log, which are the reasons this one exists.",
            "Generic ESP integrations (Mailchimp, SendGrid MCP wrappers) — different vendor, and the same guard gap. The guard design here is intended to be portable to them.",
            "Conclusion: the differentiator is not API coverage, it is the refusal behaviour. Coverage is deliberately narrow (no transactional send, no deletes) to keep the blast radius small.",
        ]},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"],
         "rows": [
             ["MCP", "Model Context Protocol; the protocol by which an AI client discovers and calls tools exposed by a server."],
             ["stdio transport", "MCP over the child process's stdin/stdout. The only transport this server supports."],
             ["Confirm token", "A literal string argument (SEND or SCHEDULE) required by an irreversible tool; typed as a zod literal so a wrong value fails schema validation."],
             ["Sender lock", "BREVO_ENFORCE_SENDER. When set, every create/send/schedule path refuses any other From address."],
             ["Dry run", "BREVO_DRY_RUN. Every non-GET request throws DryRunError before reaching the network, and is still audited."],
             ["DKIM alignment", "The From domain matching the domain that cryptographically signed the message. Misalignment is the failure that put 26 of 27 Podium campaigns in spam."],
             ["DMARC", "The policy record that tells receivers what to do when SPF and DKIM alignment fail."],
             ["Apple MPP", "Apple Mail Privacy Protection; prefetches tracking pixels so a message registers as opened regardless of whether a human read it."],
             ["appleMppOpens", "Brevo's count of MPP-attributed opens, present only on globalStats and zeroed for list-based campaigns."],
             ["Token bucket", "The rate-limiting algorithm in ratelimit.ts: a burst up to BREVO_RPS, then refill at BREVO_RPS per second."],
             ["Full jitter", "Backoff randomised uniformly between zero and the exponential ceiling, so concurrent retries do not resynchronise."],
             ["Audit log", "audit.jsonl; one JSON object per mutating request with ts, method, path, status, durationMs, attempts and an optional redacted detail."],
             ["Redaction", "redact() in config.ts, replacing any xkeysib- token with a placeholder before a string reaches a log or an error."],
             ["processId", "The handle Brevo returns for an asynchronous contact import, polled via brevo_get_import_status."],
             ["Blacklist", "Brevo's permanent suppression flag on a contact; set by brevo_blacklist_contact."],
             ["Preflight", "brevo_preflight; a pass/fail/warn checklist run before campaign work rather than raw API output."],
         ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": f"Complete tool inventory as of v1.0.0 — {len(TOOLS)} tools, {READ_COUNT} read and {WRITE_COUNT} write. The full behavioural table appears in section 5.2.1; the classification is repeated here for reference."},
        {"kind": "table", "header": ["Class", "Tools"],
         "rows": [
             ["Read (13)", ", ".join(t[0] for t in TOOLS if t[1] == "Read")],
             ["Write (8)", ", ".join(t[0] for t in TOOLS if t[1] == "Write")],
         ]},
        {"kind": "bullets", "items": [
            "Environment variables: BREVO_API_KEY (required, xkeysib- prefix), BREVO_BASE_URL (default https://api.brevo.com/v3, trailing slash stripped), BREVO_ENFORCE_SENDER (email, lowercased), BREVO_DRY_RUN (boolean, default false), BREVO_TIMEOUT_MS (default 30000, 1000-120000), BREVO_MAX_RETRIES (default 3, 0-10), BREVO_RPS (default 8, 1-100), BREVO_AUDIT_LOG (default audit.jsonl).",
            "Boolean env accepts 1/true/yes/on and 0/false/no/off; anything else is a boot error.",
            "Test suite: 34 tests. src/tests/unit.test.ts covers config validation, redaction, the token bucket, backoff bounds, retryability and the isMutating rule. src/tests/client.test.ts covers success parsing, the api-key header, empty 204 bodies, 429 and 5xx retry behaviour, 401 non-retry, Brevo error code surfacing, key non-leakage, dry-run refusal, audit write/skip/dry-run-record, and getAll pagination termination.",
            "This is the only server in the monorepo with a test suite; the others have none.",
            "Registration: claude mcp add brevo -- node <repo>/Tooling/MCP/brevo-mcp/dist/index.js (run npm run build first).",
            "Known limits carried from the README: Brevo cannot see replies, and MPP inflation can only be corrected when Brevo supplies globalStats.",
        ]},
    ],
}
