"""PRD content module for the Google Analytics (GA4) MCP server."""

TOOL_ROWS = [
    ["ga_list_properties", "Read", "Admin API", "List GA4 accounts and properties visible to the service account"],
    ["ga_get_realtime_report", "Read", "Data API", "Realtime active-user report for a property"],
    ["ga_run_report", "Read", "Data API", "Generic report over caller-supplied dimensions, metrics and date range"],
    ["ga_get_metadata", "Read", "Data API", "List dimensions and metrics available on the property"],
    ["ga_get_top_conversion_paths", "Read", "Data API", "Preset report over conversion path dimensions"],
    ["ga_get_landing_page_performance", "Read", "Data API", "Preset landing-page metric set"],
    ["ga_get_user_acquisition", "Read", "Data API", "Preset acquisition channel/source-medium report"],
    ["ga_get_event_breakdown", "Read", "Data API", "Preset event-name breakdown with counts"],
    ["ga_list_custom_dimensions", "Read", "Admin API", "List custom dimensions defined on the property"],
    ["ga_list_custom_metrics", "Read", "Admin API", "List custom metrics defined on the property"],
    ["ga_list_conversion_events", "Read", "Admin API", "List configured conversion (key) events"],
    ["ga_list_data_streams", "Read", "Admin API", "List web/app data streams on the property"],
    ["ga_create_custom_dimension", "Write", "Admin API", "Create a custom dimension (parameter, scope, display name)"],
    ["ga_archive_custom_dimension", "Write", "Admin API", "Archive a custom dimension; GA4 has no delete"],
    ["ga_create_custom_metric", "Write", "Admin API", "Create a custom metric (parameter, measurement unit, scope)"],
    ["ga_archive_custom_metric", "Write", "Admin API", "Archive a custom metric; GA4 has no delete"],
    ["ga_create_conversion_event", "Write", "Admin API", "Mark an event name as a conversion/key event"],
    ["ga_delete_conversion_event", "Write", "Admin API", "Remove a conversion-event marking"],
]

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "Google Analytics (GA4) MCP Server",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Status", "Summary"], "rows": [
            ["0.1", "2026-07-22", "Musfiqur Tuhin", "Draft", "Initial PRD written from the shipped v1.0.0 source at Tooling/MCP/google-analytics-mcp/"],
        ]},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Sign-off"], "rows": [
            ["Document Owner", "Musfiqur Tuhin", "Authors and maintains this PRD", "Pending"],
            ["Engineering Owner", "Musfiqur Tuhin", "Maintains the server code and releases", "Pending"],
            ["Security Reviewer", "TBD — named reviewer for service-account key handling", "Approves credential storage and rotation", "Pending"],
            ["Primary Consumer", "HaorGrix SEO/growth agents", "Consumes the tools through MCP", "Pending"],
        ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Repo: HaorGrix/mcp-servers (private monorepo), branch main, folder Tooling/MCP/google-analytics-mcp/",
            "Server README.md — service-account setup, API enablement and GA property access steps",
            "Sibling server Tooling/MCP/google-search-console-mcp/ — same service-account auth pattern",
            "Google Analytics Data API v1 (@google-analytics/data ^6.1.0) reference",
            "Google Analytics Admin API v1 (@google-analytics/admin ^9.2.0) reference",
            "Model Context Protocol specification (SDK ^1.12.0)",
        ]},

        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "GA4 reporting and configuration live behind a web console and two separate Google APIs. Agents working on HaorGrix and client sites cannot read traffic data, verify conversion setup, or fix measurement configuration without a human opening the console and copying numbers out by hand. That makes analytics-driven work slow and the data in reports unverifiable."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": "google-analytics-mcp v1.0.0 is a Node/TypeScript ESM MCP server that speaks stdio and exposes 18 tools over the GA4 Data API (reporting) and Admin API (configuration). Twelve tools read; six write. Authentication is a single Google Cloud service-account JSON key referenced by GOOGLE_APPLICATION_CREDENTIALS, with a default property from GA4_PROPERTY_ID that every tool can override per call."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "The server is part of the HaorGrix MCP tooling set. It was built alongside google-search-console-mcp and reuses the same service-account authentication pattern, so one Google Cloud project and one key can cover both search and analytics telemetry."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "Analytics is the measurement half of the SEO workflow the agent fleet already runs. Pairing GA4 reads with Search Console reads lets an agent close the loop from query impression to on-site behaviour to conversion without leaving the tool surface."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Remove manual console work from routine traffic and conversion reporting",
            "Let agents audit and repair GA4 measurement configuration (custom dimensions, metrics, key events) directly",
            "Keep one credential and one property default shared across the analytics tooling",
            "Make reported numbers reproducible, because every figure comes from a named tool call with explicit parameters",
        ]},

        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "G1 — All 18 tools return a usable result against a live GA4 property with only GOOGLE_APPLICATION_CREDENTIALS and GA4_PROPERTY_ID configured, verified by 2026-08-15.",
            "G2 — Rotate the compromised service-account key in Google Cloud and re-issue it out of git, before any further deployment of this server.",
            "G3 — An agent can answer a standard traffic question (channel, landing page, event) in a single tool call without human console access.",
            "G4 — Add an automated test that exercises at least the read tools against a fixture property, target 2026-09-30 (none exist today).",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"], "rows": [
            ["Tools callable end-to-end", "Unverified — no test suite", "18 / 18", "Manual smoke run recorded in the repo"],
            ["Automated test coverage", "0%", "Read tools covered", "npm test once a runner is added"],
            ["Compromised key rotated", "No", "Yes", "Google Cloud IAM key list shows a new key ID and the old one deleted"],
            ["Manual GA4 console sessions per reporting task", "1 or more", "0", "Operator observation over a month of SEO work"],
            ["Data API quota exhaustion incidents", "Unknown, unmonitored", "0 per month", "RESOURCE_EXHAUSTED errors surfaced in tool output"],
        ]},
        {"kind": "h2", "text": "3.3 Non-Goals"},
        {"kind": "bullets", "items": [
            "No HTTP or SSE transport; stdio only",
            "No local caching, storage or warehousing of GA4 responses",
            "No Universal Analytics (GA3) support",
            "No Measurement Protocol event ingestion — the server reads and configures, it does not send hits",
            "No dashboarding or charting; output is text for an agent to interpret",
            "No multi-tenant credential brokering; one service account per running process",
        ]},

        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"], "rows": [
            ["Name", "SEO/analytics agent (LLM) running inside Claude Code"],
            ["Goal", "Answer traffic, acquisition and conversion questions, and correct GA4 measurement setup"],
            ["Interface", "MCP tool calls over stdio; tool names and descriptions are the only affordance"],
            ["Technical level", "High for API semantics, zero for GUI navigation"],
            ["Pain points", "Preset report tools cannot be reshaped; GA4 processing delay makes recent data look wrong; quota errors are opaque"],
            ["Success looks like", "A correct, parameterised answer in one call, with property and date range echoed back"],
        ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "Operator (Musfiqur Tuhin) — configures the service account, grants GA property access, rotates keys, reads raw tool output when debugging",
            "Client-facing reviewer — consumes agent-produced reports and needs the figures to be traceable to a tool call",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an agent, I want to list the properties my credential can see so I can confirm I am pointed at the right one.",
            "As an agent, I want a realtime active-user report so I can confirm a deployment is receiving traffic.",
            "As an agent, I want to run an arbitrary dimension/metric report so I am not limited to the preset shapes.",
            "As an agent, I want the property's metadata so I can pick valid dimension and metric names before querying.",
            "As an agent, I want landing-page, acquisition and event-breakdown presets so common questions take one call.",
            "As an agent, I want to list custom dimensions, custom metrics, conversion events and data streams so I can audit measurement setup.",
            "As an agent, I want to create and archive custom dimensions and metrics so I can fix a gap I just found.",
            "As an agent, I want to create and delete conversion events so key-event configuration matches the site's actual goals.",
            "As an operator, I want a clear error when the credential file or property ID is missing rather than a raw Google API stack trace.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"], "rows": [
            ["FR-1", "Expose 18 MCP tools over stdio using MCP SDK ^1.12.0 with zod-validated inputs", "Must", "All 18 tools appear in tools/list with schemas; invalid input is rejected before any API call"],
            ["FR-2", "Authenticate via a service-account JSON key at GOOGLE_APPLICATION_CREDENTIALS, resolved relative or absolute", "Must", "Server starts with a valid key; a missing key yields the explicit message defined in src/client.ts, not a crash"],
            ["FR-3", "Default the property from GA4_PROPERTY_ID and allow a per-call propertyId override on every property-scoped tool", "Must", "Omitting propertyId uses the env default; supplying it overrides; neither present returns a named error"],
            ["FR-4", "Property discovery — ga_list_properties", "Must", "Returns accounts and properties visible to the service account"],
            ["FR-5", "Realtime reporting — ga_get_realtime_report", "Must", "Returns current active users for the resolved property"],
            ["FR-6", "Generic reporting — ga_run_report over caller-supplied dimensions, metrics and date range", "Must", "Arbitrary valid GA4 dimension/metric combinations return rows; invalid names surface the API error text"],
            ["FR-7", "Metadata discovery — ga_get_metadata", "Must", "Returns the property's available dimensions and metrics"],
            ["FR-8", "Preset reports — ga_get_top_conversion_paths, ga_get_landing_page_performance, ga_get_user_acquisition, ga_get_event_breakdown", "Should", "Each returns its fixed metric/dimension set for the resolved property and date range"],
            ["FR-9", "Configuration reads — ga_list_custom_dimensions, ga_list_custom_metrics, ga_list_conversion_events, ga_list_data_streams", "Must", "Each returns the current Admin API configuration for the property"],
            ["FR-10", "Custom dimension writes — ga_create_custom_dimension, ga_archive_custom_dimension", "Must", "Create returns the new resource; archive succeeds and the dimension disappears from the active list. Delete is not offered because GA4 does not support it"],
            ["FR-11", "Custom metric writes — ga_create_custom_metric, ga_archive_custom_metric", "Must", "Create returns the new resource; archive removes it from the active list"],
            ["FR-12", "Conversion event writes — ga_create_conversion_event, ga_delete_conversion_event", "Must", "Create marks an event name as a key event; delete removes the marking"],
            ["FR-13", "Error legibility — configuration and API errors are returned as readable text on the tool result", "Must", "Missing credentials, missing property, permission denial and quota exhaustion each produce a distinguishable message"],
        ]},
        {"kind": "para", "text": "Complete tool inventory (18 tools, 12 read / 6 write):"},
        {"kind": "table", "header": ["Tool", "Class", "API", "Behaviour"], "rows": TOOL_ROWS},
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Reporting flow: ga_list_properties (confirm property) → ga_get_metadata (confirm valid field names) → ga_run_report or a preset tool → agent summarises rows.",
            "Measurement audit flow: ga_list_custom_dimensions + ga_list_custom_metrics + ga_list_conversion_events + ga_list_data_streams → agent compares against the site's tracking plan → ga_create_* / ga_archive_* to close gaps.",
            "Live check flow: ga_get_realtime_report immediately after a deploy to confirm hits are arriving, because standard reports lag 24–48 hours.",
        ]},

        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"], "rows": [
            ["Performance", "Tool latency is dominated by the Google API round trip; the server adds no caching layer and no retry/backoff. Typical Data API calls complete in under 3 seconds."],
            ["Scalability", "Single-process, single-credential, one concurrent stdio client. The binding constraint is the GA4 Data API quota (tokens per property per day, per hour, and concurrent-request limits), not server capacity. Heavy generic reports consume disproportionate token quota."],
            ["Availability", "Availability equals that of the Google Analytics Data and Admin APIs. The process is started on demand by the MCP client; there is no supervisor or health endpoint."],
            ["Security", "Service-account JSON key on local disk, path from GOOGLE_APPLICATION_CREDENTIALS. The key grants whatever GA role it was given — grant Viewer for read-only use and only elevate where write tools are required. Six write tools mutate live GA4 configuration with no confirmation prompt or dry-run."],
            ["Privacy / Compliance", "GA4 responses can contain user-level and geographic data governed by the property's own retention and consent settings. The server stores nothing and logs no response bodies, so retention obligations stay with GA4."],
            ["Accessibility", "N/A — no human-facing UI; operator-facing output is plain text on stdout/stderr."],
            ["Observability", "Errors surface in tool results and on stderr. There is no structured logging, no metrics, and no quota-usage counter."],
            ["Localization", "N/A — English-only tool descriptions and error strings. Report values carry whatever locale GA4 returns."],
        ]},

        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "para", "text": "Node >= 18, TypeScript, ESM. Source is 930 lines across three files: src/index.ts (431 lines, all 18 tool registrations), src/client.ts (456 lines, credential resolution, property resolution and both Google API clients) and src/types.ts (43 lines). Scripts: build (tsc), start (node dist/index.js), dev (tsx src/index.ts), typecheck (tsc --noEmit). There is no test script and no test framework."},
        {"kind": "bullets", "items": [
            "@google-analytics/data ^6.1.0 — reporting",
            "@google-analytics/admin ^9.2.0 — property and configuration management",
            "@modelcontextprotocol/sdk ^1.12.0 — stdio server transport",
            "zod ^3.23.8 — tool input schemas",
            "dotenv ^16.4.7 — loads the local .env",
            "dev: typescript ^5.7.2, tsx ^4.19.2, @types/node ^22.10.0",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "para", "text": "The server owns no persistent data model. Property IDs are numeric and passed without the properties/ prefix; the client adds it. Tool inputs are zod objects, typically an optional propertyId plus date range or dimension/metric arguments. Responses are the Google API payloads rendered as text content on the MCP tool result."},
        {"kind": "h2", "text": "7.3 Integrations"},
        {"kind": "table", "header": ["Dependency", "Owner", "Type", "Status"], "rows": [
            ["Google Analytics Data API v1", "Google", "External API (read)", "Live — must be enabled in the Cloud project"],
            ["Google Analytics Admin API v1", "Google", "External API (read/write)", "Live — must be enabled in the Cloud project"],
            ["Google Cloud service account", "HaorGrix", "Credential", "Live but compromised; rotation outstanding"],
            ["GA4 property access grant", "HaorGrix / client", "Permission", "Manual step per property, per README"],
            ["MCP client (Claude Code)", "Anthropic", "Transport host", "Live"],
            ["google-search-console-mcp", "HaorGrix", "Sibling server", "Live — shares the same service-account auth pattern"],
        ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "GA4 standard reports carry a processing delay, typically 24–48 hours; only ga_get_realtime_report reflects the current minute.",
            "GA4 applies sampling to large or high-cardinality queries and collapses high-cardinality dimension values into (other), so totals may not reconcile across reports.",
            "The Data API enforces per-property token quotas (per day, per hour, and concurrent requests). Broad generic reports can exhaust them; the server does not meter or back off.",
            "GA4 custom dimensions and custom metrics cannot be deleted — only archived. The tool surface reflects this: archive, never delete.",
            "Conversion (key) events can be deleted, which is why ga_delete_conversion_event exists while its dimension/metric counterparts do not.",
            "Four report tools are hardcoded metric/dimension presets rather than composable; ga_run_report is the escape hatch.",
            "Assumes the service account has been granted at least Viewer on the target property, and an editing role for the six write tools.",
            "Assumes a trusted local execution environment; stdio has no authentication of its own.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "table", "header": ["Event", "Trigger", "Properties", "Destination"], "rows": [
            ["Tool invocation", "Any of the 18 tools is called", "Tool name, arguments", "Not instrumented — no telemetry exists today"],
            ["Configuration error", "Missing credential file or unresolved property ID", "Error message text", "Tool result and stderr"],
            ["Google API error", "Data or Admin API returns a non-2xx", "API error message, including PERMISSION_DENIED and RESOURCE_EXHAUSTED", "Tool result"],
            ["Write operation", "Any create/archive/delete tool succeeds", "Resource name", "Tool result only; no audit log is kept locally"],
        ]},

        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "There is no GUI. The product surface is the tool list an LLM sees, so design work is naming, description quality and error legibility."},
        {"kind": "bullets", "items": [
            "Naming: every tool is prefixed ga_ then verb-first (list/get/run/create/archive/delete), so the read/write split is readable from the name alone.",
            "Descriptions are the agent's only affordance; each one states what the tool returns and that propertyId falls back to GA4_PROPERTY_ID.",
            "Archive-versus-delete is encoded in the tool name so an agent cannot request an operation GA4 does not support.",
            "Errors are written for a reader who can act: the missing-credential message names the environment variable and what it should point at; the missing-property message names both the argument and the env var.",
            "Guard ergonomics are currently weak — the six write tools mutate live property configuration with no confirmation argument and no dry-run mode. Adding an explicit confirm flag is a known design gap.",
            "Preset report tools trade flexibility for one-call answers; their fixed field sets are documented in the descriptions so an agent knows when to fall back to ga_run_report.",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"], "rows": [
            ["M0 — v1.0.0 shipped", "18 tools, stdio, service-account auth", "Musfiqur Tuhin", "Shipped"],
            ["M1 — Credential rotation", "Revoke the leaked key, issue a new one outside git, verify all tools", "Musfiqur Tuhin", "2026-07-25"],
            ["M2 — Test harness", "Smoke tests for the 12 read tools against a fixture property", "Musfiqur Tuhin", "2026-09-30"],
            ["M3 — Write guards", "Confirmation argument and dry-run on the 6 write tools", "Musfiqur Tuhin", "TBD — schedule after M2"],
            ["M4 — Report composability", "Fold the 4 preset tools into parameterised presets over ga_run_report", "Musfiqur Tuhin", "TBD"],
        ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "para", "text": "Internal only. The server is registered in the local MCP client config and rolled out by pulling the monorepo and running npm run build. There is no package publication, no staged rollout and no versioned release channel; main is the release."},
        {"kind": "h2", "text": "9.3 Effort & Timeline"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"], "rows": [
            ["Key rotation and re-verification", "Musfiqur Tuhin", "0.5 day", "Google Cloud IAM access"],
            ["Read-tool smoke tests", "Musfiqur Tuhin", "2 days", "Fixture GA4 property, test runner choice"],
            ["Write guards", "Musfiqur Tuhin", "1 day", "Agreement on the confirmation convention across MCP servers"],
            ["Preset consolidation", "Musfiqur Tuhin", "2 days", "M2 tests in place to catch regressions"],
        ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "Data API and Admin API enabled in the Cloud project",
            "Service-account key rotated and stored outside the repo",
            "Service account granted access on every target GA4 property",
            "GA4_PROPERTY_ID set to the intended default property",
            "npm run build and npm run typecheck clean",
            "credentials.json and .env confirmed ignored by git",
            "All 18 tools manually smoke-tested against a live property",
        ]},

        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"], "rows": [
            ["Document owner / maintainer", "Musfiqur Tuhin", "Ad hoc"],
            ["Engineering", "Musfiqur Tuhin", "Ad hoc, no dedicated allocation"],
            ["Security review", "TBD — named reviewer", "One-off for key rotation"],
            ["QA", "Unassigned — no test suite exists", "0"],
        ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "Google Analytics Data and Admin APIs are free; the cost is quota, not money.",
            "No hosting cost — the process runs locally under the MCP client.",
            "Main ongoing cost is maintenance: tracking breaking changes in @google-analytics/data and @google-analytics/admin major versions.",
            "Hidden cost of the untested single-credential design is incident time when a key or permission grant breaks.",
        ]},

        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "para", "text": "Owned by HaorGrix; day-to-day operator is Musfiqur Tuhin. There is no on-call rotation. Failures surface as failed tool calls inside an agent session and are handled in-session."},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "para", "text": "The server README is the setup guide: enable both APIs, create the service account and JSON key, grant the service-account email access in GA4 Property Access Management, then copy .env.example to .env and set GA4_PROPERTY_ID. Support is direct to the maintainer."},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "Dependency updates are manual; Google client library majors are the main breakage source.",
            "Service-account keys should be rotated on a fixed schedule once the current compromised key is replaced.",
            "No deprecation path is defined; if GA4 replaces the Data API, this server is rewritten rather than migrated.",
            "Development artefacts left in the folder (audit.ts, test-ga.ts, audit_results.json, deep_audit_results.json) should be removed or moved out of the shipped tree.",
        ]},

        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "table", "header": ["Area", "Consideration", "Owner / Status"], "rows": [
            ["Credential compromise", "The service-account credentials.json was committed to git history and purged on 2026-07-22. The key must be treated as compromised until rotated in Google Cloud.", "Musfiqur Tuhin — open, blocking"],
            ["Data residency", "No GA4 data is persisted by the server; it stays in Google's systems", "Closed"],
            ["Personal data", "GA4 responses may include geographic, device and behavioural data subject to the property's consent configuration", "Property owner"],
            ["Client data access", "One credential may reach multiple client properties; access grants must be revoked when an engagement ends", "Musfiqur Tuhin — ongoing"],
            ["Google API Terms of Service", "Use of the Data and Admin APIs is bound by Google's terms and quota policy", "Accepted"],
            ["Write authority", "Six tools mutate client analytics configuration; authority to do so must be established per client before granting an editing role", "TBD — no written policy"],
            ["Licensing", "Internal, unlicensed, private monorepo; dependencies are permissively licensed", "Closed"],
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"], "rows": [
            ["Leaked service-account key — credentials.json was committed to git history and purged 2026-07-22; the key is compromised and anyone with a copy of the old history retains access to the granted GA4 properties", "High", "Critical", "Rotate the key in Google Cloud, delete the old key ID, audit GA4 access logs, keep credentials.json in .gitignore permanently"],
            ["No automated tests — nothing verifies the 18 tools after a dependency bump", "High", "High", "Add read-tool smoke tests (M2); run typecheck on every change until then"],
            ["Write tools have no confirmation or dry-run and mutate live client configuration", "Medium", "High", "Grant Viewer-only by default; add a confirm argument (M3)"],
            ["All tool registrations sit in one 431-line index.ts with client logic in a 456-line client.ts, limiting maintainability", "High", "Medium", "Split registrations into a tools/ directory as the surface grows"],
            ["Four report tools are hardcoded presets, so an unanticipated question needs ga_run_report and knowledge of valid field names", "Medium", "Medium", "Keep ga_get_metadata prominent; consolidate presets (M4)"],
            ["Data API quota exhaustion from broad reports", "Medium", "Medium", "Constrain date ranges and dimension counts; surface RESOURCE_EXHAUSTED clearly; add backoff"],
            ["GA4 sampling and (other) cardinality collapse produce figures that do not reconcile and may be reported as fact", "Medium", "Medium", "Note sampling in tool descriptions; cross-check totals against a second report shape"],
            ["Google client library major-version breakage", "Medium", "Medium", "Pin ranges, review changelogs before upgrading, rely on typecheck plus M2 tests"],
            ["Single credential shared with google-search-console-mcp — one compromise affects both surfaces", "Medium", "High", "Consider separate service accounts per API surface"],
        ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"], "rows": [
            ["Rotate the compromised service-account key in Google Cloud — the credentials.json committed to git history was purged on 2026-07-22 but the key itself is still valid and must be revoked and re-issued", "Musfiqur Tuhin", "Open — blocking, highest priority"],
            ["Was the private repo history ever cloned or exposed to a third party before the purge?", "Musfiqur Tuhin", "Open — determines whether GA4 access log review is required"],
            ["Should read and write live in one server, or should the six Admin write tools split into a separate, separately credentialed server?", "Musfiqur Tuhin", "Open"],
            ["What confirmation convention should write tools use across all HaorGrix MCP servers?", "Musfiqur Tuhin", "Open"],
            ["Which test runner for M2, and which GA4 property serves as the fixture?", "Musfiqur Tuhin", "Open"],
            ["Should the four preset report tools be kept, or replaced by documented ga_run_report recipes?", "Musfiqur Tuhin", "Open"],
            ["Who signs off on write access to client-owned GA4 properties?", "TBD — client engagement owner", "Open"],
        ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"], "rows": [
            ["TBD — v1.0.0 build date", "Use a service-account JSON key rather than OAuth user flow", "Headless server with no interactive consent step; matches google-search-console-mcp", "Musfiqur Tuhin"],
            ["TBD — v1.0.0 build date", "stdio transport only", "Local agent execution; no remote surface wanted", "Musfiqur Tuhin"],
            ["TBD — v1.0.0 build date", "Expose archive rather than delete for custom dimensions and metrics", "GA4 does not support deleting them", "Musfiqur Tuhin"],
            ["TBD — v1.0.0 build date", "Ship both preset report tools and a generic ga_run_report", "Presets answer common questions in one call; the generic tool prevents dead ends", "Musfiqur Tuhin"],
            ["2026-07-22", "Purge credentials.json from git history and treat the key as compromised", "Secret was committed; purge alone does not invalidate the key", "Musfiqur Tuhin"],
        ]},

        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "para", "text": "Public GA4 MCP servers exist, but they generally cover the Data API only and require the operator to trust third-party code with a Google credential. This server is kept in-house because it also covers Admin API writes, shares the credential pattern with google-search-console-mcp, and can be changed to match HaorGrix workflows without waiting on an upstream maintainer."},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"], "rows": [
            ["GA4", "Google Analytics 4, the event-based analytics property model that replaced Universal Analytics"],
            ["Data API", "Google Analytics Data API v1 — reporting queries against a GA4 property"],
            ["Admin API", "Google Analytics Admin API v1 — property, stream and measurement configuration"],
            ["Property ID", "Numeric GA4 property identifier; the API path prefixes it with properties/"],
            ["Custom dimension / metric", "A property-scoped field derived from an event parameter or user property; can be archived but never deleted"],
            ["Conversion (key) event", "An event name marked as a business outcome in GA4"],
            ["Data stream", "A web or app source feeding events into a GA4 property"],
            ["Sampling", "GA4 answering a large query from a subset of sessions, producing approximate figures"],
            ["Cardinality limit", "GA4 collapsing excess distinct dimension values into an (other) row"],
            ["Quota token", "The unit GA4 charges Data API requests against, capped per property per hour and per day"],
            ["MCP", "Model Context Protocol — the tool interface between an LLM client and this server"],
            ["stdio transport", "MCP over the process's standard input and output"],
        ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": "Full tool inventory by exact name. Read tools (12, no side effects): ga_list_properties, ga_get_realtime_report, ga_run_report, ga_get_metadata, ga_get_top_conversion_paths, ga_get_landing_page_performance, ga_get_user_acquisition, ga_get_event_breakdown, ga_list_custom_dimensions, ga_list_custom_metrics, ga_list_conversion_events, ga_list_data_streams. Write tools (6, mutate live GA4 configuration): ga_create_custom_dimension, ga_archive_custom_dimension, ga_create_custom_metric, ga_archive_custom_metric, ga_create_conversion_event, ga_delete_conversion_event."},
        {"kind": "bullets", "items": [
            "Environment variables: GOOGLE_APPLICATION_CREDENTIALS (path to the service-account JSON key, relative to the server directory or absolute), GA4_PROPERTY_ID (numeric default property, without the properties/ prefix)",
            "npm scripts: build (tsc), start (node dist/index.js), dev (tsx src/index.ts), typecheck (tsc --noEmit). No test script.",
            "Source layout: src/index.ts (431 lines), src/client.ts (456 lines), src/types.ts (43 lines) — 930 lines total, no tools/ subdirectory",
            "Non-shipping files present in the folder: audit.ts, test-ga.ts, audit_results.json, deep_audit_results.json, credentials.example.json",
        ]},
        {"kind": "meta", "text": "Scope: this PRD documents google-analytics-mcp v1.0.0 as committed on 2026-07-22. It records the code as it exists, including the absence of tests and write-operation guards."},
    ],
}
