"""PRD content module: Google Search Console MCP server."""

from __future__ import annotations

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "Google Search Console MCP Server",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        # 1
        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Status", "Summary of Change"], "rows": [
            ["0.1", "2026-07-22", "Musfiqur Tuhin", "Draft", "Initial PRD written from the shipped source at Tooling/MCP/google-search-console-mcp (v1.0.0, 10 tools, ~588 LOC)."],
        ]},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Sign-off"], "rows": [
            ["Document Owner", "Musfiqur Tuhin", "Authors and maintains this PRD", "Pending"],
            ["Engineering Owner", "Musfiqur Tuhin", "Server code, releases, credential hygiene", "Pending"],
            ["Product Owner", "HaorGrix", "Prioritises tool surface against SEO workflow needs", "Pending"],
            ["SEO Consumer", "TBD — named owner of the SEO Growth Engine workstream", "Defines the reporting and indexation use cases", "Pending"],
            ["Security Reviewer", "TBD — named reviewer for service-account key rotation", "Approves credential handling and write-tool guards", "Pending"],
        ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Repository: HaorGrix/mcp-servers (private monorepo), branch main, folder google-search-console-mcp/.",
            "Source of record: src/index.ts (tool registration and dispatch, 337 lines) and src/client.ts (GSC API wrapper, 251 lines).",
            "Configuration: .env.example (added 2026-07-22) and credentials.example.json.",
            "Google Search Console API v1 (searchconsole.googleapis.com) reference documentation.",
            "Google Indexing API v3 reference documentation.",
            "Model Context Protocol specification, stdio transport.",
            "Sibling PRDs in this set for the Brevo, cPanel, GA4, WordPress and Meta Ads MCP servers.",
        ]},

        # 2
        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "Search Console data is the only first-party record of how HaorGrix properties and client sites actually perform in Google Search, but reaching it means either the web UI (manual, unexportable at scale, capped rows) or bespoke scripts against the API. Agent-driven SEO work — CTR triage, position-change analysis, indexation checks, sitemap submission — stalls because the agent cannot read or act on that data itself. The evidence of the gap is already in the repository: six loose one-off TypeScript scripts sit in the project root, each written to answer a single question once."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": "A Node/TypeScript MCP server that exposes the Search Console and Indexing APIs as 10 tools over stdio: seven read tools and three write tools. Authentication is a Google service account supplied through GOOGLE_APPLICATION_CREDENTIALS; the default property comes from GSC_SITE_URL. Two of the read tools are derived rather than pass-through — get_ctr_rescue_candidates and get_position_changes compute an answer the API does not return directly, which is where most of the server's value sits."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "The server was built in July 2026 alongside the SEO Growth Engine workstream and is registered locally in the Claude configuration together with the GA4 MCP server. It is version 1.0.0 and functional, but it carries the marks of fast delivery: no test suite, no README, hand-written JSON schemas instead of zod, and the oldest MCP SDK pin in the monorepo."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "Search Console is the entry point of the SEO data chain — impressions and positions here explain the sessions GA4 reports and the pages the WordPress MCP server edits. Making it agent-readable is what lets an agent close the loop from diagnosis to fix without a human copying numbers between tabs."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Remove manual GSC export work from recurring SEO reporting.",
            "Let an agent identify CTR and ranking regressions without a bespoke script per question.",
            "Give agents a supervised path to submit sitemaps and request indexing, within Google's quota.",
            "Retire the six root-level one-off scripts by folding their logic into supported tools.",
        ]},

        # 3
        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "G1 — By 2026-08-15, rotate the compromised service-account key and confirm the old key is revoked in Google Cloud IAM.",
            "G2 — By 2026-08-31, namespace all 10 tools with a gsc_ prefix so the server can be mounted alongside the other five monorepo servers without name collisions.",
            "G3 — By 2026-09-15, delete all six root-level one-off scripts, with their behaviour covered by server tools.",
            "G4 — By 2026-09-30, raise the MCP SDK pin from ^1.0.1 to the monorepo baseline and replace hand-written JSON schemas with zod-derived schemas.",
            "G5 — By 2026-09-30, ship a smoke-test suite that exercises every read tool against a live property in a dry-run mode.",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"], "rows": [
            ["Tools callable without error against a live property", "TBD — never measured", "10 of 10", "Manual smoke run, then automated suite once G5 lands"],
            ["Namespaced tool names", "0 of 10", "10 of 10", "Grep of src/index.ts tool registration"],
            ["Root-level one-off scripts", "6", "0", "Directory listing of the server folder"],
            ["MCP SDK version", "^1.0.1 (oldest in monorepo)", "Monorepo baseline (>= 1.12.0)", "package.json review"],
            ["Automated test coverage", "0 tests", "Smoke coverage of all 7 read tools", "Test runner output"],
            ["Live service-account keys in git history", "1 (purged 2026-07-22, not yet rotated)", "0 valid, key rotated", "Google Cloud IAM key listing"],
            ["Indexing API daily quota consumed", "TBD — unmeasured", "Under 200 requests/day", "Google Cloud API quota dashboard"],
        ]},
        {"kind": "h2", "text": "3.3 Non-Goals"},
        {"kind": "bullets", "items": [
            "No HTTP or SSE transport. stdio only.",
            "No human-facing GUI, dashboard or report renderer.",
            "No multi-tenant credential store; one service account per process.",
            "No caching or local persistence of GSC responses.",
            "No Bing, Yandex or other search-engine webmaster integrations.",
            "No rank tracking beyond what GSC itself reports.",
            "No write access to site content — that belongs to the WordPress MCP server.",
        ]},

        # 4
        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"], "rows": [
            ["Name", "The SEO agent — an MCP-capable Claude session running SEO analysis"],
            ["Role", "Automated analyst and executor inside a developer's terminal session"],
            ["Goals", "Answer performance questions from real data; identify CTR and position regressions; check and fix indexation"],
            ["Frustrations", "Tool descriptions are its only affordance; unnamespaced tool names collide with sibling servers; no schema validation means malformed arguments surface as raw Google API errors"],
            ["Technical proficiency", "High for structured JSON, zero tolerance for ambiguous parameter semantics"],
            ["Access pattern", "stdio subprocess, one process per session, credentials from the operator's environment"],
        ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "The operator (Musfiqur Tuhin or a HaorGrix engineer) who installs the server, holds the service-account key, grants it Search Console access, and reads stderr when a call fails.",
            "The SEO consultant who receives the agent's findings as prose and never touches the server directly.",
            "The maintainer who will upgrade the SDK, add namespacing and tests, and who needs the tool surface documented here to avoid regressions.",
        ]},

        {"kind": "break"},
        # 5
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an agent, I want to list the properties the service account can see, so that I know which site URLs are valid arguments.",
            "As an agent, I want clicks, impressions, CTR and average position by query, page, country, device or date, so that I can quantify performance.",
            "As an agent, I want to filter and aggregate search analytics, so that I can answer a narrow question without pulling the whole dataset.",
            "As an agent, I want to inspect a single URL, so that I can report its indexing status, last crawl, rich-result state and mobile usability.",
            "As an agent, I want the queries with high impressions and near-zero CTR, so that I can propose title and meta rewrites where the upside is largest.",
            "As an agent, I want two date ranges compared, so that I can name the specific queries that gained or lost position.",
            "As an agent, I want the sitemaps registered for a property and their processing status, so that I can tell whether submission actually worked.",
            "As an agent, I want an indexation summary, so that I can see coverage without opening the GSC UI.",
            "As an operator, I want to submit or delete a sitemap through the agent, so that I do not have to open the console.",
            "As an operator, I want to request indexing for a URL, so that a new or updated page is crawled sooner — knowing the daily quota is roughly 200 requests.",
            "As a maintainer, I want every tool prefixed and schema-validated, so that mounting six servers in one session does not produce ambiguous dispatch.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"], "rows": [
            ["FR-1", "Property discovery: list every Search Console property the service account can access.", "Must", "list_sites returns each property with its permission level; an unauthorised account returns a legible error, not a stack trace."],
            ["FR-2", "Search analytics retrieval with dimensions, date range, filters and aggregation.", "Must", "get_search_analytics returns clicks, impressions, CTR and average position for the requested dimensions, honours dimension filters and aggregation type, and returns up to 25,000 rows per call."],
            ["FR-3", "URL inspection returning indexing status, last crawl, rich-result state and mobile usability.", "Must", "inspect_url returns the Google index verdict and the coverage state for any URL inside the property."],
            ["FR-4", "Indexation status summary for the property.", "Must", "get_indexing_status returns a coverage summary derived from the API without requiring the caller to construct a query."],
            ["FR-5", "Derived CTR rescue analysis: surface high-impression, near-zero-CTR queries.", "Must", "get_ctr_rescue_candidates returns queries ranked by lost-click opportunity, with the impression and CTR thresholds visible in the output."],
            ["FR-6", "Derived position-change analysis across two date ranges.", "Must", "get_position_changes compares two ranges and returns gains and losses per query with before, after and delta."],
            ["FR-7", "Sitemap listing for a property.", "Must", "list_sitemaps returns each submitted sitemap with its last-downloaded time and processing/warning/error state."],
            ["FR-8", "Sitemap submission and deletion.", "Should", "submit_sitemap registers a feed URL and delete_sitemap removes it; both confirm the mutation in the response and both are documented as write operations."],
            ["FR-9", "Indexing API URL submission.", "Should", "submit_url_for_indexing sends a URL_UPDATED notification; the tool description states the Owner-permission requirement and the ~200 requests/day cap."],
            ["FR-10", "Configuration by environment: GOOGLE_APPLICATION_CREDENTIALS and GSC_SITE_URL, loaded via dotenv.", "Must", "The server starts when both are set and fails at startup with a named-variable message when either is missing."],
            ["FR-11", "stdio transport with tool discovery.", "Must", "tools/list returns all 10 tools with names, descriptions and input schemas."],
            ["FR-12", "Namespace every tool name with a gsc_ prefix.", "Should", "All 10 registered names carry the prefix; documented as NOT IMPLEMENTED at v1.0.0."],
            ["FR-13", "Schema validation of tool arguments before the Google call.", "Should", "Invalid arguments are rejected with a field-level message; documented as NOT IMPLEMENTED — v1.0.0 uses hand-written JSON schemas with no runtime validation."],
            ["FR-14", "Confirmation semantics for destructive write tools.", "Could", "delete_sitemap and submit_url_for_indexing require an explicit confirm argument; documented as NOT IMPLEMENTED."],
        ]},
        {"kind": "para", "text": "Complete tool inventory — 10 tools, 7 read and 3 write. Names are given exactly as registered in src/index.ts, without any namespace prefix."},
        {"kind": "table", "header": ["Tool name", "Class", "Google API", "Purpose"], "rows": [
            ["list_sites", "Read", "Search Console v1 sites.list", "Lists every property the service account can access, with permission level."],
            ["get_search_analytics", "Read", "Search Console v1 searchanalytics.query", "Clicks, impressions, CTR and average position by dimension, with filters, aggregation and up to 25,000 rows."],
            ["inspect_url", "Read", "Search Console v1 urlInspection.index.inspect", "Indexing status, last crawl, rich-result state and mobile usability for one URL."],
            ["list_sitemaps", "Read", "Search Console v1 sitemaps.list", "Registered sitemaps with processing, warning and error counts."],
            ["get_indexing_status", "Read", "Search Console v1 (derived from inspection/coverage data)", "Property-level indexation summary."],
            ["get_ctr_rescue_candidates", "Read (derived)", "Search Console v1 searchanalytics.query", "High-impression, near-zero-CTR queries ranked as rewrite opportunities."],
            ["get_position_changes", "Read (derived)", "Search Console v1 searchanalytics.query", "Compares two date ranges and reports per-query position gains and losses."],
            ["submit_sitemap", "Write", "Search Console v1 sitemaps.submit", "Registers a sitemap feed URL for the property."],
            ["delete_sitemap", "Write (destructive)", "Search Console v1 sitemaps.delete", "Removes a registered sitemap from the property."],
            ["submit_url_for_indexing", "Write (quota-bound)", "Indexing API v3 urlNotifications.publish", "Requests crawl of a URL; needs Owner permission and is capped near 200 requests/day."]],
        },
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Startup: operator launches the server as a stdio subprocess -> dotenv loads GOOGLE_APPLICATION_CREDENTIALS and GSC_SITE_URL -> googleapis builds a service-account JWT client -> tools/list advertises 10 tools.",
            "Performance question: agent calls list_sites to confirm the property -> get_search_analytics with dimensions and a date range -> summarises to the operator in prose.",
            "CTR triage: agent calls get_ctr_rescue_candidates -> picks the highest-impression offenders -> optionally calls inspect_url per page to confirm the page is indexed before proposing a title rewrite.",
            "Regression hunt: agent calls get_position_changes with a current and a comparison range -> reports losses -> hands the affected URLs to a content workflow.",
            "Sitemap maintenance: list_sitemaps -> submit_sitemap for a missing feed -> list_sitemaps again to confirm the submission was accepted.",
            "Indexing request: agent calls submit_url_for_indexing -> Google accepts or rejects on permission/quota grounds -> the agent reports the outcome. There is no client-side quota counter, so repeated calls can exhaust the daily cap silently.",
        ]},

        # 6
        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"], "rows": [
            ["Performance", "A single-dimension search analytics call over a 28-day range should return within a few seconds. Latency is dominated by the Google API; the server adds only JSON shaping. Derived tools issue more than one query and are correspondingly slower."],
            ["Scalability", "One process per agent session, single-tenant, single service account. Row ceiling is 25,000 per search analytics call — larger pulls require the caller to page by date. No connection pooling or queueing exists or is needed."],
            ["Availability", "Availability equals the Google Search Console API's. The server has no retry, no exponential backoff and no circuit breaker; a transient 5xx surfaces as a failed tool call."],
            ["Security", "Credentials come only from environment variables and a service-account key file. The key file must never be committed — this was violated once and the key must be treated as compromised until rotated. Write tools have no confirmation guard, and delete_sitemap is irreversible from the server's side."],
            ["Privacy / Compliance", "GSC search analytics returns aggregate and anonymised query data, not personal data. Query strings can still contain user-typed personal information, so responses must not be logged to shared destinations."],
            ["Accessibility", "N/A — no human-facing UI. Operator-facing output is plain text on stderr and structured JSON to the agent."],
            ["Observability", "Console/stderr logging only. No structured logs, no metrics, no per-tool timing, no quota counter for the Indexing API."],
            ["Localization", "N/A — no human-facing UI. Tool descriptions and errors are English only; GSC country and search-type dimensions are passed through untouched."],
            ["Data freshness", "Search Console data carries a 2-3 day reporting lag and 16 months of retention. No tool can return newer or older data than that, and the constraint must be stated in every report derived from it."],
        ]},

        # 7
        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "bullets", "items": [
            "Node.js with TypeScript, compiled by tsc to dist/ (target ES2022, module Node16, strict mode). The package declares no type field, so output is CommonJS.",
            "Roughly 588 lines across two files: src/index.ts (337) registers and dispatches the 10 tools; src/client.ts (251) wraps googleapis and holds the derived-analysis logic.",
            "@modelcontextprotocol/sdk ^1.0.1 — the oldest pin in the monorepo. Four sibling servers are on 1.12.0 and the Meta Ads server is on 1.29.0.",
            "googleapis ^144.0.0 for both the Search Console v1 and Indexing v3 clients; dotenv ^16.4.5 for configuration.",
            "No zod. Input schemas are hand-written JSON objects and are advertised to the agent but not enforced at runtime.",
            "Transport: stdio only.",
            "Scripts: build (tsc), start (node dist/index.js), dev (tsc --watch). dev only recompiles — it does not start the server, which is a papercut for anyone expecting a watch-and-run loop.",
            "Six one-off scripts sit in the repository root outside src/: run_ctr.ts, run_sitemap.ts, submit_sitemap.ts, run_gsc_analytics.ts, hg_pushall.ts and test-gsc.ts. They duplicate tool logic and are not compiled by tsconfig, which includes only src/**/*.",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "para", "text": "The server holds no database and no local state. It is a translation layer: MCP tool call in, Google API request out, JSON text content back. The domain objects are Google's — property (site URL, either a URL-prefix property or an sc-domain: property), search analytics row (keys plus clicks, impressions, ctr, position), URL inspection result, and sitemap entry. The two derived tools construct their outputs in memory from one or more searchanalytics.query calls and return a shape that has no direct API equivalent."},
        {"kind": "h2", "text": "7.3 Integrations"},
        {"kind": "table", "header": ["Dependency", "Owner", "Type", "Status"], "rows": [
            ["Google Search Console API v1", "Google", "External REST API", "Live"],
            ["Google Indexing API v3", "Google", "External REST API", "Live — requires Owner permission on the property, ~200 requests/day"],
            ["Google Cloud service account", "HaorGrix", "Credential", "Live — key compromised via git history, rotation pending"],
            ["@modelcontextprotocol/sdk ^1.0.1", "Anthropic", "npm dependency", "Outdated relative to the monorepo baseline"],
            ["googleapis ^144.0.0", "Google", "npm dependency", "Current"],
            ["dotenv ^16.4.5", "Community", "npm dependency", "Current"],
            ["MCP host (Claude Code / Claude Desktop)", "Anthropic", "Runtime host", "Live — registered locally in claude.json alongside the GA4 server"],
            ["HaorGrix/mcp-servers monorepo", "HaorGrix", "Source repository", "Private, branch main"],
        ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "Search Console reports with a 2-3 day lag; today's and yesterday's data are not available.",
            "Search Console retains 16 months of data; no tool can answer a question older than that.",
            "searchanalytics.query returns at most 25,000 rows per request.",
            "Google applies anonymisation to low-volume queries, so query-level totals never sum to property totals.",
            "The Indexing API requires Owner permission on the property and is capped at roughly 200 requests/day; exceeding it fails the call.",
            "The service account must be explicitly granted access to each property in Search Console — API enablement alone is not enough.",
            "Assumes a single property per process via GSC_SITE_URL, with per-call overrides where a tool accepts a site argument.",
            "Assumes the operator's machine can reach googleapis.com; no proxy configuration is supported.",
            "Assumes trusted local execution — the agent is not treated as an untrusted caller, so write tools are unguarded.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "table", "header": ["Event", "Trigger", "Properties", "Destination"], "rows": [
            ["Server start", "Process launch and transport connect", "Server name, version", "stderr"],
            ["Tool invocation", "Any tools/call", "Tool name, arguments", "Not currently emitted — proposed"],
            ["Google API error", "Non-2xx from googleapis", "Tool name, HTTP status, Google error message", "stderr, surfaced to the agent as text"],
            ["Indexing quota consumption", "submit_url_for_indexing call", "URL, running daily count", "Not currently tracked — proposed, needed to stay under the ~200/day cap"],
            ["Write-tool audit trail", "submit_sitemap, delete_sitemap, submit_url_for_indexing", "Tool, target, timestamp, outcome", "Not currently emitted — proposed"],
        ]},

        # 8
        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "There is no graphical interface. The consumer is an AI agent over stdio, and the operator sees only stderr. The design surface is therefore the tool contract itself, and it has three parts."},
        {"kind": "para", "text": "Tool naming. The current names are bare verbs and nouns — list_sites, inspect_url, get_position_changes — with no namespace. Every other server in the monorepo prefixes its tools (brevo_, cp_, ga_, wp_). When several servers are mounted in one session, an unprefixed list_sites or get_indexing_status is a live collision risk and gives the agent no signal about which system it is addressing. Renaming to gsc_* is the single largest UX fix available."},
        {"kind": "para", "text": "Descriptions as the only affordance. The agent cannot read the source, so a tool description is the entire user manual. Descriptions must state the date-range semantics, the 25,000-row ceiling, the 2-3 day lag, and for submit_url_for_indexing both the Owner-permission requirement and the daily quota. Anything omitted from a description is, in practice, invisible."},
        {"kind": "para", "text": "Error legibility and guard ergonomics. Because arguments are not validated, a malformed date or an unknown dimension reaches Google and returns as a raw API error the agent must interpret. Errors should be rewritten to name the offending parameter. Guards are equally thin: delete_sitemap removes a registered feed and submit_url_for_indexing spends finite quota, and neither asks for confirmation. A confirm flag on both, plus a dry-run mode on the derived analytics tools, would make the write surface safe to expose to an autonomous agent."},

        {"kind": "break"},
        # 9
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"], "rows": [
            ["M0 — Shipped", "v1.0.0: 10 tools, stdio, service-account auth, in local use", "Musfiqur Tuhin", "Delivered July 2026"],
            ["M1 — Credential remediation", "Rotate the service-account key, confirm the purged key is revoked, verify .gitignore covers credentials.json and .env", "Musfiqur Tuhin", "2026-08-15"],
            ["M2 — Namespacing", "Rename all 10 tools to gsc_*, update the local MCP registration and any agent prompts", "Musfiqur Tuhin", "2026-08-31"],
            ["M3 — Script consolidation", "Delete the six root-level scripts once their behaviour is covered by tools", "Musfiqur Tuhin", "2026-09-15"],
            ["M4 — Dependency and validation", "SDK upgrade to monorepo baseline, zod schemas, error-message rewriting", "TBD — assigned engineer", "2026-09-30"],
            ["M5 — Tests and docs", "Read-tool smoke suite, README, write-tool confirmation guards", "TBD — assigned engineer", "2026-09-30"],
        ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "para", "text": "Internal only. Distribution is a git pull plus npm install and npm run build, then registration in the host's MCP config. There are no release channels, no versioned artefact and no published package. M2 is a breaking change to the tool names: any saved agent prompt or script referencing a bare name must be updated in the same change, and the rollback path is reverting the commit and rebuilding."},
        {"kind": "h2", "text": "9.3 Effort & Timeline"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"], "rows": [
            ["Key rotation and history verification", "Musfiqur Tuhin", "0.5 day", "Google Cloud IAM access"],
            ["Tool namespacing", "Musfiqur Tuhin", "0.5 day", "Inventory of every caller of the current names"],
            ["Retiring the six root scripts", "Musfiqur Tuhin", "1 day", "Confirming tool coverage of each script's behaviour"],
            ["MCP SDK upgrade to baseline", "TBD — assigned engineer", "1 day", "Sibling servers' upgrade path as reference"],
            ["zod schemas and error rewriting", "TBD — assigned engineer", "1.5 days", "SDK upgrade"],
            ["Read-tool smoke suite", "TBD — assigned engineer", "1.5 days", "A test property and a rotated key"],
            ["Write-tool confirmation guards", "TBD — assigned engineer", "0.5 day", "Agreement on the confirm-flag convention across the monorepo"],
            ["README and operator runbook", "Musfiqur Tuhin", "0.5 day", "This PRD"],
        ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "Service-account key rotated and the compromised key revoked.",
            ".gitignore verified to exclude credentials.json, .env and any *.key or *.pem.",
            ".env.example present and accurate (done 2026-07-22).",
            "Service account granted the required Search Console permission on every target property, including Owner where the Indexing API is used.",
            "All 10 tools smoke-tested against a live property.",
            "Tool names namespaced and every caller updated.",
            "README documenting install, environment variables and the write-tool blast radius.",
            "Indexing API quota consumption understood and tracked.",
            "Root-level one-off scripts removed.",
        ]},

        # 10
        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"], "rows": [
            ["Engineering owner / maintainer", "Musfiqur Tuhin", "Part-time, as needed"],
            ["Remediation engineer (SDK, zod, tests)", "TBD — assigned engineer", "~5 days across M4 and M5"],
            ["Security reviewer (key rotation sign-off)", "TBD — named reviewer", "0.5 day"],
            ["SEO consumer / requirements", "TBD — SEO Growth Engine owner", "Advisory"],
        ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "Search Console API: free, quota-limited rather than priced.",
            "Indexing API: free, capped at roughly 200 requests/day per project — the binding constraint is quota, not money.",
            "Google Cloud project: no billable services in use by this server.",
            "Infrastructure: none. The server runs as a local subprocess on the operator's machine.",
            "The real cost is engineering time — roughly 7 days across the milestones above — plus the unpriced risk carried by the un-rotated compromised key.",
        ]},

        # 11
        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "para", "text": "Musfiqur Tuhin owns the code, the service account and the deployment. There is no on-call rotation and no SLA. Failure is visible immediately and only inside the agent session that made the call; there is no alerting, because there is no always-on process to alert on."},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "para", "text": "Support is direct to the maintainer. There is no README at v1.0.0, so onboarding currently means reading src/index.ts. Diagnosis follows a short path: check that GOOGLE_APPLICATION_CREDENTIALS points at a readable key file, that GSC_SITE_URL matches a property exactly including the sc-domain: form or trailing slash, that the service account has been granted access in the Search Console UI, and that dist/ has been rebuilt after the last source change."},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "Track googleapis and MCP SDK releases; the SDK pin is already several majors behind the monorepo baseline.",
            "Watch for Google Search Console API deprecations, particularly around URL inspection and the Indexing API's eligibility rules.",
            "Rotate the service-account key on a defined schedule once the current compromised key is replaced.",
            "Delete the root-level one-off scripts rather than maintaining two copies of the same logic.",
            "Deprecation path: if HaorGrix consolidates on a single multi-provider SEO MCP server, this one is retired by removing its MCP registration; no data migration is involved because the server stores nothing.",
        ]},

        # 12
        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "table", "header": ["Area", "Consideration", "Owner or Status"], "rows": [
            ["Google API Terms of Service", "Use of Search Console and Indexing APIs is bound by Google's terms, including the prohibition on abusing the Indexing API for content it was not intended for", "Musfiqur Tuhin — compliant"],
            ["Credential handling", "A service-account key was committed to git history and purged on 2026-07-22; the key must be treated as compromised until rotated", "Open — rotation pending"],
            ["Client data access", "Where the property belongs to a client, the service account is accessing client-owned search data; access must be authorised by the client", "TBD — confirm authorisation per property"],
            ["Personal data", "GSC search analytics is aggregated and anonymised, but query strings may contain user-typed personal information", "Do not log or forward raw query rows to third-party destinations"],
            ["Data residency", "All data stays in Google's systems and in transient process memory; the server persists nothing", "Compliant by design"],
            ["Open-source licensing", "Dependencies are permissively licensed (MIT / Apache-2.0); the server itself is private and unlicensed for external use", "Compliant"],
            ["Repository confidentiality", "HaorGrix/mcp-servers is private and must remain so given the credentials and property names it references", "Musfiqur Tuhin"],
        ]},

        {"kind": "break"},
        # 13
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"], "rows": [
            ["The service-account credentials.json was committed to git history and purged on 2026-07-22; the key must be treated as compromised. Anyone with a pre-purge clone still holds a working key.", "High", "Critical", "Rotate the key in Google Cloud IAM and revoke the old one; verify no valid key remains; confirm .gitignore excludes credentials.json before any further commit."],
            ["Tool names are not namespaced, unlike every sibling server (brevo_, cp_, ga_, wp_). Mounting multiple servers in one agent session risks tool-name collision and misdirected calls.", "High", "High", "Rename all 10 tools to gsc_* in M2 and update every caller in the same change."],
            ["Six one-off scripts in the repository root duplicate tool logic outside the server and will drift from it.", "High", "Medium", "Fold any missing behaviour into tools, then delete the scripts (M3)."],
            ["MCP SDK pinned at ^1.0.1, the oldest in the monorepo, while siblings run 1.12.0 and 1.29.0.", "Medium", "Medium", "Upgrade to the monorepo baseline and align the server construction API with the siblings."],
            ["No zod and no runtime argument validation; hand-written JSON schemas are advertised but unenforced.", "High", "Medium", "Adopt zod schemas and reject invalid input with field-level messages before calling Google."],
            ["Write tools have no confirmation guard. delete_sitemap is irreversible from the server's side and submit_url_for_indexing spends finite quota.", "Medium", "High", "Add a confirm flag to destructive and quota-bound tools."],
            ["Indexing API quota is roughly 200 requests/day and is not tracked client-side; an agent loop can exhaust it silently.", "Medium", "Medium", "Track daily consumption, expose the remaining budget in the tool response, and refuse calls past a soft ceiling."],
            ["Indexing API requires Owner permission on the property; a read-only grant makes the tool fail at call time rather than at startup.", "Medium", "Low", "Check permission level during startup or in list_sites output and state the requirement in the tool description."],
            ["No tests at all; regressions are only discovered by an agent failing mid-task.", "High", "Medium", "Ship the read-tool smoke suite in M5."],
            ["No README; onboarding requires reading the source.", "High", "Low", "Write the README from this PRD."],
            ["The dev script is tsc --watch only, so it recompiles without running the server; a maintainer expecting a watch-and-run loop sees no server.", "Medium", "Low", "Rename to build:watch or pair tsc --watch with a process runner."],
            ["No retry or backoff on Google API errors; transient 5xx responses fail the tool call outright.", "Medium", "Low", "Add bounded retry with backoff on retryable status codes."],
            ["The 2-3 day reporting lag can be mistaken for a data outage or a genuine traffic drop.", "Medium", "Medium", "State the lag in every tool description and in agent-facing output."],
            ["Google Search Console query anonymisation means query-level sums never match property totals; derived tools can therefore understate opportunity.", "High", "Low", "Document the limitation in the derived tools' descriptions."],
        ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"], "rows": [
            ["The service-account key committed to git history was purged on 2026-07-22 but has not been rotated. When is rotation scheduled, and who confirms the old key is revoked in Google Cloud IAM?", "Musfiqur Tuhin", "Open — blocking"],
            ["Should all 10 tools be renamed to a gsc_ prefix to match the rest of the monorepo, and who updates the existing callers and saved agent prompts?", "Musfiqur Tuhin", "Open — recommended yes"],
            ["Do the six root-level scripts contain behaviour not covered by any tool, and if so which tools must absorb it before deletion?", "Musfiqur Tuhin", "Open"],
            ["Does the service account hold Owner permission on every property where submit_url_for_indexing is expected to work?", "Musfiqur Tuhin", "Open"],
            ["Should write tools be gated behind an environment flag so a read-only deployment is possible?", "TBD — assigned engineer", "Open"],
            ["Is a single GSC_SITE_URL sufficient, or is multi-property support needed for client work?", "TBD — SEO Growth Engine owner", "Open"],
            ["Which client properties has HaorGrix been authorised to access via this service account?", "TBD — account owner", "Open"],
            ["Should the derived tools (CTR rescue, position changes) expose their thresholds as parameters rather than fixed values?", "Musfiqur Tuhin", "Open"],
            ["Is an HTTP transport ever required, or does stdio remain sufficient for all consumers?", "Musfiqur Tuhin", "Open — currently a non-goal"],
        ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"], "rows": [
            ["2026-07", "Use a Google service account rather than OAuth user consent", "No interactive consent flow is possible in a headless stdio server", "Musfiqur Tuhin"],
            ["2026-07", "stdio transport only", "The server runs as a local subprocess of the agent host; no network exposure is wanted", "Musfiqur Tuhin"],
            ["2026-07", "Hand-written JSON schemas instead of zod", "Speed of first delivery; recorded here as technical debt, not as a preference", "Musfiqur Tuhin"],
            ["2026-07", "Include derived analysis tools (CTR rescue, position changes) rather than only API pass-throughs", "The derived answers are the actual SEO workflow; making the agent reconstruct them from raw rows is slower and less reliable", "Musfiqur Tuhin"],
            ["2026-07", "Include write tools (sitemap submit/delete, indexing submission) despite the blast radius", "Local, trusted, single-operator execution; guards deferred", "Musfiqur Tuhin"],
            ["2026-07-22", "Purge credentials.json from git history and add .env.example and credentials.example.json", "The live key was committed; history purge is the first half of remediation, rotation is the second", "Musfiqur Tuhin"],
            ["2026-07-22", "Document the server at PRD v0.1 from the shipped source rather than from intent", "The gaps (no tests, no README, no namespacing, old SDK) are the point of the document", "Musfiqur Tuhin"],
        ]},

        # 14
        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "para", "text": "Public Search Console MCP servers exist on npm and GitHub, generally as thin wrappers over sites.list, searchanalytics.query and urlInspection. Two things justify an in-house build. First, credentials: a third-party server would need HaorGrix's service-account key, which is unacceptable for client properties. Second, the derived tools — get_ctr_rescue_candidates and get_position_changes encode HaorGrix's own analysis, not Google's API surface, and no off-the-shelf server provides them. The alternatives considered and rejected were the GSC web UI (manual, not agent-readable), scheduled export scripts (which is exactly what the six root-level files are, and what this server replaces), and a third-party MCP server (credential exposure, no derived analysis)."},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"], "rows": [
            ["MCP", "Model Context Protocol — the specification by which an AI agent discovers and calls external tools."],
            ["stdio transport", "MCP over a subprocess's standard input and output; no network listener."],
            ["GSC", "Google Search Console."],
            ["Property", "A site registered in Search Console, either URL-prefix (https://example.com/) or domain (sc-domain:example.com)."],
            ["Service account", "A non-human Google Cloud identity authenticating with a JSON key file, granted access to a property in the Search Console UI."],
            ["Search analytics", "The GSC dataset of clicks, impressions, CTR and average position, sliceable by query, page, country, device, search appearance and date."],
            ["CTR", "Click-through rate — clicks divided by impressions."],
            ["Average position", "The mean ranking position of a result across the impressions it received."],
            ["CTR rescue candidate", "A query with high impressions and near-zero CTR: it ranks and is seen but is not clicked, making it a title and meta-description rewrite target."],
            ["Position change analysis", "A comparison of average position between two date ranges, reported per query as a gain or a loss."],
            ["URL inspection", "The GSC API returning Google's index verdict, last crawl time, rich-result state and mobile usability for a single URL."],
            ["Indexing API", "A separate Google API for notifying Google that a URL was updated or deleted; requires Owner permission and is capped near 200 requests/day."],
            ["Sitemap", "An XML feed of a site's URLs submitted to Search Console to aid discovery."],
            ["Reporting lag", "The 2-3 day delay before Search Console data becomes queryable."],
            ["Data retention", "Search Console keeps 16 months of search analytics history; older data is unavailable at any price."],
            ["Query anonymisation", "Google's suppression of low-volume query strings, which prevents query-level rows from summing to property totals."],
            ["Namespacing", "Prefixing tool names with a server identifier (gsc_) so that concurrently mounted servers cannot collide."],
            ["zod", "A TypeScript schema-validation library used by sibling servers and absent here."],
        ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": "Complete tool inventory by classification — 10 tools total. Read (7): list_sites, get_search_analytics, inspect_url, list_sitemaps, get_indexing_status, get_ctr_rescue_candidates, get_position_changes. Of these, get_ctr_rescue_candidates and get_position_changes are derived rather than API pass-throughs. Write (3): submit_sitemap, delete_sitemap, submit_url_for_indexing. None of the 10 names carries a namespace prefix."},
        {"kind": "para", "text": "Root-level one-off scripts, outside src/ and outside the tsconfig include path: run_ctr.ts, run_sitemap.ts, submit_sitemap.ts, run_gsc_analytics.ts, hg_pushall.ts, test-gsc.ts. Each duplicates logic that a tool already covers or should cover."},
        {"kind": "bullets", "items": [
            "Server folder: Tooling/MCP/google-search-console-mcp/ in HaorGrix/mcp-servers, branch main.",
            "Version 1.0.0. Roughly 588 lines of TypeScript across src/index.ts (337) and src/client.ts (251).",
            "Environment variables: GOOGLE_APPLICATION_CREDENTIALS, GSC_SITE_URL. .env.example added 2026-07-22.",
            "npm scripts: build (tsc), start (node dist/index.js), dev (tsc --watch — recompiles only, does not run the server).",
            "TypeScript target ES2022, module Node16, strict mode; no type field in package.json, so CommonJS output.",
            "MCP SDK ^1.0.1 — oldest pin in the monorepo (siblings at 1.12.0, Meta Ads at 1.29.0).",
            "Not present at v1.0.0: README, tests, zod validation, tool namespacing, retry/backoff, structured logging, quota tracking, write-tool confirmation guards.",
        ]},
        {"kind": "meta", "text": "Scope note: this PRD describes the Google Search Console MCP server only. Behaviour is documented from the source at v1.0.0 as of 2026-07-22; items marked NOT IMPLEMENTED are requirements, not present features."},
    ],
}
