"""Portfolio-level index PRD covering all six HaorGrix MCP servers."""

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "HaorGrix MCP Server Portfolio — Index",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        {"kind": "para", "text": "Document Owner: Musfiqur Tuhin  •  Status: Draft  •  Version 0.1  •  Last Updated: 2026-07-22"},
        {"kind": "meta", "text": "This index is the portfolio-level view. Each server has its own full PRD; this document covers only what is true across all of them and should not be read as a substitute for the individual documents."},

        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Summary of Changes"], "rows": [
            ["0.1", "2026-07-22", "Musfiqur Tuhin", "Initial portfolio index covering six MCP servers; created alongside the monorepo consolidation into HaorGrix/mcp-servers."],
        ]},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Approval"], "rows": [
            ["Product Manager", "Musfiqur Tuhin", "Owns the PRD set & priorities", "☐"],
            ["Engineering Lead", "Musfiqur Tuhin", "Technical feasibility & delivery", "☐"],
            ["Design Lead", "N/A — no human-facing UI", "Tool naming & description ergonomics", "☐"],
            ["QA Lead", "TBD — unassigned", "Test strategy & acceptance", "☐"],
            ["Business / Exec Sponsor", "HaorGrix", "Strategic alignment & budget", "☐"],
        ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Monorepo: https://github.com/HaorGrix/mcp-servers (private), branch main",
            "Per-server PRDs: documentation/PRD/01-Brevo … 06-WordPress",
            "Repository overview and setup: README.md at the monorepo root",
            "Change history: CHANGELOG.md at the monorepo root",
            "Model Context Protocol specification: https://modelcontextprotocol.io",
        ]},

        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "HaorGrix operations span six third-party platforms — Brevo, cPanel, Google Analytics 4, Google Search Console, Meta Ads, and WordPress with WooCommerce. Routine work on these platforms (pulling a performance report, purging a cache after a deploy, checking whether a page is indexed, pausing an over-spending ad set) is performed by hand through six separate web UIs. That work is slow, it is not reproducible, it leaves no audit trail, and it cannot be delegated to an AI agent because no machine-readable interface exists that an agent can safely drive."},
        {"kind": "para", "text": "Each platform does expose an API, but each has a different authentication model, pagination scheme, rate-limit behaviour, and error vocabulary. Writing throwaway scripts against them — which is what happened before this project — produces code that is neither shared, reviewed, nor guarded against destructive mistakes."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": "A monorepo of six Model Context Protocol servers, one per platform, each exposing that platform's capabilities as typed MCP tools over stdio. An AI agent mounts the servers it needs and drives them through a single uniform protocol, while each server owns the platform-specific concerns — auth, pagination, retries, rate limiting, and guard rails on destructive operations — behind a stable tool surface."},
        {"kind": "para", "text": "The six servers expose 161 tools in total. They are consolidated into one repository so that credential handling, gitignore discipline, tool-naming conventions, and release process are set once and applied uniformly, rather than drifting per project."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "The servers were built incrementally between roughly 2026-06 and 2026-07 as individual needs arose, initially as separate working directories. They were first consolidated into a single local git repository on 2026-07-07, extended with the Google Analytics server on 2026-07-15, and the Meta Ads server was rewritten to v2 on 2026-07-21 to add pagination, complete insights coverage, and guarded writes."},
        {"kind": "para", "text": "On 2026-07-22 the repository was audited before being published to GitHub. That audit found two Google service-account private keys committed in the git history. The history was rewritten to purge them and the repository was pushed private. Both keys must be treated as compromised until rotated; this is tracked as an open action in section 13."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "This portfolio is the execution layer for HaorGrix's agent-driven operations. Client-facing work — SEO campaigns, WordPress site management, email marketing, paid media — is delivered on these six platforms. Every tool added here converts a manual, unlogged, per-client task into a repeatable operation an agent can perform, which is what makes the service model scale beyond the number of hours the team can bill."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Make all six operational platforms reachable by AI agents through one uniform protocol.",
            "Cut the manual effort of routine platform operations (reporting, cache purges, indexing checks, campaign hygiene) by making them single tool calls.",
            "Prevent agent-driven accidents on production systems and live ad spend through explicit write guards, confirmation gates, and audit logging.",
            "Establish one credential and release discipline across all servers instead of six divergent ad-hoc setups.",
        ]},

        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "By 2026-08-31, bring every server to a common baseline: a README, a .env.example, a typecheck script, and a smoke test that verifies the server starts and lists its tools.",
            "By 2026-08-31, align all six servers on a single MCP SDK version, eliminating the current 1.0.1 → 1.29.0 spread.",
            "By 2026-08-15, rotate both compromised Google service-account keys and confirm no secret material remains in the repository or its history.",
            "By 2026-09-30, put a confirmation gate or a global write-enable flag in front of every destructive tool in cpanel-mcp and wordpress-mcp, matching the pattern already used by brevo-mcp and mcp-meta-ads.",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"], "rows": [
            ["Servers with a test suite", "1 of 6 (brevo-mcp)", "6 of 6", "Presence of a passing `npm test` in each package"],
            ["Servers with a README", "4 of 6", "6 of 6", "Repository file check"],
            ["Servers with a .env.example", "6 of 6 (as of 2026-07-22)", "6 of 6", "Repository file check"],
            ["MCP SDK version spread", "3 distinct versions (1.0.1, 1.12.0, 1.29.0)", "1 version", "package.json audit across packages"],
            ["Destructive tools behind a guard", "33 of 161 tools guarded (brevo, meta only)", "100% of destructive tools", "Tool-by-tool audit against the inventory in each PRD"],
            ["Secrets in repository or history", "0 (after 2026-07-22 purge)", "0", "gitleaks or equivalent scan in CI"],
            ["Unrecovered agent failures per week", "Not measured", "< 1", "Agent session review; per-server error logs"],
        ]},
        {"kind": "h2", "text": "3.3 Non-Goals / Out of Scope"},
        {"kind": "bullets", "items": [
            "A hosted or multi-tenant deployment. All servers run locally over stdio against a single operator's credentials; HTTP/SSE transport is explicitly out of scope for this version.",
            "Publishing any server to npm or to a public MCP registry.",
            "A shared runtime library across servers. Some duplication (HTTP client, retry logic) is accepted for now in exchange for keeping each server independently deployable.",
            "Per-tool authorization or role-based access control. Each server runs with one credential at full privilege.",
            "Adding new platforms. This document covers only the six servers that exist.",
        ]},

        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"], "rows": [
            ["Name / Segment", "The operating agent — an AI assistant with the servers mounted"],
            ["Role & Context", "Executes multi-step operational tasks on behalf of an operator; sees only tool names, descriptions, and JSON schemas"],
            ["Goals", "Select the correct tool on the first attempt, pass valid arguments, and interpret the result without a second clarifying call"],
            ["Pain Points", "Ambiguous or overlapping tool names; descriptions that omit required preconditions; errors returned as opaque upstream JSON with no remediation hint"],
            ["Technical Proficiency", "High, but strictly bounded by what the tool schema and description state"],
        ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "The operator (Musfiqur Tuhin and the HaorGrix team) — configures credentials, reviews what the agent did, and is accountable for anything the agent changes on a production system or an ad account.",
            "The maintaining engineer — extends a server with new tools, upgrades the SDK, and debugs failures; needs the source to be readable and the behaviour to be tested.",
            "The client whose property is being operated on — never interacts with these servers, but bears the consequence of a mistaken write.",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an operating agent, I want every server to expose its tools over a single uniform protocol so that I do not need platform-specific integration code.",
            "As an operating agent, I want tool names to be unambiguous across all mounted servers so that I never invoke the wrong platform's tool.",
            "As an operator, I want destructive operations to require an explicit confirmation or a configuration flag so that an agent cannot delete a database or spend money by misinterpreting an instruction.",
            "As an operator, I want a record of every write an agent performed so that I can review and, where possible, reverse it.",
            "As a maintaining engineer, I want each server to build, typecheck, and pass a smoke test from a clean checkout so that I can change one without fear of breaking it silently.",
            "As a maintaining engineer, I want no secret material in the repository so that publishing it does not leak a credential.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "meta", "text": "Portfolio-level requirements only. Per-tool functional requirements live in the six individual PRDs."},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"], "rows": [
            ["FR-1", "Each server shall implement the Model Context Protocol over stdio and respond correctly to tools/list and tools/call.", "Must", "Given a server started with valid configuration, when an MCP client sends tools/list, then the full tool set is returned with valid JSON schemas."],
            ["FR-2", "Each server shall read all credentials from environment variables, never from committed files.", "Must", "No credential value appears in any tracked file; each server fails fast with a named error when a required variable is absent."],
            ["FR-3", "The repository shall contain no secret material in the working tree or in git history.", "Must", "A secret scan over all refs returns no findings."],
            ["FR-4", "Every tool shall be namespaced with its server prefix so that names are unique when multiple servers are mounted together.", "Should", "All tool names match a per-server prefix; the unprefixed names currently in google-search-console-mcp and mcp-meta-ads are renamed, with the old names kept as deprecated aliases for one release."],
            ["FR-5", "Every destructive tool shall be gated by either a confirmation argument or a server-level write-enable flag.", "Should", "Given a destructive tool invoked without the gate satisfied, when it is called, then it returns a refusal explaining the gate and performs no upstream mutation."],
            ["FR-6", "Each server shall record every successful write operation to an audit log.", "Should", "The log records timestamp, tool name, arguments with secrets redacted, and outcome. Currently implemented in brevo-mcp only."],
            ["FR-7", "Each server shall surface upstream API errors with the failing tool, the upstream status, and a remediation hint, with credentials redacted.", "Should", "Given an upstream 401, when a tool is called, then the error names the missing or invalid credential without echoing its value."],
            ["FR-8", "Each server shall respect upstream rate limits with backoff and bounded retries rather than failing on the first throttle.", "Should", "Given an upstream 429, when a tool is called, then the request is retried with backoff up to the configured maximum before surfacing an error."],
            ["FR-9", "Each server shall ship a README, a .env.example, and a smoke test that verifies startup and tool listing.", "Should", "All six packages contain the three artefacts and `npm test` passes."],
            ["FR-10", "All servers shall depend on a single common MCP SDK version.", "Could", "A single @modelcontextprotocol/sdk version appears across all six package.json files."],
            ["FR-11", "Servers shall support HTTP/SSE transport in addition to stdio.", "Won't (this time)", "Deferred. Recorded so it is not lost; stdio-only is sufficient for the current single-operator local model."],
        ]},
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Entry point: the operator states an intent in natural language to an agent that has one or more of these servers mounted.",
            "The agent reads the mounted tool catalogue and selects a tool by name and description.",
            "The agent calls the tool with arguments validated against its JSON schema; a schema violation is rejected before any upstream call is made.",
            "The server authenticates to the upstream platform using environment-supplied credentials and issues the request, paginating and retrying per its configured policy.",
            "For a destructive tool, the server first checks its guard — a confirmation string or a write-enable flag — and refuses with an explanation if it is not satisfied.",
            "The server returns a structured result, or a redacted error naming the failing tool and a remediation hint.",
            "Success state: the agent reports the outcome to the operator, and any write is recorded in the audit log for later review.",
        ]},

        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"], "rows": [
            ["Performance", "A read tool backed by a single upstream call returns within 5 s p95. Paginated reads are bounded by a configurable page cap so a large account cannot hang a session indefinitely."],
            ["Scalability", "Single-operator, single-process, one credential set per server. Concurrent multi-tenant use is out of scope; scaling is by running additional local instances with different configuration."],
            ["Availability", "No uptime SLA — servers are started on demand by the MCP client. Effective availability is bounded by the upstream platform APIs, none of which HaorGrix controls."],
            ["Security", "Credentials are supplied only through environment variables and never written to disk by the server. Secrets are redacted from all errors and logs. All upstream traffic is HTTPS. Destructive operations are guarded. No secret material is committed."],
            ["Privacy / Compliance", "The servers process personal data on behalf of clients: contact records and email engagement (Brevo), WooCommerce customer and order data (WordPress), and website analytics (GA4, GSC). GDPR and CCPA obligations sit with the data controller. No personal data is persisted by the servers themselves beyond transient in-memory handling and whatever the audit log records."],
            ["Accessibility", "N/A — headless servers with no human-facing UI. Operator-facing output is plain text rendered by the MCP client, which owns accessibility."],
            ["Observability", "Structured errors on every tool failure and an append-only audit log for writes. Currently implemented in brevo-mcp only; extending it to the other five is FR-6."],
            ["Localization", "N/A — tool names, descriptions, and error strings are English only. Upstream content in any language passes through unmodified."],
        ]},

        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "bullets", "items": [
            "Systems impacted: Brevo, cPanel/WHM, Google Analytics 4 (Data and Admin APIs), Google Search Console (plus the Indexing API), Meta Graph API, WordPress REST, WooCommerce REST, and Cloudflare.",
            "New infrastructure: none. Every server is a local Node process launched by the MCP client over stdio.",
            "Runtime: Node >= 18. Five servers are TypeScript compiled with tsc; mcp-meta-ads is plain ESM JavaScript with no build step.",
            "Shared dependencies: @modelcontextprotocol/sdk (versions 1.0.1, 1.12.0, and 1.29.0 are currently in use), zod for schema validation in four of six servers, and dotenv.",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "bullets", "items": [
            "The servers hold no datastore of their own. Every entity — contact, campaign, ad set, post, order, DNS record — is owned by the upstream platform and read or written in place.",
            "The API contract is the MCP tool surface: 161 tools across six servers, each with a JSON schema for its arguments. Those schemas are the versioned interface and a breaking change to one is a breaking change for every agent using it.",
            "Per-tool inventories, argument shapes, and read/write classification are documented in the six individual PRDs.",
        ]},
        {"kind": "h2", "text": "7.3 Integrations & External Dependencies"},
        {"kind": "table", "header": ["Dependency / Integration", "Owner / Team", "Type", "Status / Notes"], "rows": [
            ["Brevo API", "Brevo", "Vendor", "Available. API key auth."],
            ["cPanel UAPI", "Hosting provider", "Vendor", "Available. Basic auth with account password; API-token support not yet implemented."],
            ["Google Analytics 4 Data & Admin APIs", "Google", "Vendor", "Available. Service-account auth; key rotation outstanding."],
            ["Google Search Console & Indexing APIs", "Google", "Vendor", "Available. Service-account auth; Indexing API needs Owner permission and is capped near 200 requests/day."],
            ["Meta Graph API", "Meta", "Vendor", "Available. Version-pinned via META_API_VERSION; deprecated on roughly a two-year cycle."],
            ["WordPress REST & WooCommerce REST", "HaorGrix / client sites", "Internal & client", "Available. Application Password and Woo consumer key/secret."],
            ["Cloudflare API", "Cloudflare", "Vendor", "Optional. Used only by wordpress-mcp for zone cache purge."],
            ["Agent Cache Control mu-plugin", "HaorGrix", "Internal", "Deployed by cpanel-mcp's cp_deploy_cache_helper; required by three wordpress-mcp tools. This is the one hard cross-server dependency in the portfolio."],
            ["@modelcontextprotocol/sdk", "Anthropic", "Vendor", "Version spread across servers is a known debt (FR-10)."],
        ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "Constraint: stdio transport only, so each server runs on the same machine as the MCP client.",
            "Constraint: one credential set per server process, at whatever privilege that credential holds. There is no per-tool authorization layer.",
            "Constraint: every server is bounded by upstream rate limits, quotas, and data-freshness lags that HaorGrix does not control.",
            "Assumption: the operator reviews consequential agent actions rather than running fully unattended, which is why guards are confirmations rather than policy engines.",
            "Assumption: the machine running these servers is trusted and its environment variables are not readable by third parties.",
            "Assumption: usage stays within the free or already-paid tiers of the upstream APIs, so no incremental API cost is expected.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "table", "header": ["Event / Metric", "Trigger", "Properties", "Destination"], "rows": [
            ["tool_invoked", "Any tools/call is received", "server, tool_name, read_or_write, duration_ms, outcome", "Local audit log"],
            ["tool_failed", "A tool returns an error", "server, tool_name, upstream_status, error_class", "Local audit log"],
            ["write_performed", "A mutating tool completes successfully", "server, tool_name, redacted_arguments, upstream_id", "Local audit log (brevo-mcp today; FR-6 extends it)"],
            ["guard_refused", "A destructive tool is called without its gate satisfied", "server, tool_name, gate_type", "Local audit log"],
            ["rate_limited", "An upstream 429 or throttle is observed", "server, upstream, retry_count, backoff_ms", "Local audit log"],
        ]},

        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "These are headless servers. There is no GUI, no wireframe, and no design system. The design surface is the tool catalogue itself, because a tool name, its description, and its JSON schema are the entire affordance an agent has for deciding what to call."},
        {"kind": "bullets", "items": [
            "Naming: tools should be prefixed by server (brevo_, cp_, ga_, wp_) so names stay unique when several servers are mounted at once. Two servers do not yet follow this and are covered by FR-4.",
            "Descriptions: each description must state what the tool does, whether it mutates anything, and any precondition — for example that wp_get_post_meta requires the Agent Cache Control mu-plugin, or that submit_url_for_indexing requires Owner permission.",
            "Errors: failures should name the failing tool, the upstream status, and what the operator can do about it, with credentials redacted. An unadorned upstream JSON blob forces the agent to guess.",
            "Guard ergonomics: a confirmation gate should be a literal string the agent must repeat (as brevo_schedule_campaign requires confirm=\"SCHEDULE\"), so that satisfying it is a deliberate act rather than a default-filled boolean.",
            "Edge-case states: empty results, partial pagination, and truncated result sets must be reported explicitly. Silently returning a capped list reads to an agent as a complete one.",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases / Milestones"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"], "rows": [
            ["Consolidation", "Six servers merged into one local repository with shared gitignore and README", "Musfiqur Tuhin", "2026-07-07 (done)"],
            ["Meta Ads v2", "Full rewrite: pagination, complete insights, guarded writes", "Musfiqur Tuhin", "2026-07-21 (done)"],
            ["Security remediation & publish", "Purge service-account keys from history, add credential examples, push private to HaorGrix/mcp-servers", "Musfiqur Tuhin", "2026-07-22 (done)"],
            ["Key rotation", "Rotate both compromised Google service-account keys and verify no residual access", "Musfiqur Tuhin", "2026-08-15"],
            ["Baseline parity", "README, .env.example, smoke test, and typecheck for all six servers; single SDK version", "TBD — unassigned", "2026-08-31"],
            ["Guard parity", "Confirmation gate or write-enable flag on every destructive tool in cpanel-mcp and wordpress-mcp", "TBD — unassigned", "2026-09-30"],
            ["Tool-name normalisation", "Prefix the unprefixed tools in google-search-console-mcp and mcp-meta-ads, with deprecated aliases", "TBD — unassigned", "2026-09-30"],
        ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "bullets", "items": [
            "Phased rollout: there is no feature-flag infrastructure. A server is rolled out by updating the MCP client config to point at the new build; the previous build remains on disk.",
            "Migration: no data migration is involved, since the servers hold no state. Tool renames under FR-4 ship with the old name retained as a deprecated alias for one release so agent prompts and saved workflows do not break on upgrade.",
            "Rollback: revert the MCP client config to the prior entrypoint, or `git checkout` the previous commit and rebuild. Rollback does not undo upstream writes already performed — those must be reversed on the platform itself, which is precisely why the guards in FR-5 matter.",
            "Deprecated versions are moved to archive/ rather than deleted, as was done for Meta Ads v1.",
        ]},
        {"kind": "h2", "text": "9.3 Effort & Timeline Estimates"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"], "rows": [
            ["Key rotation & secret scanning in CI", "Musfiqur Tuhin", "0.5 wk", "Google Cloud console access"],
            ["Baseline parity across six servers", "TBD — unassigned", "2 wks", "None"],
            ["SDK version alignment", "TBD — unassigned", "0.5 wk", "Regression check per server; 1.0.1 → 1.29.0 is the risky jump"],
            ["Guard parity (cpanel, wordpress)", "TBD — unassigned", "1.5 wks", "Agreement on the gate convention"],
            ["Tool-name normalisation", "TBD — unassigned", "0.5 wk", "Alias mechanism; client config update"],
            ["QA / smoke test authoring", "TBD — unassigned", "1 wk", "Test credentials or a sandbox per platform"],
        ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "☐ QA sign-off complete — blocked: five of six servers have no tests",
            "☑ Monitoring: structured errors present; ☐ audit log extended beyond brevo-mcp",
            "☐ Analytics events instrumented and verified (section 7.5)",
            "☑ Documentation: monorepo README and six PRDs; ☐ per-server README for cpanel-mcp",
            "☑ Security review passed for the committed-secret finding; ☐ key rotation confirmed",
            "☑ Rollback plan tested — config revert and rebuild",
            "☐ Write guards in place on every destructive tool (FR-5)",
        ]},

        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"], "rows": [
            ["Product Manager", "Musfiqur Tuhin", "Part-time, alongside delivery work"],
            ["Engineering", "Musfiqur Tuhin", "Sole maintainer across all six servers"],
            ["Design", "N/A — no human-facing UI", "—"],
            ["QA", "TBD — unassigned", "Currently unstaffed; the single largest gap in the portfolio"],
        ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "Infrastructure / hosting: none. The servers run locally as child processes of the MCP client.",
            "Third-party / licensing: no incremental cost. All six platforms are already licensed for HaorGrix operations and the APIs used sit within existing plan entitlements.",
            "Operational cost: maintenance is the real cost — upstream APIs deprecate versions (Meta on roughly a two-year cycle), change quotas, and alter response shapes, and each break requires engineering time from a single maintainer.",
            "Risk cost: an unguarded destructive tool can cause real financial loss — deleted client data, or live ad spend through mcp-meta-ads. This is the strongest argument for funding the guard-parity workstream.",
        ]},

        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "bullets", "items": [
            "Owning team post-launch: HaorGrix engineering, with Musfiqur Tuhin as sole maintainer.",
            "Runbooks: TBD — no runbook exists. Recovery today is source-reading plus manual correction on the affected platform.",
            "SLAs / SLOs: none defined. These are internal tools; failures degrade agent capability rather than a customer-facing service.",
            "Escalation: a destructive mistake on a client property escalates directly to the client account owner, since the consequence is visible on the client's system.",
        ]},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "bullets", "items": [
            "Documentation: the monorepo README plus these seven PRDs. Four of six servers carry their own README; cpanel-mcp does not.",
            "Known limitations to communicate: stdio only; one credential per server at full privilege; five servers untested; two servers expose unbounded escape hatches (cp_uapi_call and wp_rest_request) that bypass every typed guardrail; result sets can be capped by pagination limits.",
            "Feedback: failures surface in the operator's own agent sessions; there is no separate intake channel.",
        ]},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "Ongoing maintenance: track upstream API version deprecations, refresh expiring credentials (Meta long-lived user tokens expire in roughly 60 days), and keep the MCP SDK current.",
            "What this replaces: the ad-hoc per-platform scripts that previously lived outside version control. Residual one-off scripts still sit in google-search-console-mcp's root and duplicate tool logic; they should be removed once the corresponding tools are trusted.",
            "Deprecation policy: superseded servers move to archive/ with a note recording what replaced them and why, as was done for Meta Ads v1.",
        ]},

        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "table", "header": ["Area", "Consideration", "Owner / Status"], "rows": [
            ["Data privacy", "Personal data flows through Brevo contacts and email engagement, WooCommerce customers and orders, and GA4/GSC analytics. The servers add no storage of their own, but tool results enter an agent's context window and any transcript retained there.", "Musfiqur Tuhin — needs review"],
            ["Security review", "Completed 2026-07-22 for the committed-secret finding; history purged. A threat model covering the two escape-hatch tools and the absence of write guards has not been done.", "Musfiqur Tuhin — partially complete"],
            ["Regulatory / compliance", "GDPR and CCPA apply to client contact and customer data. No SOC 2 or HIPAA scope. PCI is not implicated: WooCommerce order tools read order metadata, not cardholder data, which the payment gateway holds.", "TBD — needs confirmation per client"],
            ["Legal / contractual", "Use of each platform is bound by its own API terms. Client authorisation to operate their property via automation should be explicit in the engagement terms.", "TBD — needs confirmation"],
            ["Data retention & deletion", "No server-side retention. The audit log is local and currently unbounded — a retention period should be set before it is extended to all six servers.", "Musfiqur Tuhin — open"],
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks & Mitigations"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"], "rows": [
            ["The two Google service-account keys committed to git history are used by an unauthorised party before rotation.", "L", "H", "History was purged and the repository is private and was never public. Rotate both keys by 2026-08-15 and review Google Cloud audit logs for unexpected access."],
            ["An agent invokes a destructive tool in cpanel-mcp or wordpress-mcp on a misread instruction — dropping a database, deleting a user, removing a DNS record.", "M", "H", "Implement FR-5 guard parity. Until then, keep those servers mounted only for supervised sessions."],
            ["An agent creates and activates Meta ad entities, incurring real spend.", "L", "H", "Writes already refuse unless META_ALLOW_WRITES is set. Keep it unset by default and enable only for a specific supervised task."],
            ["cp_uapi_call or wp_rest_request is used to reach an operation that has no typed guardrail at all.", "M", "H", "Treat both as break-glass. Restrict or remove them once the typed tool coverage is judged sufficient; log every invocation."],
            ["A change to one of five untested servers breaks it silently and the failure only surfaces mid-task on a client property.", "H", "M", "Implement the smoke tests in FR-9; run typecheck in CI on every push."],
            ["cp_delete_dns_record and cp_remove_cron key on brittle identifiers (line number, exact command string), so a concurrent edit causes the wrong record to be deleted.", "M", "M", "Re-read and verify the target immediately before deletion; prefer content-matched identification over positional."],
            ["Unprefixed tool names in two servers collide with another server's tools when mounted together, causing the wrong platform to be called.", "M", "M", "Implement FR-4 name normalisation with deprecated aliases."],
            ["An upstream API version deprecation breaks a server without warning.", "M", "M", "Pin versions where the platform allows it (META_API_VERSION), and subscribe to each vendor's deprecation notices."],
            ["A pagination cap silently truncates a result set and the agent reports a partial answer as complete.", "M", "M", "Return an explicit truncation flag whenever a cap is hit, and state it in the tool description."],
            ["Single-maintainer concentration: all six servers depend on one engineer.", "H", "M", "The PRD set itself is the mitigation. Add per-server READMEs and tests so a second engineer can pick one up."],
        ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"], "rows": [
            ["When will the two compromised Google service-account keys be rotated, and has Cloud audit logging been reviewed for misuse in the interim?", "Musfiqur Tuhin", "Open"],
            ["Should cp_uapi_call and wp_rest_request be kept as break-glass tools, restricted to an allowlist, or removed entirely?", "Musfiqur Tuhin", "Open"],
            ["What is the standard guard convention — a per-tool confirmation string, a server-level write-enable flag, or both depending on severity?", "Musfiqur Tuhin", "Open"],
            ["Do the unprefixed tools in google-search-console-mcp and mcp-meta-ads get renamed, and what is the deprecation window for the aliases?", "TBD — unassigned", "Open"],
            ["Who owns QA for this portfolio, given no QA lead is currently assigned?", "HaorGrix", "Open"],
            ["What retention period applies to the audit log once it covers all six servers, given it may contain client personal data?", "Musfiqur Tuhin", "Open"],
            ["Is client authorisation for automated operation of their properties explicit in current engagement terms?", "TBD — unassigned", "Open"],
        ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"], "rows": [
            ["2026-07-07", "Consolidate all MCP servers into one repository rather than one repository per server.", "Sets credential handling, gitignore discipline, and release process once. The servers share an audience and a maintainer, and per-repo overhead would exceed the isolation benefit.", "Musfiqur Tuhin"],
            ["2026-07-21", "Rewrite the Meta Ads server as v2 instead of patching v1.", "v1 lacked pagination and complete insights coverage, and had no write guard. The surface area of the fix approached a rewrite.", "Musfiqur Tuhin"],
            ["2026-07-22", "Rewrite git history to purge the two committed service-account keys, rather than pushing as-is and rotating.", "Removes the secret from every commit before it reaches a hosted remote. Backup taken first; the four-commit history was preserved.", "Musfiqur Tuhin"],
            ["2026-07-22", "Keep Meta Ads v1 in archive/ rather than deleting it.", "Preserves the reference implementation for comparison without implying it is maintained.", "Musfiqur Tuhin"],
            ["2026-07-22", "Publish the monorepo as private, not public.", "It targets HaorGrix-specific operational platforms and client properties; there is no case for public distribution.", "Musfiqur Tuhin"],
        ]},

        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "para", "text": "Public MCP servers exist for several of these platforms — WordPress, Google Analytics, and Google Search Console all have community implementations, and Meta publishes its own Graph API tooling. They were not adopted for three reasons. First, coverage: the public servers implement a generic subset, whereas the HaorGrix servers implement the specific operations this business actually performs, such as Elementor CSS regeneration, multi-layer cache purging, and CTR-rescue analysis. Second, trust: these tools hold production credentials for client properties, and a third-party dependency in that position is a supply-chain exposure. Third, composability: the cross-server integration between cpanel-mcp and wordpress-mcp via the Agent Cache Control mu-plugin only works because both sides are owned."},
        {"kind": "para", "text": "The trade-off accepted is maintenance burden. A community server has more contributors than one engineer, and the portfolio's largest risk (section 13.1) is exactly that concentration."},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"], "rows": [
            ["MCP", "Model Context Protocol — an open protocol through which AI applications discover and invoke external tools."],
            ["stdio transport", "MCP carried over a child process's standard input and output, as opposed to HTTP or SSE. Requires client and server on the same machine."],
            ["Tool", "A named, JSON-schema-typed operation a server exposes. The unit of capability an agent selects and calls."],
            ["Read / write classification", "Whether a tool only retrieves data or mutates state on the upstream platform. Write tools are the ones requiring guards."],
            ["Escape hatch", "A tool accepting an arbitrary upstream call — cp_uapi_call, wp_rest_request. Maximally flexible and entirely unguarded."],
            ["Guard / gate", "A precondition on a destructive tool: a literal confirmation string the caller must repeat, or a server-level flag such as META_ALLOW_WRITES."],
            ["Dry-run", "A mode in which a write tool validates and reports what it would do without issuing the mutating upstream call. Implemented in brevo-mcp."],
            ["UAPI", "cPanel's User API, the interface cpanel-mcp wraps."],
            ["Application Password", "A WordPress credential for REST authentication. Carries the full privileges of its user and cannot be scoped per capability."],
            ["mu-plugin", "A WordPress must-use plugin, loaded automatically and not deactivatable from the admin UI. The Agent Cache Control helper is installed this way."],
            ["Apple MPP", "Apple Mail Privacy Protection, which pre-fetches images and inflates reported email open rates. brevo_campaign_report corrects for it."],
            ["BUC throttling", "Business Use Case rate limiting on the Meta Graph API, applied per ad account rather than per application."],
        ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": "Tool counts by server, totalling 161:"},
        {"kind": "table", "header": ["Server", "Path", "Tools", "Language", "Tests", "Write guard"], "rows": [
            ["Brevo", "brevo-mcp/", "21", "TypeScript", "Yes", "Dry-run, sender lock, confirm strings"],
            ["cPanel", "cpanel-mcp/", "51", "TypeScript", "No", "None"],
            ["Google Analytics", "google-analytics-mcp/", "18", "TypeScript", "No", "None"],
            ["Google Search Console", "google-search-console-mcp/", "10", "TypeScript", "No", "None"],
            ["Meta Ads", "mcp-meta-ads_new/", "12", "JavaScript", "No", "META_ALLOW_WRITES"],
            ["WordPress", "wordpress-mcp/", "49", "TypeScript", "No", "None"],
        ]},
        {"kind": "bullets", "items": [
            "Per-server PRDs, which carry the complete tool-by-tool inventory: 01-Brevo-MCP-PRD.docx, 02-cPanel-MCP-PRD.docx, 03-Google-Analytics-MCP-PRD.docx, 04-Google-Search-Console-MCP-PRD.docx, 05-Meta-Ads-MCP-PRD.docx, 06-WordPress-MCP-PRD.docx.",
            "These documents are generated from source. To regenerate after editing content: python3 documentation/PRD/_build/build.py",
            "Model Context Protocol specification: https://modelcontextprotocol.io",
            "Repository: https://github.com/HaorGrix/mcp-servers (private)",
        ]},
    ],
}
