"""PRD content module for the Meta Ads MCP server (v2)."""

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "Meta Ads MCP Server",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Summary"], "rows": [
            ["0.1", "2026-07-22", "Musfiqur Tuhin", "Initial PRD written against mcp-meta-ads v2.0.0 as it exists in the monorepo."],
        ]},
        {"kind": "para", "text": "Status: Draft. Last updated 2026-07-22. Owner org: HaorGrix. Document owner: Musfiqur Tuhin."},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Sign-off"], "rows": [
            ["Document Owner", "Musfiqur Tuhin", "Scope, priorities, release decisions", "Pending"],
            ["Maintainer", "Musfiqur Tuhin", "Code, dependency upgrades, Graph API version bumps", "Pending"],
            ["Token / Business Manager owner", "TBD — who owns the Meta Business Manager system user", "Issues and rotates META_ACCESS_TOKEN, controls account access", "Pending"],
            ["Ad spend accountable owner", "TBD — who signs off on enabling META_ALLOW_WRITES", "Approves any environment in which write tools are registered", "Pending"],
        ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Source: HaorGrix/mcp-servers (private monorepo), branch main, folder Tooling/MCP/mcp-meta-ads_new/.",
            "Deprecated predecessor: archive/mcp-meta-ads-v1-deprecated/ (retained for reference only).",
            "Server README.md — tool tables, environment variables, write-gate behaviour.",
            "Meta Marketing API reference (Graph API v23.0) and Meta access-token / rate-limit documentation.",
            "Model Context Protocol specification (stdio transport, tools capability).",
        ]},

        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "Meta ad account data lives behind the Graph API: cursor-paginated edges, a large and awkward field vocabulary, an insights endpoint with its own level/breakdown grammar, and an error model that mixes transient throttling with permanent failures. Analysts and agents working on client campaigns cannot read that data without hand-rolling HTTP calls, and any tooling that does reach the API is one careless call away from creating or activating objects that spend real money."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": "mcp-meta-ads v2.0.0 is a Node ESM MCP server on stdio that exposes 12 tools over the Meta Marketing API: 8 read tools and 4 write tools. Reads follow paging.next to exhaustion, report how many pages were fetched, and flag truncation explicitly. Every request retries with bounded exponential backoff on the Graph error codes and HTTP statuses that are genuinely transient. The 4 write tools are only registered when META_ALLOW_WRITES=true; in the default configuration they do not exist in the tool list at all, so an agent cannot call them."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "v1 (now archive/mcp-meta-ads-v1-deprecated/) was a thin wrapper: it returned page one of each edge with no cursor following, covered only a subset of insights parameters, and had no write capability or write guard. Silent single-page results were the decisive defect — reports built on them were wrong in a way that looked correct."},
        {"kind": "para", "text": "v2 is a full rewrite rather than an increment. It introduces a separate Graph data layer (src/graph.js) that knows nothing about MCP, full cursor pagination with an explicit truncated flag, the complete insights surface (levels, date presets, explicit since/until windows, time_increment, breakdowns, action_breakdowns, filtering, lite field set), and guarded writes that always create PAUSED objects. v1 is deprecated and receives no fixes."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "This server sits in the HaorGrix MCP tooling monorepo alongside the analytics and marketing connectors (Google Analytics, Google Search Console, Brevo). Together they let an agent assemble a paid-plus-organic picture of a client without a human exporting spreadsheets. Meta Ads is the only paid-media source in the set, and along with brevo-mcp it is one of only two servers in the monorepo that can mutate an external system — which is why it is also one of only two carrying an explicit write guard."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Remove manual Ads Manager exports from campaign reporting and audit work.",
            "Make complete-by-default reads the norm, so agent-authored analysis is not quietly built on page one.",
            "Keep spend authority in human hands: write tools are absent unless an operator deliberately turns them on, and created objects are always PAUSED.",
            "Absorb Graph API transience (throttling, 5xx, timeouts) in one place instead of in every caller.",
        ]},

        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "G1 — All 12 tools operate against a live Meta ad account with a system-user token by the end of the current maintenance cycle, with no unhandled rejection reaching the transport.",
            "G2 — Every list-style read returns the full edge, or sets truncated=true, in 100% of responses; no response ever omits rows without saying so.",
            "G3 — Zero unintended ad spend attributable to this server: no ACTIVE object created or activated without an operator having explicitly set META_ALLOW_WRITES=true.",
            "G4 — Transient Graph failures (codes 1, 2, 4, 17, 32, 341, 613; HTTP 429/500/502/503/504) are absorbed by retry rather than surfaced, up to META_MAX_RETRIES attempts.",
            "G5 — Graph API version bumps are a single environment-variable change (META_API_VERSION), requiring no code edit, ahead of each roughly two-year Meta deprecation.",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"], "rows": [
            ["Tool call success rate", "Not measured", "≥ 98% non-error results excluding caller-argument mistakes", "Manual review of stderr log and returned isError payloads"],
            ["Truncated responses on real accounts", "Unknown (META_MAX_PAGES default 200 pages × 200 rows)", "0 truncated=true on routine reporting accounts", "Inspect truncated flag in tool output"],
            ["Unintended writes", "0 (writes unregistered by default)", "0", "Meta Business Manager change log review"],
            ["Retry-absorbed failures", "Not measured", "Transient failures never surface as tool errors within the retry budget", "stderr inspection during long snapshot runs"],
            ["Time to produce an account audit", "Manual export, ~30–60 min", "Single get_account_snapshot call", "Wall-clock comparison"],
            ["Graph version currency", "v23.0", "Never more than one Meta-supported version behind", "Quarterly check against Meta changelog"],
        ]},
        {"kind": "meta", "text": "Baselines are honest gaps: this server emits no metrics of its own, so every KPI above is measured by manual inspection today."},
        {"kind": "h2", "text": "3.3 Non-Goals"},
        {"kind": "bullets", "items": [
            "Not a budget optimiser or bid-management system; it does not decide anything about spend.",
            "No HTTP/SSE transport — stdio only, single local process per client.",
            "No caching, no local persistence, no database; every call hits Graph.",
            "No OAuth flow; the token is supplied out of band and never minted or refreshed by this server.",
            "No creative asset upload, no image/video hosting, no audience or pixel management.",
            "No delete tools; objects can be created and status-changed but not removed.",
            "No TypeScript, no build step, no test suite in this version (recorded as a risk, not a feature).",
        ]},

        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"], "rows": [
            ["Persona", "AI coding/analysis agent (Claude via Claude Code or another MCP client)"],
            ["Access", "Local stdio subprocess, registered in ~/.claude.json as meta-ads"],
            ["Goal", "Read campaign structure and performance to answer questions and draft reports; occasionally scaffold PAUSED campaign objects when authorised"],
            ["Inputs it can supply", "Ad account ids (act_<digits>), node ids, date presets or since/until windows, levels, breakdowns, field overrides"],
            ["Affordance", "Tool name plus description string only — there is no UI and no documentation the agent can consult mid-call"],
            ["Failure tolerance", "Low; a misleading empty or truncated result silently corrupts downstream analysis"],
            ["Constraint", "Cannot see the environment, so it cannot know whether writes are enabled except by the tool list it receives"],
        ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "Performance marketer / account manager at HaorGrix — consumes the agent's output, owns the client relationship and the spend, and is the person harmed by a truncated or stale read.",
            "Maintainer / engineer — runs npm run check, bumps META_API_VERSION, adds fields, debugs Graph errors from stderr trace ids.",
            "Business Manager administrator — issues the system-user token with ads_read (and ads_management where writes are intended), and revokes it on offboarding.",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an agent, I want to list every ad account my token reaches, so I can pick the right act_ id without the operator pasting one.",
            "As an agent, I want campaigns, ad sets, ads and creatives for an account fully paginated, so my structural summary is complete.",
            "As an agent, I want to know when a result was cut short, so I can tell the operator instead of reporting a partial list as whole.",
            "As an agent, I want insights at account, campaign, adset or ad level with a date range and optional daily rows and breakdowns, so I can compute trends and segment performance.",
            "As an agent, I want one call that returns structure plus insights for an account, so an audit does not take a dozen round trips.",
            "As a marketer, I want write tools to be invisible unless someone deliberately enabled them, so no agent can spend my client's money by accident.",
            "As a marketer, I want anything the server creates to arrive PAUSED, so a human reviews before delivery starts.",
            "As a maintainer, I want the server to refuse to start without a real token, so failures are boot-time and legible rather than a confusing OAuth error on the first call.",
            "As a maintainer, I want to change Graph API version by environment variable, so Meta's deprecation cycle is a config change.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"], "rows": [
            ["FR-1", "Account discovery and detail: list_ad_accounts, get_ad_account", "Must", "list_ad_accounts returns every account on me/adaccounts with status, currency and lifetime spend; get_ad_account returns balance, spend cap, funding source and timezone for one act_ id"],
            ["FR-2", "Campaign, ad set, ad and creative enumeration: list_campaigns, list_adsets, list_ads, list_creatives", "Must", "Each returns the full edge with its default field set; list_campaigns accepts an effective_status filter; list_adsets and list_ads accept an account, campaign or ad set parent; all accept a comma-separated fields override"],
            ["FR-3", "Insights: get_insights", "Must", "Supports level (account/campaign/adset/ad), date_preset or paired since/until, time_increment, breakdowns, action_breakdowns, filtering, and a lite field set; rejects unknown levels and presets, and rejects since without until"],
            ["FR-4", "Single-call account audit: get_account_snapshot", "Must", "Returns account detail, campaigns, ad sets, ads, creatives and insights for one account in a single response"],
            ["FR-5", "Exhaustive cursor pagination", "Must", "paginate() follows paging.next until exhausted, returning {data, pages, truncated}; truncated is true if and only if META_MAX_PAGES was reached with a next cursor still present"],
            ["FR-6", "Bounded retry with jittered exponential backoff", "Must", "Retries Graph codes 1/2/4/17/32/341/613 and HTTP 429/500/502/503/504 up to META_MAX_RETRIES; backoff 500ms doubling plus up to 250ms jitter; non-retryable Graph errors throw immediately"],
            ["FR-7", "Write gate", "Must", "When META_ALLOW_WRITES is not exactly \"true\", the 4 write tools are not registered and do not appear in tools/list; calling one returns an unknown-tool error that names the flag"],
            ["FR-8", "Guarded object creation: create_campaign, create_adset, create_ad", "Should", "Each creates the object in PAUSED state; ad sets take caller-supplied targeting; ads require an existing creative_id"],
            ["FR-9", "Status mutation: update_status", "Should", "Sets ACTIVE/PAUSED/ARCHIVED (and equivalent) on a campaign, ad set or ad; description states plainly that ACTIVE can start spending"],
            ["FR-10", "Fail-fast configuration", "Must", "loadConfig() throws at boot on a missing or placeholder META_ACCESS_TOKEN, on a META_API_VERSION not matching v<major>.<minor>, and on any non-positive-integer numeric setting"],
            ["FR-11", "Argument validation before network", "Must", "Ad account ids must match act_<digits>; node ids must be alphanumeric/underscore; violations raise a GraphError with the offending value before any HTTP call"],
            ["FR-12", "Legible error results", "Must", "Graph failures return isError with the tool name, Graph message, code/subcode where present, and fbtrace_id where present; unhandled rejections are logged to stderr, not thrown at the transport"],
            ["FR-13", "Startup diagnostics on stderr", "Should", "On connect the server logs Graph version, registered tool count, and whether writes are ENABLED or disabled"],
        ]},
        {"kind": "para", "text": "Complete tool inventory — 12 tools (8 read, 4 write):"},
        {"kind": "table", "header": ["Tool", "Class", "Purpose"], "rows": [
            ["list_ad_accounts", "Read", "Every account the token reaches: status, currency, lifetime spend"],
            ["get_ad_account", "Read", "One account: balance, spend cap, funding source, timezone"],
            ["list_campaigns", "Read", "All campaigns, paginated; budgets, objective, schedule; optional effective_status filter"],
            ["list_adsets", "Read", "Ad sets for an account or one campaign, including full targeting specs"],
            ["list_ads", "Read", "Ads for an account, campaign or ad set"],
            ["list_creatives", "Read", "Headlines, body copy, CTAs, image/video refs, story specs"],
            ["get_insights", "Read", "Performance at any level with date ranges, daily rows and breakdowns"],
            ["get_account_snapshot", "Read", "One-shot audit: structure plus insights in a single call"],
            ["create_campaign", "Write (gated)", "Creates a PAUSED campaign"],
            ["create_adset", "Write (gated)", "Creates a PAUSED ad set with caller-supplied targeting"],
            ["create_ad", "Write (gated)", "Creates a PAUSED ad from an existing creative_id"],
            ["update_status", "Write (gated)", "Sets delivery status on a campaign, ad set or ad; ACTIVE can start spending"],
        ]},
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Boot: MCP client spawns node index.js → dotenv loads .env → loadConfig() validates token, API version and numeric settings, throwing on failure → GraphClient constructed → read tools registered, write tools registered only if allowWrites → stdio transport connected → one-line status written to stderr.",
            "Read call: client sends tools/call → handler validates arguments locally → paginate() issues the first request with limit=META_PAGE_LIMIT → follows paging.next, retrying transient failures → returns {data, pages, truncated} → serialised as pretty JSON text content.",
            "Truncation: page count reaches META_MAX_PAGES while a next cursor remains → paginate returns immediately with truncated=true, and that flag is part of the JSON the agent receives, so the shortfall is visible rather than silent.",
            "Error: non-retryable Graph error, or retry budget exhausted → GraphError propagates to index.js → returned as isError content naming the tool, message, code/subcode and fbtrace_id.",
            "Write (enabled): operator sets META_ALLOW_WRITES=true and restarts → the 4 write tools appear in tools/list → create_* produces PAUSED objects → a human reviews in Ads Manager → update_status ACTIVE is the single deliberate step that begins spending.",
            "Write (default): tools/list contains 8 tools; any create_* call fails as unknown tool, with a hint naming META_ALLOW_WRITES.",
        ]},

        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"], "rows": [
            ["Performance", "Per-request timeout META_TIMEOUT_MS (default 60,000 ms). Page size META_PAGE_LIMIT (default 200). Latency is dominated by Graph and by page count; get_account_snapshot issues many paginated calls and is expected to be the slowest tool by a wide margin."],
            ["Scalability", "Single-process, single-token, one client per process. Bounded by META_MAX_PAGES (default 200 pages) per edge. No concurrency control beyond what the MCP client imposes; parallel callers share the same per-app and per-ad-account rate budget."],
            ["Availability", "Availability equals Meta Graph availability. Transient failures (codes 1, 2, 4, 17, 32, 341, 613; HTTP 429/500/502/503/504) are retried up to META_MAX_RETRIES (default 4) with jittered exponential backoff. There is no circuit breaker and no fallback data source."],
            ["Security", "META_ACCESS_TOKEN is read from the environment/.env and sent as a Bearer header; it is never logged and is stripped from paging.next URLs before reuse. Boot fails on the placeholder token value. Writes require a deliberate META_ALLOW_WRITES=true. Token scope should be the minimum needed: ads_read for read-only deployments, ads_management only where writes are intended."],
            ["Privacy / Compliance", "Handles client advertising performance and account financial data (balance, spend cap, funding source) belonging to third parties. No end-user personal data is fetched, but demographic breakdowns return aggregate audience segments. No data is persisted by the server; retention is entirely the MCP client's transcript."],
            ["Accessibility", "N/A — no human-facing UI. Operator-facing output is plain text on stdout/stderr and is screen-reader compatible by construction."],
            ["Observability", "One stderr line at startup (Graph version, tool count, write state); errors returned to the caller carry Graph code, subcode and fbtrace_id. There is no structured logging, no metrics, no tracing, and no per-request log. Insufficient for unattended operation — recorded as a risk."],
            ["Localization", "N/A — no user-facing copy to translate. Tool descriptions and errors are English only. Monetary values are returned in each account's own currency and in Meta's minor-unit convention; the server does not convert or format them, so callers must not assume USD."],
        ]},

        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "bullets", "items": [
            "Plain Node ESM JavaScript, no TypeScript and no build step. Engines: node >= 18 (native fetch and AbortController are required). Roughly 695 lines across five files.",
            "index.js — MCP server wiring, tool registry, ListTools/CallTool handlers, error formatting, stdio transport.",
            "src/config.js — environment parsing and fail-fast validation; produces the single Config object.",
            "src/graph.js — GraphClient and GraphError: retry, cursor pagination, error normalisation. Contains no MCP concepts.",
            "src/tools.js — tool definitions with hand-written JSON Schema, argument validation, and handlers; readTools() and writeTools() are separate exports.",
            "src/fields.js — default field sets and enumerations (account, campaign, adset, ad, creative, insights full and lite, insight levels, date presets).",
            "Dependencies: @modelcontextprotocol/sdk ^1.29.0 (the newest SDK version in the monorepo) and dotenv ^17.4.2. No zod; input schemas are hand-written JSON Schema objects, so arguments are validated by hand in the handlers rather than by a schema library.",
            "Scripts: start (node index.js) and check (node --check per file, a syntax pass only). There is no test script and no tests.",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "bullets", "items": [
            "Base URL https://graph.facebook.com/${META_API_VERSION}, default v23.0. Auth is an Authorization: Bearer header.",
            "Read edges: me/adaccounts, act_<id>, act_<id>/campaigns, /adsets, /ads, /adcreatives, and <node>/insights at account, campaign, adset and ad level.",
            "Writes are POSTs with a JSON body to the corresponding creation edges, and to the node itself for update_status.",
            "Pagination contract returned to callers: {data: [...], pages: <int>, truncated: <bool>}. requestAbsolute() re-fetches paging.next by parsing its query string and deleting any access_token it carries, so the configured credential is always the one used.",
            "No local schema, cache or storage. All responses are serialised to pretty-printed JSON in a single text content block, which means very large snapshots produce very large messages.",
        ]},
        {"kind": "h2", "text": "7.3 Integrations"},
        {"kind": "table", "header": ["Dependency", "Owner", "Type", "Status"], "rows": [
            ["Meta Marketing / Graph API v23.0", "Meta Platforms", "External REST API", "Live; version pinned by META_API_VERSION"],
            ["Meta system-user access token", "TBD — Business Manager owner", "Credential", "Required; boot fails without it"],
            ["@modelcontextprotocol/sdk ^1.29.0", "Anthropic / MCP", "npm dependency", "Active; newest SDK pin in the monorepo"],
            ["dotenv ^17.4.2", "Open source", "npm dependency", "Active"],
            ["Node.js >= 18 runtime", "Node.js project", "Runtime", "Required for global fetch/AbortController"],
            ["MCP client (Claude Code)", "Anthropic", "Host process", "Registered as meta-ads in ~/.claude.json"],
            ["archive/mcp-meta-ads-v1-deprecated/", "HaorGrix", "Superseded code", "Deprecated; reference only, unmaintained"],
        ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "Meta access tokens expire: long-lived user tokens last roughly 60 days; system-user tokens do not expire, which is why system-user tokens are the assumed deployment.",
            "Meta rate limits per app and per ad account, with Business Use Case throttling that tightens as spend and call volume rise. The retry policy absorbs throttling but cannot create headroom; get_account_snapshot on a large account is the likeliest trigger.",
            "Meta deprecates Graph API versions on roughly a two-year cycle, hence META_API_VERSION being configurable rather than hard-coded.",
            "META_MAX_PAGES caps results. Very large accounts can therefore be returned incomplete; the code does set truncated=true so the caller can see it, but nothing forces the caller to act on that flag.",
            "Tool names are not namespaced with a server prefix. list_campaigns, list_ads and get_insights are generic enough to collide with another mounted server (the same issue exists in google-search-console-mcp).",
            "Being plain JavaScript, there is no typecheck beyond node --check, which only verifies syntax. JSDoc annotations exist but are not enforced.",
            "Assumes a single Business Manager identity per process; multiple tokens require multiple server instances.",
            "Assumes the caller supplies valid Meta targeting specs for create_adset; the server does not validate targeting semantics.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "table", "header": ["Event", "Trigger", "Properties", "Destination"], "rows": [
            ["Startup line", "Successful transport connect", "Graph API version, registered tool count, writes ENABLED/disabled", "stderr"],
            ["Config failure", "Missing/placeholder token, malformed API version, non-positive integer setting", "Error message naming the offending variable", "stderr, process exit"],
            ["Tool error result", "GraphError or unexpected exception in a handler", "Tool name, Graph message, code/subcode, fbtrace_id", "MCP response (isError)"],
            ["Unhandled rejection", "Any unawaited promise rejection", "Reason message", "stderr"],
            ["Pagination outcome", "Every paginated read", "pages, truncated", "MCP response body (data, not telemetry)"],
        ]},
        {"kind": "meta", "text": "There is no telemetry pipeline. Everything above is either console output or part of the tool payload; nothing is aggregated or retained."},

        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "There is no graphical interface. The server is a headless stdio process whose only consumer is an AI agent, so \"design\" here means the shape of the tool surface the model reasons over."},
        {"kind": "bullets", "items": [
            "Tool naming: verb-first and predictable (list_*, get_*, create_*, update_*), which makes intent guessable from the name alone. The gap is namespacing — no meta_ prefix, so names can collide when several servers are mounted in one client. Adding a prefix is a breaking change and is tracked as an open question.",
            "Descriptions are the agent's only affordance. They carry the load a UI would: get_insights states the supported levels and that it is fully paginated; every write tool states in its own description that it creates PAUSED objects and requires META_ALLOW_WRITES=true; update_status states plainly that setting ACTIVE can start spending.",
            "Error legibility: failures come back as human-readable sentences naming the tool, the Graph message, the numeric code/subcode and the fbtrace_id, so an agent can distinguish a bad argument from a throttle, and an engineer can take the trace id to Meta support.",
            "Argument validation is deliberately pre-flight and specific: an ad_account_id that is not act_<digits> is rejected with the value quoted back, before any network call, which keeps correction cheap.",
            "Guard ergonomics: the write gate is enforced by absence, not refusal. When writes are off the tools are never registered, so the model never sees an affordance it cannot use and cannot be argued into trying. The cost is that an agent given a stale tool list gets an unknown-tool error rather than a permission error; the message compensates by naming META_ALLOW_WRITES.",
            "Output is pretty-printed JSON in one text block. Readable for a human skimming a transcript, but there is no summarisation, so a full snapshot of a large account is a very large message.",
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"], "rows": [
            ["M0 — v1 (deprecated)", "Single-page reads, partial insights, no writes", "Musfiqur Tuhin", "Complete; archived"],
            ["M1 — v2.0.0 rewrite", "Graph data layer, full pagination with truncation flag, complete insights surface, 12 tools, write gate", "Musfiqur Tuhin", "Complete (current state)"],
            ["M2 — Verification pass", "Exercise all 12 tools against a live account with a system-user token; confirm truncation behaviour on a large account", "Musfiqur Tuhin", "TBD"],
            ["M3 — Test suite", "Unit tests for config validation, paginate/truncation, retry classification; contract fixtures for tool schemas", "Musfiqur Tuhin", "TBD"],
            ["M4 — Namespacing decision", "Decide on a meta_ tool prefix and execute or reject the breaking change", "Musfiqur Tuhin", "TBD"],
            ["M5 — Graph version bump", "Move META_API_VERSION forward ahead of Meta's deprecation of v23.0", "Musfiqur Tuhin", "TBD — driven by Meta's schedule"],
        ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "bullets", "items": [
            "Local-only distribution: cloned from the monorepo and registered per developer machine in ~/.claude.json as meta-ads. There is no package publish and no server deployment.",
            "Default posture everywhere is read-only. META_ALLOW_WRITES stays unset on every machine unless a named person has approved writes for a specific piece of work.",
            "Writes, when enabled, are enabled temporarily and reverted afterwards; the flag is not a permanent setting.",
            "Rollback is git checkout of the previous commit plus a client restart; there is no state to migrate.",
        ]},
        {"kind": "h2", "text": "9.3 Effort & Timeline"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"], "rows": [
            ["v2 rewrite (delivered)", "Musfiqur Tuhin", "Complete", "Meta Marketing API access"],
            ["Live verification of 12 tools", "Musfiqur Tuhin", "0.5 day", "System-user token with ads_read"],
            ["Write-path verification on a sandbox account", "Musfiqur Tuhin", "0.5 day", "ads_management token, disposable ad account, spend approval"],
            ["Test suite (M3)", "Musfiqur Tuhin", "1–2 days", "Choice of runner (node:test is available without new deps)"],
            ["Tool namespacing (M4)", "Musfiqur Tuhin", "0.5 day", "Decision; coordination with any saved agent prompts"],
            ["Graph version bump (M5)", "Musfiqur Tuhin", "0.25 day plus regression check", "Meta changelog, field-set review"],
        ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "System-user token issued with the minimum scope for the intended mode and stored in .env, never in git.",
            ".env confirmed git-ignored; no token in the monorepo history.",
            "npm run check passes on all five files.",
            "Server boots and logs the expected Graph version, tool count and write state.",
            "Read tools verified against at least one live account, including one large enough to test the truncated flag.",
            "META_ALLOW_WRITES confirmed unset in the default developer configuration; tools/list shows 8 tools.",
            "Write path, if enabled, verified only on a disposable account, with a named owner accountable for spend.",
            "Escalation path documented for token expiry and Graph deprecation notices.",
        ]},

        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"], "rows": [
            ["Document owner / maintainer", "Musfiqur Tuhin", "Ad hoc; no dedicated allocation"],
            ["Business Manager / token admin", "TBD — Business Manager owner", "On request (issuance, rotation, revocation)"],
            ["Spend-accountable approver", "TBD — approver for META_ALLOW_WRITES", "Per write-enabled engagement"],
            ["Reviewer", "TBD — second engineer for write-path changes", "Per pull request touching src/tools.js writes"],
        ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "The Meta Marketing API has no per-call fee; the direct software cost of this server is zero.",
            "The material cost exposure is ad spend. create_* plus update_status ACTIVE can begin real delivery against a client budget. This is the single largest financial risk in the monorepo and the reason for the write gate.",
            "Rate-limit cost is real if not monetary: an aggressive snapshot loop can exhaust a client's Business Use Case budget and degrade other tooling on the same app.",
            "Engineering cost is recurring but small: Graph version bumps roughly every two years, token rotation if a user token is ever used instead of a system-user token, and SDK upgrades.",
            "No infrastructure cost — the process runs on the developer's machine for the life of the MCP client session.",
        ]},

        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "bullets", "items": [
            "Owned by HaorGrix; maintained by Musfiqur Tuhin. There is no on-call rotation and no SLA.",
            "Runs as a child process of the MCP client; lifecycle, restart and crash handling belong to the client.",
            "Operational signal is limited to the startup stderr line and the error text returned to the caller.",
            "Meta account access and token lifecycle are owned by the Business Manager administrator, not by this repository.",
        ]},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "bullets", "items": [
            "README.md in the server folder is the primary reference: tool tables split by read/write, environment variables, and write-gate semantics.",
            "Common failure modes and their signatures: missing or placeholder token fails at boot with an explicit message; an expired token surfaces as a Graph OAuth error code; throttling surfaces as retries and, once the budget is exhausted, as a failed-after-N-attempts error; a malformed account id is rejected locally before any call.",
            "Diagnostics: quote the fbtrace_id from the error result when escalating to Meta. Run npm run check after any edit.",
            "Support is best-effort through the maintainer; there is no ticket queue.",
        ]},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "v1 is deprecated. It lives at archive/mcp-meta-ads-v1-deprecated/ for reference only, receives no fixes, and must not be registered in any MCP client. Its single-page reads are the specific defect that makes it unsafe: results looked complete and were not.",
            "v2.0.0 supersedes it entirely and is the only supported copy. The rewrite added exhaustive pagination with an explicit truncation flag, the full insights surface, and guarded writes.",
            "Meta deprecates Graph API versions on roughly a two-year cycle. META_API_VERSION must be reviewed quarterly and moved forward before v23.0 is retired; field sets in src/fields.js should be re-checked at each bump because field availability changes between versions.",
            "Dependency maintenance: track @modelcontextprotocol/sdk (currently the newest pin in the monorepo, so this server is the canary for SDK breakage) and dotenv.",
            "Deprecation criteria for v2 itself: replace or retire if Meta ships an official MCP server, or if the monorepo consolidates onto a shared typed HTTP client, at which point this document is superseded rather than amended.",
        ]},

        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "table", "header": ["Area", "Consideration", "Owner or Status"], "rows": [
            ["Meta Platform Terms", "Use of the Marketing API is bound by Meta's Platform Terms and Developer Policies, including restrictions on data retention and on use of advertising data outside the permitted purposes", "Musfiqur Tuhin — reviewed at integration; no re-review scheduled"],
            ["Client data ownership", "All campaign, spend and performance data belongs to the client whose ad account is queried; HaorGrix accesses it as a service provider", "Account manager for each engagement"],
            ["Authorisation to access", "Access must be granted through the client's Business Manager; token scope should be the minimum required", "TBD — Business Manager owner"],
            ["Spend authority", "Creating or activating ad objects commits a client's budget; contractual authority to do so is separate from technical capability", "TBD — spend-accountable approver; blocking prerequisite for enabling writes"],
            ["Credential handling", "META_ACCESS_TOKEN lives in .env only, never in git, never logged, stripped from paging URLs before reuse", "Enforced in code and by .gitignore"],
            ["Personal data / GDPR", "No individual-level personal data is retrieved; demographic breakdowns are aggregate segments. The server stores nothing", "Low exposure; not formally assessed"],
            ["Data residency", "Data transits from Meta to the developer machine and into the MCP client transcript; residency of that transcript is the client's concern, not this server's", "Open — depends on MCP client configuration"],
            ["Licensing", "Declared ISC in package.json; dependencies are permissively licensed. Internal use only, not distributed", "No conflict identified"],
            ["Audit trail", "Object creation and status changes appear in the Meta Business Manager change log attributed to the token's system user; the server itself keeps no audit log", "Gap — recorded as a risk"],
        ]},

        {"kind": "break"},
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"], "rows": [
            ["Unintended ad spend: an agent creates and activates objects against a live client account", "Low", "Critical", "Write tools are not registered unless META_ALLOW_WRITES=true, so by default they do not exist in the tool list; created objects are always PAUSED, making activation a separate deliberate act; update_status states in its description that ACTIVE can start spending. Residual: once the flag is on for a session, nothing further stands between the agent and update_status ACTIVE — no per-call confirmation, no spend ceiling, no dry run. Enable only on disposable accounts with a named approver, and revert the flag afterwards."],
            ["Silent truncation on large accounts: META_MAX_PAGES (default 200) stops pagination", "Medium", "High", "paginate() returns truncated=true and the page count in the payload, so the shortfall is visible to the caller — the code does signal it. But nothing enforces that the agent reads the flag, and get_account_snapshot buries several such flags in one large object. Mitigation: raise META_MAX_PAGES for large accounts and treat truncated=true as a hard stop in reporting workflows."],
            ["Tool-name collision: names are not namespaced (no meta_ prefix)", "Medium", "Medium", "Same defect as google-search-console-mcp. list_campaigns, list_ads and get_insights are plausible names for other connectors; a collision silently routes calls to the wrong server. Mitigation: avoid mounting overlapping servers together until the namespacing decision (M4) is made."],
            ["No tests: npm run check is node --check, a syntax pass only", "High", "High", "Nothing verifies retry classification, truncation logic, or argument validation. A regression in paginate() would reintroduce the exact v1 defect undetected. Mitigation: M3 test suite using node:test."],
            ["No typecheck: plain JavaScript with unenforced JSDoc", "High", "Medium", "Field-name and shape errors surface only at runtime, as a Graph error or an undefined. Mitigation: checkJs via a jsconfig, or migration to TypeScript, both deferred."],
            ["Token expiry or revocation", "Medium", "High", "Long-lived user tokens expire in roughly 60 days; system-user tokens do not. Mitigation: deploy with a system-user token; boot-time validation catches an absent token, though an expired one only surfaces on the first call as a Graph OAuth error."],
            ["Rate limiting / BUC throttling under snapshot load", "Medium", "Medium", "Retry with jittered exponential backoff absorbs bursts up to META_MAX_RETRIES; beyond that the call fails with a clear message. No client-side rate limiter exists. Mitigation: avoid parallel snapshots against one account."],
            ["Graph API version deprecation (roughly two-year cycle)", "High over time", "High", "META_API_VERSION is configurable and validated by pattern, so a bump is a config change. Mitigation: quarterly review plus a field-set re-check at each bump."],
            ["Oversized responses: full snapshots serialise to one large JSON text block", "Medium", "Medium", "No summarisation or field trimming by default. Mitigation: use the fields override and INSIGHTS_FIELDS_LITE, and prefer narrower tools over get_account_snapshot on large accounts."],
            ["Hand-written JSON Schema with no schema library", "Medium", "Medium", "Validation is manual inside handlers, so an unchecked argument reaches Graph unvalidated. Account and node ids are checked; targeting specs and creative payloads are not. Mitigation: tests, or adopt zod as other servers in the monorepo do."],
            ["No server-side audit log of writes", "Medium", "Medium", "Attribution relies on the Meta Business Manager change log against the system user, which cannot distinguish which agent or session acted. Mitigation: use a dedicated system user for write-enabled work."],
            ["Credential leakage into transcripts", "Low", "High", "The token is never logged and is stripped from paging.next URLs, but account financial detail (balance, spend cap, funding source) does land in the MCP client transcript. Mitigation: treat transcripts as client-confidential."],
        ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"], "rows": [
            ["Do we namespace tools with a meta_ prefix, accepting the breaking change, or accept collision risk?", "Musfiqur Tuhin", "Open"],
            ["Should writes require a per-call confirmation token or a spend ceiling in addition to META_ALLOW_WRITES?", "Musfiqur Tuhin + spend approver", "Open"],
            ["Should truncated=true be escalated to an error or a warning banner rather than a quiet field?", "Musfiqur Tuhin", "Open"],
            ["Which token identity do we standardise on, and who rotates it?", "TBD — Business Manager owner", "Open"],
            ["Do we adopt zod for schemas to match the rest of the monorepo, or keep hand-written JSON Schema?", "Musfiqur Tuhin", "Open"],
            ["Is a delete/archive capability wanted, or is update_status ARCHIVED sufficient?", "Musfiqur Tuhin", "Open"],
            ["When is v1 physically deleted from archive/ rather than merely deprecated?", "Musfiqur Tuhin", "Open"],
            ["Who is accountable if an agent-created campaign spends against a client budget?", "TBD — spend-accountable approver", "Open — blocking for any write-enabled engagement"],
        ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"], "rows": [
            ["TBD — v2 rewrite date", "Rewrite v1 rather than patch it", "Single-page reads were a correctness defect running through the whole design; incremental fixes would have left the same shape", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Gate writes behind META_ALLOW_WRITES by not registering the tools at all", "Absence is a stronger guard than refusal: the model never sees an affordance it should not use", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Always create PAUSED objects", "Separates creation from spending, so activation is a distinct human-reviewable act", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Return {data, pages, truncated} rather than a bare array", "Makes incompleteness visible to the caller instead of silent", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Keep src/graph.js free of MCP concepts", "Data layer stays testable and reusable independently of the transport", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Plain JavaScript, no build step; hand-written JSON Schema, no zod", "Lowest friction for a local stdio tool; accepted cost is no typecheck and manual validation", "Musfiqur Tuhin"],
            ["TBD — v2 rewrite date", "Make META_API_VERSION configurable and pattern-validated", "Meta deprecates versions on roughly a two-year cycle; a bump should not require a code change", "Musfiqur Tuhin"],
            ["2026-07-22", "Document the server at its actual state, including no tests, no typecheck and unnamespaced tools", "PRD is a working record, not a pitch", "Musfiqur Tuhin"],
        ]},

        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "bullets", "items": [
            "Meta publishes no first-party MCP server for the Marketing API; if one appears it would likely supersede this work (see 11.3).",
            "Community Meta Ads MCP servers exist, mostly Python and mostly read-only. The differentiators here are the explicit truncation contract and the write gate; the disadvantages are no tests and no published package.",
            "The alternative is direct Graph calls or the official SDKs, which gives full coverage but pushes pagination, retry and guard logic into every caller — the situation this server exists to remove.",
            "Within the monorepo, this and brevo-mcp are the only servers with a write guard, and this one is the only paid-media source.",
        ]},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"], "rows": [
            ["MCP", "Model Context Protocol — the JSON-RPC protocol by which an AI client discovers and calls tools"],
            ["stdio transport", "MCP transport where the server is a child process communicating over stdin/stdout"],
            ["Graph API", "Meta's HTTP API; the Marketing API is the advertising surface of it"],
            ["act_<id>", "Meta ad account identifier format; validated by regex before any request"],
            ["Edge", "A collection under a Graph node, e.g. act_123/campaigns"],
            ["paging.next", "Cursor URL Meta returns for the following page; followed until exhausted or META_MAX_PAGES is reached"],
            ["truncated", "Boolean in every paginated response; true when the page cap was hit with a next cursor still present"],
            ["Insights", "Meta's performance-reporting endpoint, queryable at account, campaign, adset or ad level"],
            ["Breakdown", "Insights dimension that splits rows by segment (age, placement, device, and similar)"],
            ["time_increment", "Insights parameter producing per-period rows, typically daily"],
            ["date_preset", "Named relative window (e.g. maximum, last_30d) validated against DATE_PRESETS"],
            ["Effective status", "Meta's computed delivery status of an object, distinct from its configured status"],
            ["System user", "Non-human Business Manager identity whose access token does not expire"],
            ["BUC throttling", "Business Use Case rate limiting, scaled to an ad account's activity and spend"],
            ["fbtrace_id", "Per-request identifier Meta returns; quoted when escalating to Meta support"],
            ["Write gate", "META_ALLOW_WRITES=true; without it the 4 write tools are never registered"],
            ["PAUSED", "Delivery status in which an object exists but does not spend"],
        ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": "Environment variables:"},
        {"kind": "table", "header": ["Variable", "Default", "Purpose"], "rows": [
            ["META_ACCESS_TOKEN", "none — required", "Meta access token; boot fails if absent or left as the placeholder value"],
            ["META_API_VERSION", "v23.0", "Graph API version; must match v<major>.<minor>"],
            ["META_TIMEOUT_MS", "60000", "Per-request abort timeout"],
            ["META_MAX_RETRIES", "4", "Retry attempts after the first try, for retryable codes and statuses"],
            ["META_PAGE_LIMIT", "200", "Rows requested per Graph page"],
            ["META_MAX_PAGES", "200", "Page cap per edge; hitting it sets truncated=true"],
            ["META_ALLOW_WRITES", "unset (false)", "Must be exactly \"true\" for the 4 write tools to be registered"],
        ]},
        {"kind": "para", "text": "Tool inventory by class — 12 tools total. Read (8, always registered): list_ad_accounts, get_ad_account, list_campaigns, list_adsets, list_ads, list_creatives, get_insights, get_account_snapshot. Write (4, registered only when META_ALLOW_WRITES=true): create_campaign, create_adset, create_ad, update_status."},
        {"kind": "bullets", "items": [
            "Repository: HaorGrix/mcp-servers (private), branch main, folder Tooling/MCP/mcp-meta-ads_new/.",
            "Version 2.0.0, type module (ESM), engines node >= 18, licence ISC.",
            "Files: index.js, src/config.js, src/graph.js, src/tools.js, src/fields.js — roughly 695 lines total.",
            "Scripts: start (node index.js), check (node --check across all five files). No test script.",
            "Retryable Graph error codes: 1, 2, 4, 17, 32, 341, 613. Retryable HTTP statuses: 429, 500, 502, 503, 504.",
            "Backoff schedule: 500 ms, 1 s, 2 s, 4 s, each plus up to 250 ms of jitter.",
            "Registered in ~/.claude.json as meta-ads.",
        ]},
    ],
}
