"""PRD content module for the WordPress MCP server."""

TOOL_ROWS = [
    ["wp_list_posts", "Posts", "Read", "List posts with filter/pagination params."],
    ["wp_get_post", "Posts", "Read", "Fetch a single post by ID."],
    ["wp_create_post", "Posts", "Write", "Create a post (title, content, status, terms)."],
    ["wp_update_post", "Posts", "Write", "Partial update of an existing post."],
    ["wp_delete_post", "Posts", "Write (destructive)", "Delete a post. No confirmation gate."],
    ["wp_list_pages", "Pages", "Read", "List pages with filter/pagination params."],
    ["wp_get_page", "Pages", "Read", "Fetch a single page by ID."],
    ["wp_create_page", "Pages", "Write", "Create a page."],
    ["wp_update_page", "Pages", "Write", "Partial update of an existing page."],
    ["wp_delete_page", "Pages", "Write (destructive)", "Delete a page. No confirmation gate."],
    ["wp_list_media", "Media", "Read", "List media library items."],
    ["wp_get_media", "Media", "Read", "Fetch a single attachment by ID."],
    ["wp_upload_media", "Media", "Write", "Upload from a local filesystem path to the library."],
    ["wp_update_media", "Media", "Write", "Update attachment metadata (title, alt, caption)."],
    ["wp_delete_media", "Media", "Write (destructive)", "Delete an attachment."],
    ["wp_list_users", "Users", "Read", "List site users."],
    ["wp_get_user", "Users", "Read", "Fetch a user by ID, or 'me' for the authenticated user."],
    ["wp_create_user", "Users", "Write", "Create a user with role and credentials."],
    ["wp_update_user", "Users", "Write", "Update user fields, including role."],
    ["wp_delete_user", "Users", "Write (destructive)", "Delete a user, reassigning owned content. No confirmation gate."],
    ["wp_list_comments", "Comments", "Read", "List comments with filters."],
    ["wp_get_comment", "Comments", "Read", "Fetch a single comment."],
    ["wp_create_comment", "Comments", "Write", "Create a comment on a post."],
    ["wp_update_comment", "Comments", "Write", "Update comment content or approval status."],
    ["wp_delete_comment", "Comments", "Write (destructive)", "Delete a comment."],
    ["wp_list_categories", "Taxonomy", "Read", "List categories."],
    ["wp_list_tags", "Taxonomy", "Read", "List tags."],
    ["wp_create_category", "Taxonomy", "Write", "Create a category term."],
    ["wp_create_tag", "Taxonomy", "Write", "Create a tag term."],
    ["wp_list_post_types", "CPT", "Read", "Enumerate registered post types and their REST bases."],
    ["wp_list_cpt_items", "CPT", "Read", "List items of an arbitrary custom post type."],
    ["wc_list_products", "WooCommerce", "Read", "List products. Requires WC keys."],
    ["wc_get_product", "WooCommerce", "Read", "Fetch a product by ID."],
    ["wc_create_product", "WooCommerce", "Write", "Create a product."],
    ["wc_update_product", "WooCommerce", "Write", "Update a product."],
    ["wc_delete_product", "WooCommerce", "Write (destructive)", "Delete a product. No confirmation gate."],
    ["wc_list_orders", "WooCommerce", "Read (PII)", "List orders including billing/shipping detail."],
    ["wc_get_order", "WooCommerce", "Read (PII)", "Fetch a single order with line items and customer detail."],
    ["wc_update_order", "WooCommerce", "Write", "Update order status/fields."],
    ["wc_list_customers", "WooCommerce", "Read (PII)", "List customer records: name, email, addresses."],
    ["wc_get_customer", "WooCommerce", "Read (PII)", "Fetch a single customer record."],
    ["wp_cache_status", "Cache", "Read", "Report detected cache plugins. Requires the mu-plugin."],
    ["wp_purge_cache", "Cache", "Write", "Purge LiteSpeed, Nginx Helper, WP Rocket, W3TC, WP Super Cache."],
    ["wp_purge_cloudflare", "Cache", "Write", "Purge the Cloudflare zone. Requires CF token and zone ID."],
    ["wp_regenerate_elementor_css", "Elementor", "Write", "Force Elementor to regenerate compiled CSS."],
    ["wp_bust_elementor_image_urls", "Elementor", "Write", "Rewrite image URLs inside _elementor_data with a version token."],
    ["wp_get_post_meta", "Meta", "Read", "Read arbitrary post meta. Requires the mu-plugin."],
    ["wp_update_post_meta", "Meta", "Write", "Write arbitrary post meta. Requires the mu-plugin."],
    ["wp_rest_request", "Escape hatch", "Read/Write (unbounded)", "Arbitrary HTTP method against any /wp-json route."],
]

CONTENT = {
    "title": "PRODUCT REQUIREMENTS DOCUMENT",
    "subtitle": "WordPress MCP Server",
    "tagline": "Single Source of Truth for Engineering, Design & Product",
    "sections": [
        # ---------------- 1 ----------------
        {"kind": "h1", "text": "1. Document Control"},
        {"kind": "h2", "text": "1.1 Version History"},
        {"kind": "table", "header": ["Version", "Date", "Author", "Status", "Summary of Changes"], "rows": [
            ["0.1", "2026-07-22", "Musfiqur Tuhin", "Draft", "Initial PRD written against wordpress-mcp v1.0.0 as shipped (49 tools, ~1,628 LOC)."],
        ]},
        {"kind": "h2", "text": "1.2 Stakeholders & Sign-off"},
        {"kind": "table", "header": ["Role", "Name", "Responsibility", "Sign-off Status"], "rows": [
            ["Document Owner", "Musfiqur Tuhin", "Authors and maintains this PRD.", "Draft"],
            ["Engineering Owner", "TBD — named maintainer for wordpress-mcp", "Owns src/, releases, dependency upgrades.", "Pending"],
            ["Security Reviewer", "TBD — reviewer for credential and PII handling", "Reviews Application Password scope and WooCommerce PII exposure.", "Pending"],
            ["Site Operations", "TBD — owner of the managed WordPress estate", "Approves which sites the server is pointed at.", "Pending"],
        ]},
        {"kind": "h2", "text": "1.3 Reference Documents"},
        {"kind": "bullets", "items": [
            "Repository: HaorGrix/mcp-servers (private monorepo), branch main.",
            "Server source: Tooling/MCP/wordpress-mcp/ — src/index.ts, src/client.ts, src/types.ts, src/tools/*.ts.",
            "Tooling/MCP/wordpress-mcp/README.md — tool inventory and the cache-invalidation runbook.",
            "Tooling/MCP/wordpress-mcp/CHANGELOG.md.",
            "Tooling/MCP/cpanel-mcp/ — owner of cp_deploy_cache_helper, which installs the Agent Cache Control mu-plugin this server depends on.",
            "WordPress REST API Handbook (wp/v2) and WooCommerce REST API v3 reference.",
            "Model Context Protocol specification; @modelcontextprotocol/sdk ^1.12.0.",
        ]},

        # ---------------- 2 ----------------
        {"kind": "h1", "text": "2. Overview & Summary"},
        {"kind": "h2", "text": "2.1 Problem Statement"},
        {"kind": "para", "text": "Routine WordPress work across the managed estate — publishing posts, replacing media, fixing Elementor pages, checking WooCommerce orders — is done by hand through wp-admin. An AI agent asked to do the same work has no direct route: it must either be given browser automation against an admin UI that was never designed for machine use, or it must be handed raw REST credentials and asked to compose HTTP calls, which produces malformed requests, unclear failures, and no record of what it touched."},
        {"kind": "para", "text": "The specific failure that motivated the cache tooling is stale media. Overwriting a file in the media library leaves the URL unchanged, so LiteSpeed, Nginx, WP Rocket, or Cloudflare keep serving the old bytes and the change appears not to have happened. Diagnosing that from inside an agent loop, without a tool that reports cache state or purges it, is guesswork."},
        {"kind": "h2", "text": "2.2 Proposed Solution"},
        {"kind": "para", "text": "wordpress-mcp is a Node/TypeScript MCP server that exposes 49 typed tools over stdio, covering the WordPress REST API (posts, pages, media, users, comments, taxonomy, custom post types), the WooCommerce REST API (products, orders, customers), cache and Elementor maintenance, post meta, and an arbitrary-route escape hatch. Every tool has a zod-validated input schema, so the agent gets argument validation and a machine-readable description rather than free-form HTTP."},
        {"kind": "para", "text": "Authentication is a WordPress Application Password — built into core since 5.6, no plugin and no cost. WooCommerce and Cloudflare credentials are optional; the server starts without them and the corresponding tools return an explicit configuration error rather than failing obscurely."},
        {"kind": "h2", "text": "2.3 Background & Context"},
        {"kind": "para", "text": "The server was built to operate a small estate of client WordPress sites (fernhillbd.com with WooCommerce active, fernhillconsulting.co.uk without). It sits alongside cpanel-mcp, which handles hosting-level operations and installs the Agent Cache Control mu-plugin that gives this server its meta and cache-status capabilities. Version 1.0.0 is in use; the README still advertises \"35+ tools\" and understates the real count of 49."},
        {"kind": "h2", "text": "2.4 Strategic Fit"},
        {"kind": "para", "text": "WordPress is where most HaorGrix client content actually lives. Making it agent-addressable turns content updates, media replacement, and commerce lookups into delegable work instead of manual admin time. It is also the second half of a pair: cpanel-mcp owns the server, wordpress-mcp owns the application on top of it, and the two are designed to be used in the same agent session."},
        {"kind": "h2", "text": "2.5 Objectives & Business Value"},
        {"kind": "bullets", "items": [
            "Remove manual wp-admin work from routine content and media operations.",
            "Make the stale-media problem solvable in-session: detect cache layers, purge origin and edge, or version Elementor image URLs when the edge cannot be purged.",
            "Give agents typed, validated access to WooCommerce catalogue and order data for support and reporting tasks.",
            "Keep operating cost at zero: Application Passwords are core, and the only paid dependency is a Cloudflare account the estate already has.",
        ]},

        # ---------------- 3 ----------------
        {"kind": "h1", "text": "3. Goals & Success Metrics"},
        {"kind": "h2", "text": "3.1 Goals (SMART)"},
        {"kind": "bullets", "items": [
            "G1 — Cover the wp/v2 surface an operator actually uses: posts, pages, media, users, comments, taxonomy and CPTs are all reachable through typed tools at v1.0.0. Met.",
            "G2 — Make a media replacement verifiably visible at the edge within one agent turn using wp_purge_cache plus wp_purge_cloudflare, with wp_bust_elementor_image_urls as the fallback.",
            "G3 — Fail configuration errors loudly: missing required env vars exit at startup with a named list; missing optional credentials produce a named error at call time. Met.",
            "G4 — Add a confirmation gate to all destructive tools, matching the pattern already used in brevo-mcp and mcp-meta-ads, by the next minor release.",
            "G5 — Establish a test suite covering the client layer and at least the destructive and escape-hatch tools; currently zero tests exist.",
        ]},
        {"kind": "h2", "text": "3.2 Success Metrics / KPIs"},
        {"kind": "table", "header": ["Metric", "Baseline", "Target", "Measurement Method"], "rows": [
            ["Tools exposed", "49 at v1.0.0", "Maintain full REST coverage; add wc_create_order and wc_delete_order", "Count of registered tools in src/tools/*.ts"],
            ["Destructive tools behind a confirmation gate", "0 of 6", "6 of 6", "Code review of delete/destructive handlers"],
            ["Automated test coverage", "0% (no test script, no test files)", "Client layer plus destructive and raw tools covered", "Test runner report once a suite exists"],
            ["Typecheck cleanliness", "npm run typecheck passes", "Stays passing on every commit", "CI or pre-commit run of tsc --noEmit"],
            ["Stale-media incidents needing manual intervention", "TBD — not currently tracked", "Zero after the purge runbook is followed", "Operator log of media-replacement tasks"],
            ["Documentation accuracy", "README states \"35+ tools\" against an actual 49", "README tool count and table match source exactly", "Diff of README table against registered tool names"],
        ]},
        {"kind": "h2", "text": "3.3 Non-Goals"},
        {"kind": "bullets", "items": [
            "No WooCommerce order creation or deletion. wc_create_order and wc_delete_order do not exist; order writes are limited to wc_update_order. Creating orders would put the server adjacent to payment capture, which is deliberately out of scope for v1.",
            "No payment, refund, or gateway operations of any kind.",
            "No hosting-level operations — file system, DNS, SSL, cron, and mu-plugin deployment belong to cpanel-mcp.",
            "No HTTP or SSE transport. stdio only; the server is a local subprocess of the agent host.",
            "No multi-site fan-out. One process serves exactly one WORDPRESS_URL; multiple sites means multiple configured server entries.",
            "No end-user GUI, dashboard, or web console.",
            "No plugin or theme installation, update, or activation.",
            "No content authoring intelligence — the server moves bytes, it does not decide what to publish.",
        ]},

        # ---------------- 4 ----------------
        {"kind": "h1", "text": "4. Target Audience & User Personas"},
        {"kind": "h2", "text": "4.1 Primary Persona"},
        {"kind": "table", "header": ["Attribute", "Detail"], "rows": [
            ["Name / Role", "AI coding-and-operations agent running in an MCP host (Claude Code, Claude Desktop)"],
            ["Context", "Given a task in natural language — publish this, replace that image, why is the old logo still showing, list last week's orders"],
            ["Technical Level", "Can compose HTTP but cannot see the site, cannot log into wp-admin, and cannot verify visually"],
            ["Goals", "Complete the content or commerce task correctly and confirm it took effect at the edge"],
            ["Pain Points", "Silent cache staleness; ambiguous REST errors; no way to know whether the mu-plugin is installed until a meta call fails"],
            ["Needs from this product", "Typed schemas, descriptive tool names, errors that state the cause and the fix, and a cache-status probe"],
        ]},
        {"kind": "h2", "text": "4.2 Secondary Personas"},
        {"kind": "bullets", "items": [
            "Operator / site maintainer (HaorGrix) — supervises the agent, owns the Application Password, and is accountable for anything the agent deletes. Reads the server's stderr log line to confirm which site and whether WooCommerce is enabled.",
            "Developer maintaining the server — works in TypeScript, adds tools, and needs the client abstraction in src/client.ts to keep auth and error shaping in one place.",
            "Client site owner — never touches the server, but their content, users, and customer records are what it acts on. Their consent posture governs section 12.",
        ]},

        # ---------------- 5 ----------------
        {"kind": "break"},
        {"kind": "h1", "text": "5. Scope, User Stories & Requirements"},
        {"kind": "h2", "text": "5.1 User Stories"},
        {"kind": "bullets", "items": [
            "As an agent, I want to list and fetch posts and pages so I can locate the content a task refers to before editing it.",
            "As an agent, I want to create and update posts and pages with explicit status so I can stage a draft rather than publish by accident.",
            "As an agent, I want to upload a local file into the media library and then update its alt text and caption.",
            "As an agent, I want to know which cache plugins are active before I try to purge, so I can tell a failed purge from an absent cache layer.",
            "As an agent, I want to purge origin and Cloudflare caches after replacing media so the change is visible immediately.",
            "As an agent, when the edge cannot be purged, I want to version image URLs inside _elementor_data safely rather than run a raw SQL search-and-replace.",
            "As an agent, I want to read and write arbitrary post meta so I can work with custom fields the typed tools do not model.",
            "As an agent, I want to list WooCommerce products and orders so I can answer catalogue and fulfilment questions.",
            "As an agent, I want to reach any /wp-json route when no typed tool exists, so an unmodelled plugin endpoint does not block the task.",
            "As an operator, I want the server to refuse to start when required credentials are missing, so I never point it at a half-configured site.",
            "As an operator, I want destructive operations to require explicit confirmation so an ambiguous instruction cannot delete a user or a product. Not yet implemented.",
        ]},
        {"kind": "h2", "text": "5.2 Functional Requirements"},
        {"kind": "table", "header": ["ID", "Requirement", "Priority", "Acceptance Criteria"], "rows": [
            ["FR-1", "Expose post CRUD as five typed tools.", "Must", "wp_list_posts, wp_get_post, wp_create_post, wp_update_post, wp_delete_post are registered with zod schemas and reach wp/v2/posts."],
            ["FR-2", "Expose page CRUD as five typed tools.", "Must", "wp_list_pages, wp_get_page, wp_create_page, wp_update_page, wp_delete_page operate on wp/v2/pages."],
            ["FR-3", "Expose media management including upload from a local path.", "Must", "wp_upload_media reads a local file and posts it as multipart; wp_list_media, wp_get_media, wp_update_media, wp_delete_media cover the rest."],
            ["FR-4", "Expose user management with content reassignment on delete.", "Must", "wp_list_users, wp_get_user (accepting 'me'), wp_create_user, wp_update_user, wp_delete_user; delete passes a reassign target."],
            ["FR-5", "Expose comment moderation.", "Must", "wp_list_comments, wp_get_comment, wp_create_comment, wp_update_comment, wp_delete_comment."],
            ["FR-6", "Expose taxonomy and custom post type discovery.", "Must", "wp_list_categories, wp_list_tags, wp_create_category, wp_create_tag, wp_list_post_types, wp_list_cpt_items."],
            ["FR-7", "Expose WooCommerce read access for products, orders and customers.", "Must", "wc_list_products, wc_get_product, wc_list_orders, wc_get_order, wc_list_customers, wc_get_customer return data when WC keys are set."],
            ["FR-8", "Expose WooCommerce product writes and order status updates.", "Must", "wc_create_product, wc_update_product, wc_delete_product, wc_update_order."],
            ["FR-9", "Degrade cleanly when WooCommerce is not configured.", "Must", "Calling any wc_* tool without WC_CONSUMER_KEY/WC_CONSUMER_SECRET returns the named error 'WooCommerce API keys not configured', not a network failure."],
            ["FR-10", "Purge origin caches across the supported plugin set.", "Must", "wp_purge_cache clears LiteSpeed, Nginx Helper, WP Rocket, W3TC and WP Super Cache where present."],
            ["FR-11", "Report which cache layers are active.", "Must", "wp_cache_status enumerates detected cache plugins via the Agent Cache Control mu-plugin."],
            ["FR-12", "Purge the Cloudflare edge.", "Should", "wp_purge_cloudflare purges the zone when CLOUDFLARE_API_TOKEN and CLOUDFLARE_ZONE_ID are set, and returns a named configuration error otherwise."],
            ["FR-13", "Regenerate Elementor CSS.", "Should", "wp_regenerate_elementor_css triggers a rebuild of compiled Elementor CSS."],
            ["FR-14", "Version Elementor image URLs without corrupting stored JSON.", "Should", "wp_bust_elementor_image_urls appends a version token to image URLs inside _elementor_data via json_decode/json_encode server-side, never string replacement."],
            ["FR-15", "Read and write arbitrary post meta.", "Should", "wp_get_post_meta and wp_update_post_meta operate through the mu-plugin's agent-cache/v1 routes."],
            ["FR-16", "Provide an arbitrary-route escape hatch.", "Should", "wp_rest_request issues any HTTP method against any /wp-json route with the configured credentials."],
            ["FR-17", "Validate configuration at startup.", "Must", "Missing WORDPRESS_URL, WORDPRESS_USERNAME or WORDPRESS_APP_PASSWORD prints the missing names and exits non-zero."],
            ["FR-18", "Run over stdio with clean shutdown.", "Must", "StdioServerTransport connects; SIGINT and SIGTERM log and exit 0."],
            ["FR-19", "Gate destructive operations behind explicit confirmation.", "Should", "wp_delete_post, wp_delete_page, wp_delete_media, wp_delete_comment, wp_delete_user and wc_delete_product require a confirm flag before executing. Not implemented at v1.0.0."],
            ["FR-20", "Support WooCommerce order creation and deletion.", "Should", "wc_create_order and wc_delete_order exist and are covered by the same PII handling as the read tools. Not implemented at v1.0.0; see 3.3."],
            ["FR-21", "Constrain or audit the escape hatch.", "Should", "wp_rest_request either enforces a route allowlist or logs every invocation with method and path. Not implemented."],
            ["FR-22", "Automated tests for the client and destructive paths.", "Should", "A test script exists in package.json and passes. Not implemented."],
            ["FR-23", "Redact or minimise PII in WooCommerce responses.", "Could", "Customer and order tools offer a field-selection or redaction mode so full addresses are not returned by default. Not implemented."],
            ["FR-24", "Report the target site on startup.", "Must", "stderr logs the WORDPRESS_URL and whether WooCommerce is enabled. Met."],
        ]},
        {"kind": "para", "text": "Complete tool inventory (49 tools), with read/write classification:"},
        {"kind": "table", "header": ["Tool", "Group", "Classification", "Behaviour"], "rows": TOOL_ROWS},
        {"kind": "h2", "text": "5.3 User Flows"},
        {"kind": "bullets", "items": [
            "Startup — host launches node dist/index.js; dotenv loads .env; required env vars are checked and the process exits on any missing; WordPressClient is constructed; nine tool-group registrars run; StdioServerTransport connects; a stderr line names the site and WooCommerce state.",
            "Publish — wp_list_posts to locate or confirm absence, wp_create_post with status draft, operator reviews, wp_update_post to status publish.",
            "Media replacement (the canonical flow) — wp_upload_media overwriting the file, wp_purge_cache, wp_purge_cloudflare, wp_regenerate_elementor_css. If the edge cannot be purged, substitute wp_bust_elementor_image_urls with a timestamp version token.",
            "Cache diagnosis — wp_cache_status first; if it errors, the Agent Cache Control mu-plugin is absent and cpanel-mcp's cp_deploy_cache_helper must be run once before retrying.",
            "Commerce lookup — wc_list_orders filtered by status or date, then wc_get_order for detail, then wc_update_order to change fulfilment status.",
            "Unmodelled endpoint — agent finds no typed tool, calls wp_rest_request with an explicit method and /wp-json path. No guardrail applies on this path.",
        ]},

        # ---------------- 6 ----------------
        {"kind": "h1", "text": "6. Non-Functional Requirements"},
        {"kind": "table", "header": ["Category", "Requirement"], "rows": [
            ["Performance", "Latency is dominated by the remote WordPress site, not the server. Local overhead per call is schema validation plus one HTTPS round trip. List tools must expose per_page and page so an agent can bound response size; large media uploads are bounded by the site's PHP upload limits, not by this process."],
            ["Scalability", "Single-process, single-site, one stdio client. Concurrency is whatever the agent host issues; there is no queue, no rate limiter and no connection pooling. Scaling to more sites means more configured server instances, not more capacity in one."],
            ["Availability", "No independent uptime. The process lives and dies with the agent host, and is entirely dependent on the target site, its host, and — for edge purges — the Cloudflare API. No retry or circuit breaker is implemented; a failed call surfaces as an error to the agent."],
            ["Security", "Credentials come only from environment variables loaded by dotenv; nothing is hardcoded and .env must be gitignored. A WordPress Application Password is full-privilege for the granted user and cannot be scoped per capability — if the account can delete users, so can the agent. Least privilege must therefore be enforced by choosing the WordPress role of the account, not by the password. WooCommerce consumer key/secret carry read_write scope. wp_rest_request bypasses every typed guardrail by design. No destructive-action confirmation gate exists. All traffic must be HTTPS; credentials must never be echoed into tool output or error messages."],
            ["Privacy / Compliance", "WooCommerce customer and order records are personal data: names, email addresses, billing and shipping addresses, phone numbers, order history. wc_list_customers, wc_get_customer, wc_list_orders and wc_get_order pull that data into the agent's context window, where it may be retained by the model host. Responses must not be written to disk or logs. See section 12."],
            ["Accessibility", "N/A — no human-facing UI. Operator-facing output is plain text on stdout/stderr and is screen-reader compatible by virtue of being text."],
            ["Observability", "Minimal. One stderr line at startup naming the target site and WooCommerce state, plus stderr on shutdown and fatal error. There is no per-call logging, no request ID, no metrics and no audit trail — which is a real gap given the destructive and escape-hatch tools. Recorded as a risk."],
            ["Localization", "N/A — tool names, descriptions and errors are English only and consumed by an agent. Content payloads pass through unmodified, so multilingual site content is handled correctly as opaque UTF-8."],
        ]},

        # ---------------- 7 ----------------
        {"kind": "h1", "text": "7. Technical Considerations"},
        {"kind": "h2", "text": "7.1 Architecture & Dependencies"},
        {"kind": "para", "text": "Node.js (engines: >=18) with TypeScript 5.7, compiled by tsc to dist/ and started with node dist/index.js; tsx runs src/index.ts directly in development. Roughly 1,628 lines across src/index.ts (86), src/client.ts (259), src/types.ts (169) and nine tool modules under src/tools/ (posts 131, pages 113, media 121, users 123, comments 106, taxonomy 133, woocommerce 220, cache 106, raw 61)."},
        {"kind": "para", "text": "src/index.ts validates config, constructs a single WordPressClient, and calls nine registrar functions that attach tools to an McpServer. src/client.ts is the only place that knows about authentication, base URLs, and the WooCommerce and Cloudflare credential checks. Transport is StdioServerTransport — no HTTP listener, no port."},
        {"kind": "bullets", "items": [
            "@modelcontextprotocol/sdk ^1.12.0 — McpServer and StdioServerTransport.",
            "zod ^3.23.8 — input schemas for all 49 tools.",
            "dotenv ^16.4.7 — loads .env at import time.",
            "Dev: typescript ^5.7.2, tsx ^4.19.2, @types/node ^22.10.0.",
            "Scripts: build (tsc), start (node dist/index.js), dev (tsx src/index.ts), typecheck (tsc --noEmit). There is no test script.",
        ]},
        {"kind": "h2", "text": "7.2 Data Model & APIs"},
        {"kind": "para", "text": "The server holds no database and no persistent state. src/types.ts declares TypeScript shapes for the WordPress and WooCommerce entities the tools return; everything else is passed through as received from the REST API."},
        {"kind": "table", "header": ["Surface", "Base", "Auth", "Used by"], "rows": [
            ["WordPress core REST", "<WORDPRESS_URL>/wp-json/wp/v2/", "Basic auth with Application Password", "Posts, pages, media, users, comments, taxonomy, CPT tools"],
            ["WooCommerce REST v3", "<WORDPRESS_URL>/wp-json/wc/v3/", "Consumer key/secret", "All wc_* tools"],
            ["Agent Cache Control mu-plugin", "<WORDPRESS_URL>/wp-json/agent-cache/v1/", "Application Password", "wp_cache_status, wp_get_post_meta, wp_update_post_meta, purge helpers"],
            ["Cloudflare API v4", "api.cloudflare.com — zones/<CLOUDFLARE_ZONE_ID>/purge_cache", "Bearer token", "wp_purge_cloudflare"],
            ["Any /wp-json route", "<WORDPRESS_URL>/wp-json/", "Application Password", "wp_rest_request"],
        ]},
        {"kind": "table", "header": ["Env var", "Required", "Purpose"], "rows": [
            ["WORDPRESS_URL", "Yes — startup exits without it", "Base URL of the target site"],
            ["WORDPRESS_USERNAME", "Yes", "WordPress user the Application Password belongs to"],
            ["WORDPRESS_APP_PASSWORD", "Yes", "Application Password; full-privilege for that user"],
            ["WC_CONSUMER_KEY", "No", "WooCommerce REST key; absence disables all wc_* tools with a named error"],
            ["WC_CONSUMER_SECRET", "No", "WooCommerce REST secret"],
            ["CLOUDFLARE_API_TOKEN", "No", "Cloudflare purge token; absence disables wp_purge_cloudflare"],
            ["CLOUDFLARE_ZONE_ID", "No", "Cloudflare zone to purge"],
        ]},
        {"kind": "h2", "text": "7.3 Integrations"},
        {"kind": "para", "text": "The most important integration is a cross-server dependency. The Agent Cache Control mu-plugin (agent-cache/v1) is not shipped or installed by this server — it is deployed by cpanel-mcp's cp_deploy_cache_helper tool, which must be run once per site. Until it is, wp_get_post_meta, wp_update_post_meta and wp_cache_status all fail, and the cache-purge path loses its diagnostic step. This is a silent coupling: nothing in wordpress-mcp checks for the plugin at startup, so the failure only appears when an agent calls one of those three tools mid-task. Any deployment runbook for a new site must place cp_deploy_cache_helper before first use of this server."},
        {"kind": "table", "header": ["Dependency", "Owner", "Type", "Status"], "rows": [
            ["Agent Cache Control mu-plugin (agent-cache/v1)", "cpanel-mcp (HaorGrix), installed via cp_deploy_cache_helper", "Required for 3 tools; hard cross-server dependency", "Live — must be deployed per site before use; not verified at startup"],
            ["Target WordPress site + Application Password", "Site owner / HaorGrix operations", "Core runtime dependency", "Live"],
            ["WooCommerce plugin + REST keys", "Site owner", "Optional; gates 10 tools", "Active on fernhillbd.com, absent on fernhillconsulting.co.uk"],
            ["Cloudflare API (zone purge)", "HaorGrix / site owner", "Optional; gates wp_purge_cloudflare", "Configured per site"],
            ["Cache plugins (LiteSpeed, Nginx Helper, WP Rocket, W3TC, WP Super Cache)", "Site owner", "Optional; wp_purge_cache targets whichever are present", "Varies by site"],
            ["Elementor", "Site owner", "Optional; gates the two Elementor tools", "Present on the Elementor-built sites"],
            ["@modelcontextprotocol/sdk ^1.12.0", "Anthropic / upstream", "Library", "Pinned by caret; breaking minor changes are a live risk"],
            ["MCP host (Claude Code / Claude Desktop)", "Anthropic", "Runtime host over stdio", "Live"],
        ]},
        {"kind": "h2", "text": "7.4 Constraints & Assumptions"},
        {"kind": "bullets", "items": [
            "One process serves exactly one site; WORDPRESS_URL is fixed at startup.",
            "stdio only — the server cannot be reached over a network and is not multi-tenant.",
            "Application Passwords cannot be scoped per capability; the WordPress role of the account is the only privilege boundary available.",
            "The site must expose /wp-json publicly and must not block Basic auth headers at the web server or firewall.",
            "wp_upload_media reads from the local filesystem of the machine running the server, so the file must already be present there.",
            "Assumes HTTPS on the target site; Basic auth over plain HTTP would expose the Application Password.",
            "Assumes the operator supervising the agent is accountable for destructive calls, because the code enforces no confirmation.",
            "Assumes the mu-plugin has been deployed by cpanel-mcp; nothing verifies this.",
        ]},
        {"kind": "h2", "text": "7.5 Analytics & Instrumentation"},
        {"kind": "para", "text": "No analytics or telemetry is implemented. The table below records the only signals that exist today plus the instrumentation this PRD proposes; proposed rows are marked."},
        {"kind": "table", "header": ["Event", "Trigger", "Properties", "Destination"], "rows": [
            ["server_start", "Transport connects", "WORDPRESS_URL, WooCommerce enabled/disabled", "stderr (implemented)"],
            ["config_missing", "Required env var absent", "Names of missing vars", "stderr, then exit non-zero (implemented)"],
            ["shutdown", "SIGINT or SIGTERM", "Signal", "stderr (implemented)"],
            ["fatal_error", "Unhandled error in main()", "Error object", "stderr, then exit 1 (implemented)"],
            ["tool_invoked", "Any tool call", "Tool name, duration, HTTP status, no argument values", "Proposed — structured stderr log"],
            ["destructive_invoked", "Any delete or destructive tool", "Tool name, target ID, confirmation flag", "Proposed — audit log, required alongside FR-19"],
            ["raw_request_invoked", "wp_rest_request call", "HTTP method, route path", "Proposed — audit log, required alongside FR-21"],
        ]},

        # ---------------- 8 ----------------
        {"kind": "h1", "text": "8. Design & UX"},
        {"kind": "para", "text": "There is no graphical interface. The entire product surface is 49 tool definitions consumed by an AI agent over stdio, so the design work is in naming, descriptions, errors, and guard ergonomics — the only affordances the agent has."},
        {"kind": "bullets", "items": [
            "Naming — a strict verb-object convention with a namespace prefix: wp_ for WordPress core, wc_ for WooCommerce. The verb states the operation (list, get, create, update, delete, upload, purge, regenerate, bust) so an agent can infer read/write intent from the name alone before reading the description. The prefix split also tells the agent immediately which credential set a failure would relate to.",
            "Description quality — the tool description is the agent's only documentation; there is no manual to consult mid-task. Descriptions must state what the tool changes, what it requires (for example that wp_cache_status and the meta tools depend on the mu-plugin), and any irreversibility. Where a description is thin, the agent's failure mode is not an error but a wrong choice of tool.",
            "Schema as guidance — zod schemas do double duty as validation and as documentation. Optional parameters with meaningful names (per_page, page, status) steer the agent toward bounded, staged operations; wp_create_post exposing an explicit status is what lets an agent draft rather than publish.",
            "Error legibility — configuration errors name the exact missing variable and the fix, for example 'WooCommerce API keys not configured. Set WC_CONSUMER_KEY and WC_CONSUMER_SECRET in .env.' That pattern should extend to the mu-plugin dependency, which currently surfaces as an opaque REST 404 rather than a sentence telling the agent to run cp_deploy_cache_helper.",
            "Confirmation and guard ergonomics — this is the weakest part of the current design. Six destructive tools execute on first call with no second step, while sibling servers (brevo-mcp, mcp-meta-ads) require an explicit confirmation argument. The intended pattern is a required confirm parameter whose rejection message restates exactly what would be deleted, so the agent must re-assert intent with the target named.",
            "Escape-hatch framing — wp_rest_request must be described as a last resort, explicitly after the typed tools have been ruled out, or an agent will reach for it first and lose every guardrail the other 48 tools provide.",
        ]},

        # ---------------- 9 ----------------
        {"kind": "break"},
        {"kind": "h1", "text": "9. Release Plan & Milestones"},
        {"kind": "h2", "text": "9.1 Phases"},
        {"kind": "table", "header": ["Milestone", "Scope", "Owner", "Target Date"], "rows": [
            ["M0 — v1.0.0 shipped", "49 tools across nine groups, stdio transport, Application Password auth, cache and Elementor tooling", "Musfiqur Tuhin", "Complete"],
            ["M1 — Safety pass", "FR-19 confirmation gates on all six destructive tools; FR-21 audit logging for wp_rest_request", "TBD — engineering owner", "TBD"],
            ["M2 — Test suite", "FR-22: client-layer tests plus coverage of destructive and raw paths; add a test script to package.json", "TBD — engineering owner", "TBD"],
            ["M3 — Documentation correction", "README tool count and table reconciled with source (49, not 35+); mu-plugin prerequisite documented at the top", "Musfiqur Tuhin", "TBD"],
            ["M4 — Commerce completeness", "FR-20 wc_create_order and wc_delete_order, subject to the scope decision in 3.3", "TBD", "TBD"],
            ["M5 — PII minimisation", "FR-23 field selection or redaction on WooCommerce customer and order responses", "TBD", "TBD"],
        ]},
        {"kind": "h2", "text": "9.2 Rollout Strategy"},
        {"kind": "para", "text": "Distribution is by cloning the monorepo and registering the built entry point in the MCP host config; there is no package publish and no server to deploy. Rollout of a new site is: create a WordPress user at the minimum sufficient role, generate an Application Password, run cp_deploy_cache_helper from cpanel-mcp, populate .env, npm install, npm run build, then verify with a read-only call (wp_get_user with 'me') before any write. Changes to the server itself roll out per developer machine on the next pull and build, so there is no staged rollout and no rollback mechanism beyond git."},
        {"kind": "h2", "text": "9.3 Effort & Timeline"},
        {"kind": "table", "header": ["Workstream", "Owner", "Estimate", "Dependencies"], "rows": [
            ["Confirmation gates on six destructive tools", "TBD — engineering owner", "1–2 days", "Agreement on the confirm-parameter pattern used in brevo-mcp"],
            ["Audit logging for wp_rest_request and destructive calls", "TBD", "1 day", "Decision on log destination (stderr vs file)"],
            ["Test suite and CI typecheck gate", "TBD", "3–4 days", "Choice of test runner; a disposable WordPress instance to test against"],
            ["README and tool-count correction", "Musfiqur Tuhin", "0.5 day", "None"],
            ["Mu-plugin presence check at startup with an actionable error", "TBD", "0.5 day", "cpanel-mcp mu-plugin route contract"],
            ["wc_create_order / wc_delete_order", "TBD", "2 days", "Scope decision in 3.3 and section 12 sign-off on payment adjacency"],
            ["WooCommerce PII field selection", "TBD", "2 days", "Privacy review"],
        ]},
        {"kind": "h2", "text": "9.4 Launch Readiness Checklist"},
        {"kind": "bullets", "items": [
            "npm run typecheck passes against a clean build (remove dist/ and *.tsbuildinfo first).",
            ".env is gitignored and contains no committed credentials anywhere in history.",
            "Application Password is issued to a user whose WordPress role is the minimum the tasks require.",
            "Target site is HTTPS and /wp-json is reachable with the configured credentials.",
            "cp_deploy_cache_helper has been run against the site and wp_cache_status returns successfully.",
            "WooCommerce keys are present only if commerce tools are actually needed on that site.",
            "Operator has been briefed that six destructive tools have no confirmation gate.",
            "Operator understands that WooCommerce reads place customer PII into the agent context.",
            "README tool inventory matches the registered tools.",
            "Startup stderr line confirms the expected site URL before any write is attempted.",
        ]},

        # ---------------- 10 ----------------
        {"kind": "h1", "text": "10. Cost, Resourcing & Effort"},
        {"kind": "h2", "text": "10.1 Team & Roles"},
        {"kind": "table", "header": ["Role", "Person", "Allocation"], "rows": [
            ["Document owner / product", "Musfiqur Tuhin", "As needed"],
            ["Maintainer (TypeScript)", "TBD — named maintainer for wordpress-mcp", "Part-time, demand-driven"],
            ["Security / privacy reviewer", "TBD", "Point review per release"],
            ["Site operations", "TBD — owner of the managed WordPress estate", "Per-site onboarding"],
        ]},
        {"kind": "h2", "text": "10.2 Cost Considerations"},
        {"kind": "bullets", "items": [
            "Direct software cost is zero. Application Passwords are WordPress core since 5.6; the WooCommerce and WordPress REST APIs carry no per-call fee; all runtime dependencies are open source.",
            "Cloudflare purge uses an existing account; purge_cache is available on the free plan.",
            "Compute cost is negligible — a short-lived Node subprocess on the operator's machine.",
            "The real cost is engineering time on the safety, test and documentation workstreams in 9.3, plus token cost in the agent host: WooCommerce list responses are verbose, and an unbounded wc_list_orders or wc_list_products call can consume a large share of a context window. Agents should always pass per_page.",
            "Latent risk cost: no tests and no confirmation gates means an incorrect delete is recoverable only from the site's own backups, which this server neither takes nor verifies.",
        ]},

        # ---------------- 11 ----------------
        {"kind": "h1", "text": "11. Operations, Support & Maintenance"},
        {"kind": "h2", "text": "11.1 Operational Ownership"},
        {"kind": "para", "text": "HaorGrix owns the server code; the site owner owns the WordPress instance it acts on. There is nothing to monitor — the process is a subprocess of the agent host with no uptime of its own. Credential rotation (Application Password, WooCommerce keys, Cloudflare token) is an operations task with no automation behind it; revoking an Application Password in wp-admin is the kill switch and takes effect immediately."},
        {"kind": "h2", "text": "11.2 Support & Enablement"},
        {"kind": "bullets", "items": [
            "First-line reference is the README, including the cache-invalidation runbook, plus this PRD.",
            "Diagnosis order for a failing call: check the startup stderr line for the target site, confirm credentials, confirm /wp-json reachability, then confirm the mu-plugin if the failing tool is wp_cache_status, wp_get_post_meta or wp_update_post_meta.",
            "Stale content after a change is a cache problem until proven otherwise; run wp_cache_status, then wp_purge_cache and wp_purge_cloudflare, then the Elementor tools.",
            "There is no issue tracker convention documented for this server. TBD — agree where defects are filed in HaorGrix/mcp-servers.",
        ]},
        {"kind": "h2", "text": "11.3 Maintenance & Deprecation"},
        {"kind": "bullets", "items": [
            "Track WordPress core REST and WooCommerce v3 changes; both are stable, but plugin-provided routes reached via wp_rest_request are not.",
            "@modelcontextprotocol/sdk is pinned by caret at ^1.12.0; SDK minor releases have historically changed registration APIs, so upgrades need a build and a manual smoke test.",
            "Node >=18 is the declared floor; revisit as Node 18 leaves maintenance.",
            "Deprecation path: if a typed tool is removed, wp_rest_request remains a fallback, so removals are low-risk for callers but must still be announced in CHANGELOG.md.",
            "Retirement of a site means revoking its Application Password and WooCommerce keys, not just deleting the .env.",
        ]},

        # ---------------- 12 ----------------
        {"kind": "h1", "text": "12. Legal, Privacy & Compliance"},
        {"kind": "para", "text": "This server is the only one in the estate that routinely handles third-party personal data. wc_list_customers, wc_get_customer, wc_list_orders and wc_get_order return names, email addresses, telephone numbers, billing and shipping addresses, and purchase history belonging to a client's customers — people who have no relationship with HaorGrix and have not consented to their data entering an AI agent's context. wp_list_users and wp_get_user return site-user email addresses on the same basis. Treat every WooCommerce read as a processing activity, not a lookup."},
        {"kind": "table", "header": ["Area", "Consideration", "Owner / Status"], "rows": [
            ["GDPR — legal basis", "The client site owner is the data controller; HaorGrix acts as processor when an agent reads customer data. Processing requires a documented instruction from the controller and a written processing agreement covering AI-assisted access.", "TBD — confirm a DPA exists for each site with WooCommerce enabled"],
            ["GDPR — data minimisation (Art. 5)", "wc_list_customers returns whole customer records with no field selection. Pulling a full customer list to answer a narrow question is disproportionate. FR-23 (field selection / redaction) is the remedy and is not yet implemented.", "Open — FR-23"],
            ["GDPR — purpose limitation and retention", "The server stores nothing, but the agent host retains the conversation. Personal data read into a transcript inherits the host's retention period, which is outside HaorGrix's control. Responses must never be written to files, logs, or shared documents.", "Open — needs a written operator rule"],
            ["GDPR — Art. 15/17 rights", "Deletion or export requests are served through WordPress and WooCommerce tooling on the site itself. This server can read and update but is not the system of record and must not be treated as one.", "Site owner"],
            ["GDPR — international transfer", "Sending EU customer data to a model host processes it outside the site's environment and may constitute a transfer. Must be assessed per client before WooCommerce reads are permitted.", "Open — TBD legal review"],
            ["CCPA / CPRA", "Customer names, addresses, and purchase histories are personal information. Californian consumers' access and deletion rights are served on the site; agent access must not create an undisclosed secondary use. Purchase history must not be used for any profiling purpose.", "Open — site owner disclosure"],
            ["PCI DSS scope", "Not in scope, and the design keeps it that way. The WooCommerce REST API does not return primary account numbers, CVVs, or full card data; orders expose only a payment method title and a gateway transaction reference. The server performs no payment capture, refund, or gateway call, and wc_create_order does not exist — which is a deliberate reason to keep it out of scope. Any future order-creation or refund capability would require a fresh PCI assessment before it ships.", "Assessed — out of scope at v1.0.0; re-assess before FR-20"],
            ["Credential handling", "Application Passwords, WooCommerce consumer secrets, and the Cloudflare token live only in .env. .env, *.pem, *.key and *secret* must be gitignored. Credentials must never appear in tool output, error text, or commits.", "Owner: maintainer"],
            ["Privilege scoping", "An Application Password grants everything the underlying user can do and cannot be narrowed per capability. Least privilege is achievable only by choosing the WordPress role. Using an Administrator account gives an agent user-deletion power it almost never needs.", "Open — audit role of each configured account"],
            ["Destructive action liability", "Six tools delete client data with no confirmation gate. On a client-owned site this is a contractual exposure, not only a technical one.", "Open — FR-19"],
            ["Escape hatch", "wp_rest_request can reach any /wp-json route, including plugin routes that expose data this PRD has not assessed. No allowlist and no audit log exist.", "Open — FR-21"],
            ["Licensing", "MIT/ISC dependency set with no copyleft obligations. WordPress and WooCommerce are GPL but are consumed over HTTP, which creates no derivative-work obligation for this server.", "Cleared"],
            ["Content ownership", "Content created or modified by the agent belongs to the site owner. Authorship is attributed to the WordPress user behind the Application Password, so the audit trail in wp-admin names an account, not an agent — worth stating to clients.", "Owner: site operations"],
        ]},

        # ---------------- 13 ----------------
        {"kind": "break"},
        {"kind": "h1", "text": "13. Risks, Dependencies & Open Questions"},
        {"kind": "h2", "text": "13.1 Risks"},
        {"kind": "table", "header": ["Risk", "Likelihood", "Impact", "Mitigation"], "rows": [
            ["wp_rest_request is an unbounded escape hatch — any method, any /wp-json route — bypassing every typed schema, validation rule and future guardrail.", "High", "High", "Describe it explicitly as a last resort; implement FR-21 (route allowlist or full audit logging); constrain the underlying WordPress role so the escape hatch cannot exceed it."],
            ["No confirmation gate on destructive tools. wp_delete_post, wp_delete_page, wp_delete_media, wp_delete_comment, wp_delete_user and wc_delete_product execute on first call, unlike brevo-mcp and mcp-meta-ads which require explicit confirmation.", "High", "High", "Implement FR-19 across all six; until then, run against accounts without delete capability wherever possible and brief operators."],
            ["No tests at all — no test script, no test files, ~1,628 LOC unverified beyond tsc.", "High", "Medium", "FR-22: client-layer tests plus destructive and raw-path coverage against a disposable WordPress instance."],
            ["Silent mu-plugin dependency. wp_cache_status, wp_get_post_meta and wp_update_post_meta fail with an opaque REST error if cp_deploy_cache_helper was never run, and nothing checks at startup.", "Medium", "Medium", "Add a startup or first-call probe returning an error that names cp_deploy_cache_helper; document the prerequisite at the top of the README."],
            ["WooCommerce PII enters the agent context in bulk, with no field selection and no redaction.", "Medium", "High", "FR-23; operator rule that customer reads are narrowed by ID or filter and never dumped wholesale; see section 12."],
            ["Application Password cannot be scoped per capability, so any leak or misuse grants the full role.", "Medium", "High", "Issue passwords to the lowest sufficient role; rotate on any suspicion; revoke immediately in wp-admin as the kill switch."],
            ["No audit trail. No per-call logging means an incorrect delete or an unexpected wp_rest_request cannot be reconstructed afterwards.", "High", "Medium", "Implement the proposed instrumentation in 7.5."],
            ["No retry, timeout or rate-limit handling. A slow or throttled site surfaces as a raw failure mid-task.", "Medium", "Low", "Add bounded timeouts and a single retry on idempotent reads."],
            ["wp_bust_elementor_image_urls mutates stored _elementor_data. It edits via json_decode/json_encode rather than string replacement, which is the safe approach, but it is still an irreversible write to page structure with no backup step.", "Low", "Medium", "Document it as the fallback only when purge is impossible; take a post revision or export before running it."],
            ["Documentation drift — README claims \"35+ tools\" against 49 registered, so the written record already understates the surface area.", "Certain", "Low", "M3 documentation correction; regenerate the tool table from source."],
            ["SDK caret range (^1.12.0) can pull a minor release with breaking registration changes.", "Medium", "Medium", "Pin exactly for releases; smoke-test after any SDK bump."],
            ["Single-site coupling — an operator pointing the process at the wrong WORDPRESS_URL will act on the wrong client's site.", "Low", "High", "Startup stderr names the site; make reading that line a mandatory pre-write step in the checklist."],
        ]},
        {"kind": "h2", "text": "13.2 Open Questions"},
        {"kind": "table", "header": ["Question", "Owner", "Status"], "rows": [
            ["What confirmation pattern should destructive tools adopt — a required confirm boolean, or an echo of the target's title/name?", "TBD — engineering owner", "Open"],
            ["Should wp_rest_request be allowlisted by route prefix, or kept unbounded with mandatory audit logging?", "TBD — engineering owner", "Open"],
            ["Should wc_create_order and wc_delete_order be built at all, given the PCI and payment-adjacency argument in 3.3 and section 12?", "Musfiqur Tuhin", "Open"],
            ["Which WordPress role should the Application Password account hold on each site, and is any site currently using Administrator unnecessarily?", "Site operations", "Open"],
            ["Is a data processing agreement in place with every client whose WooCommerce data an agent may read?", "TBD — legal", "Open"],
            ["Where do defects for this server get filed within HaorGrix/mcp-servers?", "Musfiqur Tuhin", "Open"],
            ["Should the server probe for the agent-cache/v1 mu-plugin at startup, or only on first use of a dependent tool?", "TBD", "Open"],
            ["Is per-call structured logging acceptable given that arguments may contain personal data, and if so what gets redacted?", "TBD — security reviewer", "Open"],
        ]},
        {"kind": "h2", "text": "13.3 Decision Log"},
        {"kind": "table", "header": ["Date", "Decision", "Rationale", "Decided By"], "rows": [
            ["TBD — pre-v1.0.0", "Authenticate with WordPress Application Passwords rather than JWT or OAuth plugins", "Core since WP 5.6, zero cost, no plugin to install or maintain on client sites", "Musfiqur Tuhin"],
            ["TBD — pre-v1.0.0", "stdio transport only", "The server is a local subprocess of the agent host; an HTTP listener would add an attack surface with no caller", "Musfiqur Tuhin"],
            ["TBD — pre-v1.0.0", "Ship wp_rest_request as an escape hatch", "Plugin routes cannot all be modelled; a task should not be blocked by a missing typed tool. Accepted with known guardrail loss", "Musfiqur Tuhin"],
            ["TBD — pre-v1.0.0", "Version Elementor image URLs by editing _elementor_data through json_decode/json_encode", "A raw SQL search-and-replace corrupts serialised JSON; server-side re-encoding cannot", "Musfiqur Tuhin"],
            ["TBD — pre-v1.0.0", "Put the mu-plugin in cpanel-mcp rather than shipping it here", "Installing a mu-plugin is a filesystem operation and belongs to the hosting server, not the REST client", "Musfiqur Tuhin"],
            ["TBD — pre-v1.0.0", "Omit wc_create_order and wc_delete_order", "Keeps the server clear of payment-adjacent flows and PCI scope; order writes limited to status updates", "Musfiqur Tuhin"],
            ["2026-07-22", "Record the missing confirmation gates, missing tests and unbounded escape hatch as open risks rather than closing them in this document", "The PRD describes the code as shipped; remediation is scheduled as M1 and M2", "Musfiqur Tuhin"],
        ]},

        # ---------------- 14 ----------------
        {"kind": "h1", "text": "14. Appendix & Glossary"},
        {"kind": "h2", "text": "14.1 Competitive / Market Analysis"},
        {"kind": "para", "text": "Several public WordPress MCP servers exist, most wrapping only posts and pages with read-heavy tool sets. The distinguishing features here are the WooCommerce surface, the cache and Elementor maintenance tools built around a real operational failure mode, and the paired mu-plugin that exposes post meta and cache state. Where public alternatives are ahead is discipline: several ship tests and confirmation prompts on destructive operations, which this server does not. Building in-house was the right call regardless — the cache and Elementor tooling is specific to how the HaorGrix estate is hosted, and no public server would carry the agent-cache/v1 dependency."},
        {"kind": "h2", "text": "14.2 Glossary"},
        {"kind": "table", "header": ["Term", "Definition"], "rows": [
            ["MCP", "Model Context Protocol — the interface by which an AI agent host discovers and calls external tools."],
            ["stdio transport", "MCP over the process's standard input/output; the server runs as a child process of the host with no network listener."],
            ["Application Password", "WordPress core feature (5.6+) issuing a revocable Basic-auth credential for a user. Full-privilege for that user; cannot be scoped per capability."],
            ["wp/v2", "Namespace of the WordPress core REST API."],
            ["wc/v3", "Namespace of the WooCommerce REST API, authenticated with a consumer key and secret."],
            ["agent-cache/v1", "REST namespace added by the Agent Cache Control mu-plugin, providing cache status and post-meta routes."],
            ["mu-plugin", "Must-use plugin — code in wp-content/mu-plugins that WordPress loads unconditionally and that cannot be deactivated from wp-admin."],
            ["cp_deploy_cache_helper", "Tool in cpanel-mcp that installs the Agent Cache Control mu-plugin. Prerequisite for three tools in this server."],
            ["_elementor_data", "Post meta key holding an Elementor page's layout as JSON. Edited server-side via json_decode/json_encode by wp_bust_elementor_image_urls."],
            ["Cache busting", "Changing a resource URL (here by appending ?ver=<token>) so caches treat it as new, used when the edge cannot be purged."],
            ["CPT", "Custom post type — a non-core content type registered by a theme or plugin, reachable via wp_list_post_types and wp_list_cpt_items."],
            ["Escape hatch", "wp_rest_request: an untyped tool that can call any REST route, bypassing the schemas that constrain the other 48 tools."],
            ["PII", "Personally identifiable information. Here: WooCommerce customer and order records, and WordPress user email addresses."],
            ["zod", "TypeScript schema library used to define and validate every tool's input."],
        ]},
        {"kind": "h2", "text": "14.3 Additional Notes & References"},
        {"kind": "para", "text": "Complete tool inventory by group (49 tools). The full per-tool table with behaviour notes is in section 5.2."},
        {"kind": "table", "header": ["Group", "Read tools", "Write tools", "Count"], "rows": [
            ["Posts", "wp_list_posts, wp_get_post", "wp_create_post, wp_update_post, wp_delete_post", "5"],
            ["Pages", "wp_list_pages, wp_get_page", "wp_create_page, wp_update_page, wp_delete_page", "5"],
            ["Media", "wp_list_media, wp_get_media", "wp_upload_media, wp_update_media, wp_delete_media", "5"],
            ["Users", "wp_list_users, wp_get_user", "wp_create_user, wp_update_user, wp_delete_user", "5"],
            ["Comments", "wp_list_comments, wp_get_comment", "wp_create_comment, wp_update_comment, wp_delete_comment", "5"],
            ["Taxonomy / CPT", "wp_list_categories, wp_list_tags, wp_list_post_types, wp_list_cpt_items", "wp_create_category, wp_create_tag", "6"],
            ["WooCommerce", "wc_list_products, wc_get_product, wc_list_orders, wc_get_order, wc_list_customers, wc_get_customer", "wc_create_product, wc_update_product, wc_delete_product, wc_update_order", "10"],
            ["Cache / Elementor", "wp_cache_status", "wp_purge_cache, wp_purge_cloudflare, wp_regenerate_elementor_css, wp_bust_elementor_image_urls", "5"],
            ["Meta / escape hatch", "wp_get_post_meta", "wp_update_post_meta, wp_rest_request", "3"],
            ["Total", "22 read", "27 write", "49"],
        ]},
        {"kind": "meta", "text": "Counts reflect wordpress-mcp v1.0.0 as committed at 2026-07-22. wp_rest_request is classified as a write tool because it accepts arbitrary HTTP methods; it can also perform reads. The README's \"35+ tools\" claim is stale and is corrected here."},
        {"kind": "bullets", "items": [
            "Source of truth for the inventory: registration calls in Tooling/MCP/wordpress-mcp/src/tools/*.ts.",
            "Line counts: index.ts 86, client.ts 259, types.ts 169, tools/posts.ts 131, tools/pages.ts 113, tools/media.ts 121, tools/users.ts 123, tools/comments.ts 106, tools/taxonomy.ts 133, tools/woocommerce.ts 220, tools/cache.ts 106, tools/raw.ts 61 — 1,628 total.",
            "Known estate at time of writing: fernhillbd.com (WooCommerce active), fernhillconsulting.co.uk (no WooCommerce).",
            "Companion server: Tooling/MCP/cpanel-mcp/ — hosting operations and the mu-plugin deployer.",
        ]},
    ],
}
